
package mx.com.sky.sel.proxyclients.pagweb.pwremotebooking;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "bpel_pw_remotebooking_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/PAGWEB_BAM/PAGWEB_BAM/BPEL_PW_REMOTEBOOKING",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagweb/PAGWEB_BAM/bpel_pw_remotebooking_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FPAGWEB_BAM%2FPAGWEB_BAM%2FBPEL_PW_REMOTEBOOKING%7Dbpel_pw_remotebooking_client_ep")
public class BpelPwRemotebookingClientEp extends Service {

    private final static URL BPELPWREMOTEBOOKINGCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELPWREMOTEBOOKINGCLIENTEP_EXCEPTION;
    private final static QName BPELPWREMOTEBOOKINGCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/PAGWEB_BAM/PAGWEB_BAM/BPEL_PW_REMOTEBOOKING",
                  "bpel_pw_remotebooking_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagweb/PAGWEB_BAM/bpel_pw_remotebooking_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FPAGWEB_BAM%2FPAGWEB_BAM%2FBPEL_PW_REMOTEBOOKING%7Dbpel_pw_remotebooking_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELPWREMOTEBOOKINGCLIENTEP_WSDL_LOCATION = url;
        BPELPWREMOTEBOOKINGCLIENTEP_EXCEPTION = e;
    }

    public BpelPwRemotebookingClientEp() {
        super(__getWsdlLocation(), BPELPWREMOTEBOOKINGCLIENTEP_QNAME);
    }

    public BpelPwRemotebookingClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELPWREMOTEBOOKINGCLIENTEP_QNAME, features);
    }

    public BpelPwRemotebookingClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELPWREMOTEBOOKINGCLIENTEP_QNAME);
    }

    public BpelPwRemotebookingClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELPWREMOTEBOOKINGCLIENTEP_QNAME, features);
    }

    public BpelPwRemotebookingClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelPwRemotebookingClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BPELPWREMOTEBOOKING
     */
    @WebEndpoint(name = "BPEL_PW_REMOTEBOOKING_pt")
    public BPELPWREMOTEBOOKING getBPELPWREMOTEBOOKINGPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/PAGWEB_BAM/PAGWEB_BAM/BPEL_PW_REMOTEBOOKING",
                                       "BPEL_PW_REMOTEBOOKING_pt"), BPELPWREMOTEBOOKING.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BPELPWREMOTEBOOKING
     */
    @WebEndpoint(name = "BPEL_PW_REMOTEBOOKING_pt")
    public BPELPWREMOTEBOOKING getBPELPWREMOTEBOOKINGPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/PAGWEB_BAM/PAGWEB_BAM/BPEL_PW_REMOTEBOOKING",
                                       "BPEL_PW_REMOTEBOOKING_pt"), BPELPWREMOTEBOOKING.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELPWREMOTEBOOKINGCLIENTEP_EXCEPTION != null) {
            throw BPELPWREMOTEBOOKINGCLIENTEP_EXCEPTION;
        }
        return BPELPWREMOTEBOOKINGCLIENTEP_WSDL_LOCATION;
    }

}
