package mx.com.sky.sel.proxyclients.soainterface.gestionarsscomprardatos;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.3.0.0914
public class GestionarSSComprarDatosSoaInterface_ptClient {
    public static void main(String[] args) {
        GestionarSSComprarDatosSoaInterfaceEp gestionarSSComprarDatosSoaInterfaceEp =
            new GestionarSSComprarDatosSoaInterfaceEp();
        GestionarSSComprarDatosSoaInterface gestionarSSComprarDatosSoaInterface =
            gestionarSSComprarDatosSoaInterfaceEp.getGestionarSSComprarDatosSoaInterfacePt();
        // Add your code to call the desired methods.


    }
}
