
package mx.com.sky.sel.proxyclients.pagweb.altarespencusatis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagweb.altarespencusatis.types.AltaRespuestaEncuestaSatisfaccionProcessRequest;
import mx.com.sky.sel.proxyclients.pagweb.altarespencusatis.types.AltaRespuestaEncuestaSatisfaccionProcessResponse;
import mx.com.sky.sel.proxyclients.pagweb.altarespencusatis.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "AltaRespuestaEncuestaSatisfaccion",
            targetNamespace = "http://xmlns.oracle.com/AltaRespuestaEncuestaSatisfaccion")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface AltaRespuestaEncuestaSatisfaccion {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagweb.altarespencusatis.types.AltaRespuestaEncuestaSatisfaccionProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "AltaRespuestaEncuestaSatisfaccionProcessResponse",
               targetNamespace = "http://xmlns.oracle.com/AltaRespuestaEncuestaSatisfaccion", partName = "payload")
    public AltaRespuestaEncuestaSatisfaccionProcessResponse process(@WebParam(name =
                                                                              "AltaRespuestaEncuestaSatisfaccionProcessRequest",
                                                                              targetNamespace =
                                                                              "http://xmlns.oracle.com/AltaRespuestaEncuestaSatisfaccion",
                                                                              partName = "payload")
                                                                    AltaRespuestaEncuestaSatisfaccionProcessRequest payload);

}
