package mx.com.sky.sel.proxyclients.pagwebconsultas.consultatiird;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaTI_IRDClient {
    public static void main(String[] args) {
        ConsultaTIIRD_Service consultaTIIRD_Service = new ConsultaTIIRD_Service();
        ConsultaTIIRD consultaTIIRD = consultaTIIRD_Service.getConsultaTIIRD();
        // Add your code to call the desired methods.


    }
}
