
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultaladas;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultaladas.types.ConsultaLadasProcessRequest;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultaladas.types.ConsultaLadasProcessResponse;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultaladas.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaLadas",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaLadas/ConsultaLadas")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaLadas {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultaladas.types.ConsultaLadasProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "ConsultaLadasProcessResponse", targetNamespace = "http://xmlns.oracle.com/ConsultaLadas",
               partName = "payload")
    public ConsultaLadasProcessResponse process(@WebParam(name = "ConsultaLadasProcessRequest",
                                                          targetNamespace = "http://xmlns.oracle.com/ConsultaLadas",
                                                          partName = "payload") ConsultaLadasProcessRequest payload);

}
