
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultaordenmod;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultaordenmod.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaOrdenModificacion",
            targetNamespace =
            "http://xmlns.oracle.com/SKYConsultas/ConsultaOrdenModificacion/ConsultaOrdenModificacion")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaOrdenModificacion {


    /**
     *
     * @param errorDesc
     * @param errorCode
     * @param numeroCuenta
     * @param ordenModificacionPendiente
     * @param tarjetaInteligente
     */
    @WebMethod(action = "consultaOrdenModificacion")
    @RequestWrapper(localName = "consultaOrdenModificacion",
                    targetNamespace =
                    "http://xmlns.oracle.com/SKYConsultas/ConsultaOrdenModificacion/ConsultaOrdenModificacion",
                    className =
                    "mx.com.sky.sel.proxyclients.pagwebconsultas.consultaordenmod.types.ConsultaOrdenModificacion")
    @ResponseWrapper(localName = "consultaOrdenModificacionResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/SKYConsultas/ConsultaOrdenModificacion/ConsultaOrdenModificacion",
                     className =
                     "mx.com.sky.sel.proxyclients.pagwebconsultas.consultaordenmod.types.ConsultaOrdenModificacionResponse")
    public void consultaOrdenModificacion(@WebParam(name = "tarjetaInteligente",
                                                    targetNamespace =
                                                    "http://xmlns.oracle.com/SKYConsultas/ConsultaOrdenModificacion/ConsultaOrdenModificacion")
                                          String tarjetaInteligente,
                                          @WebParam(name = "numeroCuenta",
                                                    targetNamespace =
                                                    "http://xmlns.oracle.com/SKYConsultas/ConsultaOrdenModificacion/ConsultaOrdenModificacion")
                                          String numeroCuenta,
                                          @WebParam(name = "errorCode",
                                                    targetNamespace =
                                                    "http://xmlns.oracle.com/SKYConsultas/ConsultaOrdenModificacion/ConsultaOrdenModificacion",
                                                    mode = WebParam.Mode.OUT) Holder<String> errorCode,
                                          @WebParam(name = "errorDesc",
                                                    targetNamespace =
                                                    "http://xmlns.oracle.com/SKYConsultas/ConsultaOrdenModificacion/ConsultaOrdenModificacion",
                                                    mode = WebParam.Mode.OUT) Holder<String> errorDesc,
                                          @WebParam(name = "ordenModificacionPendiente",
                                                    targetNamespace =
                                                    "http://xmlns.oracle.com/SKYConsultas/ConsultaOrdenModificacion/ConsultaOrdenModificacion",
                                                    mode = WebParam.Mode.OUT)
                                          Holder<String> ordenModificacionPendiente);

}
