
package mx.com.sky.sel.proxyclients.siebelInterface.obtenercuentasky;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ObtenerCtaSkySiebelInterface_ep",
                  targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Siebel/ObtenerCtaSky",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/SIEBEL_Interface/ObtenerCtaSkySiebelInterface/ObtenerCtaSkySiebelInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSiebel%2FObtenerCtaSky%7DObtenerCtaSkySiebelInterface_ep")
public class ObtenerCtaSkySiebelInterfaceEp extends Service {

    private final static URL OBTENERCTASKYSIEBELINTERFACEEP_WSDL_LOCATION;
    private final static WebServiceException OBTENERCTASKYSIEBELINTERFACEEP_EXCEPTION;
    private final static QName OBTENERCTASKYSIEBELINTERFACEEP_QNAME =
        new QName("http://xmlns.sky.com.mx/InterfaceServices/Siebel/ObtenerCtaSky", "ObtenerCtaSkySiebelInterface_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/SIEBEL_Interface/ObtenerCtaSkySiebelInterface/ObtenerCtaSkySiebelInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSiebel%2FObtenerCtaSky%7DObtenerCtaSkySiebelInterface_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OBTENERCTASKYSIEBELINTERFACEEP_WSDL_LOCATION = url;
        OBTENERCTASKYSIEBELINTERFACEEP_EXCEPTION = e;
    }

    public ObtenerCtaSkySiebelInterfaceEp() {
        super(__getWsdlLocation(), OBTENERCTASKYSIEBELINTERFACEEP_QNAME);
    }

    public ObtenerCtaSkySiebelInterfaceEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), OBTENERCTASKYSIEBELINTERFACEEP_QNAME, features);
    }

    public ObtenerCtaSkySiebelInterfaceEp(URL wsdlLocation) {
        super(wsdlLocation, OBTENERCTASKYSIEBELINTERFACEEP_QNAME);
    }

    public ObtenerCtaSkySiebelInterfaceEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OBTENERCTASKYSIEBELINTERFACEEP_QNAME, features);
    }

    public ObtenerCtaSkySiebelInterfaceEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ObtenerCtaSkySiebelInterfaceEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ObtenerCtaSkySiebelInterface
     */
    @WebEndpoint(name = "ObtenerCtaSkySiebelInterface_pt")
    public ObtenerCtaSkySiebelInterface getObtenerCtaSkySiebelInterfacePt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Siebel/ObtenerCtaSky",
                                       "ObtenerCtaSkySiebelInterface_pt"), ObtenerCtaSkySiebelInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ObtenerCtaSkySiebelInterface
     */
    @WebEndpoint(name = "ObtenerCtaSkySiebelInterface_pt")
    public ObtenerCtaSkySiebelInterface getObtenerCtaSkySiebelInterfacePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Siebel/ObtenerCtaSky",
                                       "ObtenerCtaSkySiebelInterface_pt"), ObtenerCtaSkySiebelInterface.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (OBTENERCTASKYSIEBELINTERFACEEP_EXCEPTION != null) {
            throw OBTENERCTASKYSIEBELINTERFACEEP_EXCEPTION;
        }
        return OBTENERCTASKYSIEBELINTERFACEEP_WSDL_LOCATION;
    }

}
