
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultarevistasky;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "consultarevistasky_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaRevistaSKY/ConsultaRevistaSKY",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaRevistaSKY/consultarevistasky_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKYConsultas%2FConsultaRevistaSKY%2FConsultaRevistaSKY%7Dconsultarevistasky_client_ep")
public class ConsultarevistaskyClientEp extends Service {

    private final static URL CONSULTAREVISTASKYCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTAREVISTASKYCLIENTEP_EXCEPTION;
    private final static QName CONSULTAREVISTASKYCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaRevistaSKY/ConsultaRevistaSKY",
                  "consultarevistasky_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaRevistaSKY/consultarevistasky_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKYConsultas%2FConsultaRevistaSKY%2FConsultaRevistaSKY%7Dconsultarevistasky_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAREVISTASKYCLIENTEP_WSDL_LOCATION = url;
        CONSULTAREVISTASKYCLIENTEP_EXCEPTION = e;
    }

    public ConsultarevistaskyClientEp() {
        super(__getWsdlLocation(), CONSULTAREVISTASKYCLIENTEP_QNAME);
    }

    public ConsultarevistaskyClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAREVISTASKYCLIENTEP_QNAME, features);
    }

    public ConsultarevistaskyClientEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAREVISTASKYCLIENTEP_QNAME);
    }

    public ConsultarevistaskyClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAREVISTASKYCLIENTEP_QNAME, features);
    }

    public ConsultarevistaskyClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarevistaskyClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaRevistaSKY
     */
    @WebEndpoint(name = "ConsultaRevistaSKY_pt")
    public ConsultaRevistaSKY getConsultaRevistaSKYPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaRevistaSKY/ConsultaRevistaSKY",
                                       "ConsultaRevistaSKY_pt"), ConsultaRevistaSKY.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaRevistaSKY
     */
    @WebEndpoint(name = "ConsultaRevistaSKY_pt")
    public ConsultaRevistaSKY getConsultaRevistaSKYPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaRevistaSKY/ConsultaRevistaSKY",
                                       "ConsultaRevistaSKY_pt"), ConsultaRevistaSKY.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAREVISTASKYCLIENTEP_EXCEPTION != null) {
            throw CONSULTAREVISTASKYCLIENTEP_EXCEPTION;
        }
        return CONSULTAREVISTASKYCLIENTEP_WSDL_LOCATION;
    }

}
