
package mx.com.sky.sel.proxyclients.pagwebss.consultatablabatchaltafact;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaTablaBatchSSAltaFacturacion",
                  targetNamespace = "http://xmlns.oracle.com/ConsultaTablaBatchSSAltaFacturacion",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebss/ConsultaTablaBatchSSAltaFacturacion/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaTablaBatchSSAltaFacturacion%7DConsultaTablaBatchSSAltaFacturacion")
public class ConsultaTablaBatchSSAltaFacturacion_Service extends Service {

    private final static URL CONSULTATABLABATCHSSALTAFACTURACION_WSDL_LOCATION;
    private final static WebServiceException CONSULTATABLABATCHSSALTAFACTURACION_EXCEPTION;
    private final static QName CONSULTATABLABATCHSSALTAFACTURACION_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaTablaBatchSSAltaFacturacion", "ConsultaTablaBatchSSAltaFacturacion");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebss/ConsultaTablaBatchSSAltaFacturacion/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaTablaBatchSSAltaFacturacion%7DConsultaTablaBatchSSAltaFacturacion");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTATABLABATCHSSALTAFACTURACION_WSDL_LOCATION = url;
        CONSULTATABLABATCHSSALTAFACTURACION_EXCEPTION = e;
    }

    public ConsultaTablaBatchSSAltaFacturacion_Service() {
        super(__getWsdlLocation(), CONSULTATABLABATCHSSALTAFACTURACION_QNAME);
    }

    public ConsultaTablaBatchSSAltaFacturacion_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTATABLABATCHSSALTAFACTURACION_QNAME, features);
    }

    public ConsultaTablaBatchSSAltaFacturacion_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTATABLABATCHSSALTAFACTURACION_QNAME);
    }

    public ConsultaTablaBatchSSAltaFacturacion_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTATABLABATCHSSALTAFACTURACION_QNAME, features);
    }

    public ConsultaTablaBatchSSAltaFacturacion_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaTablaBatchSSAltaFacturacion_Service(URL wsdlLocation, QName serviceName,
                                                       WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaTablaBatchSSAltaFacturacion
     */
    @WebEndpoint(name = "ConsultaTablaBatchSSAltaFacturacion")
    public ConsultaTablaBatchSSAltaFacturacion getConsultaTablaBatchSSAltaFacturacion() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaTablaBatchSSAltaFacturacion",
                                       "ConsultaTablaBatchSSAltaFacturacion"),
                             ConsultaTablaBatchSSAltaFacturacion.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaTablaBatchSSAltaFacturacion
     */
    @WebEndpoint(name = "ConsultaTablaBatchSSAltaFacturacion")
    public ConsultaTablaBatchSSAltaFacturacion getConsultaTablaBatchSSAltaFacturacion(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaTablaBatchSSAltaFacturacion",
                                       "ConsultaTablaBatchSSAltaFacturacion"),
                             ConsultaTablaBatchSSAltaFacturacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTATABLABATCHSSALTAFACTURACION_EXCEPTION != null) {
            throw CONSULTATABLABATCHSSALTAFACTURACION_EXCEPTION;
        }
        return CONSULTATABLABATCHSSALTAFACTURACION_WSDL_LOCATION;
    }

}
