
package mx.com.sky.sel.proxyclients.soainterface.consultapreciorecargasoainterface;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaPrecioRecargaSoaInterface_ep",
                  targetNamespace =
                  "http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaPrecioRecarga",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/ConsultaPrecioRecargaSoaInterface/ConsultaPrecioRecargaSoaInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSoa%2FConsultaPrecioRecarga%7DConsultaPrecioRecargaSoaInterface_ep")
public class ConsultaPrecioRecargaSoaInterfaceEp extends Service {

    private final static URL CONSULTAPRECIORECARGASOAINTERFACEEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPRECIORECARGASOAINTERFACEEP_EXCEPTION;
    private final static QName CONSULTAPRECIORECARGASOAINTERFACEEP_QNAME =
        new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaPrecioRecarga",
                  "ConsultaPrecioRecargaSoaInterface_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/ConsultaPrecioRecargaSoaInterface/ConsultaPrecioRecargaSoaInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSoa%2FConsultaPrecioRecarga%7DConsultaPrecioRecargaSoaInterface_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPRECIORECARGASOAINTERFACEEP_WSDL_LOCATION = url;
        CONSULTAPRECIORECARGASOAINTERFACEEP_EXCEPTION = e;
    }

    public ConsultaPrecioRecargaSoaInterfaceEp() {
        super(__getWsdlLocation(), CONSULTAPRECIORECARGASOAINTERFACEEP_QNAME);
    }

    public ConsultaPrecioRecargaSoaInterfaceEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPRECIORECARGASOAINTERFACEEP_QNAME,
              features);
    }

    public ConsultaPrecioRecargaSoaInterfaceEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPRECIORECARGASOAINTERFACEEP_QNAME);
    }

    public ConsultaPrecioRecargaSoaInterfaceEp(URL wsdlLocation,
                                               WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPRECIORECARGASOAINTERFACEEP_QNAME,
              features);
    }

    public ConsultaPrecioRecargaSoaInterfaceEp(URL wsdlLocation,
                                               QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaPrecioRecargaSoaInterfaceEp(URL wsdlLocation,
                                               QName serviceName,
                                               WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaPrecioRecargaSoaInterface
     */
    @WebEndpoint(name = "ConsultaPrecioRecargaSoaInterface_pt")
    public ConsultaPrecioRecargaSoaInterface getConsultaPrecioRecargaSoaInterfacePt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaPrecioRecarga",
                                       "ConsultaPrecioRecargaSoaInterface_pt"),
                             ConsultaPrecioRecargaSoaInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaPrecioRecargaSoaInterface
     */
    @WebEndpoint(name = "ConsultaPrecioRecargaSoaInterface_pt")
    public ConsultaPrecioRecargaSoaInterface getConsultaPrecioRecargaSoaInterfacePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaPrecioRecarga",
                                       "ConsultaPrecioRecargaSoaInterface_pt"),
                             ConsultaPrecioRecargaSoaInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPRECIORECARGASOAINTERFACEEP_EXCEPTION != null) {
            throw CONSULTAPRECIORECARGASOAINTERFACEEP_EXCEPTION;
        }
        return CONSULTAPRECIORECARGASOAINTERFACEEP_WSDL_LOCATION;
    }

}
