
package mx.com.sky.sel.proxyclients.pagweb.opinionsugerencias;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagweb.opinionsugerencias.types.ObjectFactory;
import mx.com.sky.sel.proxyclients.pagweb.opinionsugerencias.types.OpinionSugerenciasProcessRequest;
import mx.com.sky.sel.proxyclients.pagweb.opinionsugerencias.types.OpinionSugerenciasProcessResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "Opinion_Sugerencias", targetNamespace = "http://xmlns.oracle.com/Opinion_Sugerencias")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface OpinionSugerencias {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagweb.opinionsugerencias.types.OpinionSugerenciasProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "Opinion_SugerenciasProcessResponse",
               targetNamespace = "http://xmlns.oracle.com/Opinion_Sugerencias", partName = "payload")
    public OpinionSugerenciasProcessResponse process(@WebParam(name = "Opinion_SugerenciasProcessRequest",
                                                               targetNamespace =
                                                               "http://xmlns.oracle.com/Opinion_Sugerencias",
                                                               partName = "payload")
                                                     OpinionSugerenciasProcessRequest payload);

}
