
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultacrregiones;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaControlRemotoRegiones",
                  targetNamespace = "http://xmlns.oracle.com/ConsultaControlRemotoRegiones",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaControlRemotoRegiones/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaControlRemotoRegiones%7DConsultaControlRemotoRegiones")
public class ConsultaControlRemotoRegiones_Service extends Service {

    private final static URL CONSULTACONTROLREMOTOREGIONES_WSDL_LOCATION;
    private final static WebServiceException CONSULTACONTROLREMOTOREGIONES_EXCEPTION;
    private final static QName CONSULTACONTROLREMOTOREGIONES_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaControlRemotoRegiones", "ConsultaControlRemotoRegiones");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaControlRemotoRegiones/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaControlRemotoRegiones%7DConsultaControlRemotoRegiones");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTACONTROLREMOTOREGIONES_WSDL_LOCATION = url;
        CONSULTACONTROLREMOTOREGIONES_EXCEPTION = e;
    }

    public ConsultaControlRemotoRegiones_Service() {
        super(__getWsdlLocation(), CONSULTACONTROLREMOTOREGIONES_QNAME);
    }

    public ConsultaControlRemotoRegiones_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTACONTROLREMOTOREGIONES_QNAME, features);
    }

    public ConsultaControlRemotoRegiones_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTACONTROLREMOTOREGIONES_QNAME);
    }

    public ConsultaControlRemotoRegiones_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTACONTROLREMOTOREGIONES_QNAME, features);
    }

    public ConsultaControlRemotoRegiones_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaControlRemotoRegiones_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaControlRemotoRegiones
     */
    @WebEndpoint(name = "ConsultaControlRemotoRegiones")
    public ConsultaControlRemotoRegiones getConsultaControlRemotoRegiones() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaControlRemotoRegiones",
                                       "ConsultaControlRemotoRegiones"), ConsultaControlRemotoRegiones.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaControlRemotoRegiones
     */
    @WebEndpoint(name = "ConsultaControlRemotoRegiones")
    public ConsultaControlRemotoRegiones getConsultaControlRemotoRegiones(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaControlRemotoRegiones",
                                       "ConsultaControlRemotoRegiones"), ConsultaControlRemotoRegiones.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTACONTROLREMOTOREGIONES_EXCEPTION != null) {
            throw CONSULTACONTROLREMOTOREGIONES_EXCEPTION;
        }
        return CONSULTACONTROLREMOTOREGIONES_WSDL_LOCATION;
    }

}
