
package mx.com.sky.sel.proxyclients.pagweb.cargaarchivoeventos;

import java.util.List;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

import mx.com.sky.sel.proxyclients.pagweb.cargaarchivoeventos.types.AttachmentType;
import mx.com.sky.sel.proxyclients.pagweb.cargaarchivoeventos.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "BPELCargaArchivoEventos",
            targetNamespace = "http://xmlns.oracle.com/SKYPortal/CargaArchivoEventos/BPELCargaArchivoEventos")
@XmlSeeAlso({ ObjectFactory.class })
public interface BPELCargaArchivoEventos {


    /**
     *
     * @param attachments
     */
    @WebMethod(action = "process")
    @Oneway
    @RequestWrapper(localName = "process",
                    targetNamespace = "http://xmlns.oracle.com/SKYPortal/CargaArchivoEventos/CargaArchivoEventos",
                    className = "mx.com.sky.sel.proxyclients.pagweb.cargaarchivoeventos.types.Process")
    public void process(@WebParam(name = "ATTACHMENTS",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/CargaArchivoEventos/CargaArchivoEventos")
                        List<AttachmentType> attachments);

}
