
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultacambiospenmodulos;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaCambiosPendientesModulos",
                  targetNamespace = "http://xmlns.oracle.com/ConsultaCambiosPendientesModulos",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaCambiosPendientesModulos/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaCambiosPendientesModulos%7DConsultaCambiosPendientesModulos")
public class ConsultaCambiosPendientesModulos_Service extends Service {

    private final static URL CONSULTACAMBIOSPENDIENTESMODULOS_WSDL_LOCATION;
    private final static WebServiceException CONSULTACAMBIOSPENDIENTESMODULOS_EXCEPTION;
    private final static QName CONSULTACAMBIOSPENDIENTESMODULOS_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaCambiosPendientesModulos", "ConsultaCambiosPendientesModulos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaCambiosPendientesModulos/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaCambiosPendientesModulos%7DConsultaCambiosPendientesModulos");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTACAMBIOSPENDIENTESMODULOS_WSDL_LOCATION = url;
        CONSULTACAMBIOSPENDIENTESMODULOS_EXCEPTION = e;
    }

    public ConsultaCambiosPendientesModulos_Service() {
        super(__getWsdlLocation(), CONSULTACAMBIOSPENDIENTESMODULOS_QNAME);
    }

    public ConsultaCambiosPendientesModulos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTACAMBIOSPENDIENTESMODULOS_QNAME, features);
    }

    public ConsultaCambiosPendientesModulos_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTACAMBIOSPENDIENTESMODULOS_QNAME);
    }

    public ConsultaCambiosPendientesModulos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTACAMBIOSPENDIENTESMODULOS_QNAME, features);
    }

    public ConsultaCambiosPendientesModulos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaCambiosPendientesModulos_Service(URL wsdlLocation, QName serviceName,
                                                    WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaCambiosPendientesModulos
     */
    @WebEndpoint(name = "ConsultaCambiosPendientesModulos")
    public ConsultaCambiosPendientesModulos getConsultaCambiosPendientesModulos() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaCambiosPendientesModulos",
                                       "ConsultaCambiosPendientesModulos"), ConsultaCambiosPendientesModulos.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaCambiosPendientesModulos
     */
    @WebEndpoint(name = "ConsultaCambiosPendientesModulos")
    public ConsultaCambiosPendientesModulos getConsultaCambiosPendientesModulos(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaCambiosPendientesModulos",
                                       "ConsultaCambiosPendientesModulos"), ConsultaCambiosPendientesModulos.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTACAMBIOSPENDIENTESMODULOS_EXCEPTION != null) {
            throw CONSULTACAMBIOSPENDIENTESMODULOS_EXCEPTION;
        }
        return CONSULTACAMBIOSPENDIENTESMODULOS_WSDL_LOCATION;
    }

}
