
package mx.com.sky.sel.proxyclients.pagwebss.consultasolicitudservicio;

import com.oracle.xmlns.consultasolicituddeservicio.ConsultaSolicitudDeServicioProcessRequest;
import com.oracle.xmlns.consultasolicituddeservicio.ConsultaSolicitudDeServicioProcessResponse;
import com.oracle.xmlns.consultasolicituddeservicio.ObjectFactory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import com.oracle.xmlns.consultasolicituddeservicio.ConsultaSolicitudDeServicioProcessRequest;
import com.oracle.xmlns.consultasolicituddeservicio.ConsultaSolicitudDeServicioProcessResponse;
import com.oracle.xmlns.consultasolicituddeservicio.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaSolicitudDeServicio",
            targetNamespace = "http://xmlns.oracle.com/ConsultaSolicitudDeServicio")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaSolicitudDeServicio {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebss.consultasolicitudservicio.types.ConsultaSolicitudDeServicioProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "ConsultaSolicitudDeServicioProcessResponse",
               targetNamespace = "http://xmlns.oracle.com/ConsultaSolicitudDeServicio", partName = "payload")
    public ConsultaSolicitudDeServicioProcessResponse process(@WebParam(name =
                                                                        "ConsultaSolicitudDeServicioProcessRequest",
                                                                        targetNamespace =
                                                                        "http://xmlns.oracle.com/ConsultaSolicitudDeServicio",
                                                                        partName = "payload")
                                                              ConsultaSolicitudDeServicioProcessRequest payload);

}
