
package mx.com.sky.sel.proxyclients.pagwebss.consultasolicitudservicio;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaSolicitudDeServicio",
                  targetNamespace = "http://xmlns.oracle.com/ConsultaSolicitudDeServicio",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebss/ConsultaSolicitudDeServicio/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaSolicitudDeServicio%7DConsultaSolicitudDeServicio")
public class ConsultaSolicitudDeServicio_Service extends Service {

    private final static URL CONSULTASOLICITUDDESERVICIO_WSDL_LOCATION;
    private final static WebServiceException CONSULTASOLICITUDDESERVICIO_EXCEPTION;
    private final static QName CONSULTASOLICITUDDESERVICIO_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaSolicitudDeServicio", "ConsultaSolicitudDeServicio");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebss/ConsultaSolicitudDeServicio/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaSolicitudDeServicio%7DConsultaSolicitudDeServicio");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTASOLICITUDDESERVICIO_WSDL_LOCATION = url;
        CONSULTASOLICITUDDESERVICIO_EXCEPTION = e;
    }

    public ConsultaSolicitudDeServicio_Service() {
        super(__getWsdlLocation(), CONSULTASOLICITUDDESERVICIO_QNAME);
    }

    public ConsultaSolicitudDeServicio_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTASOLICITUDDESERVICIO_QNAME, features);
    }

    public ConsultaSolicitudDeServicio_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTASOLICITUDDESERVICIO_QNAME);
    }

    public ConsultaSolicitudDeServicio_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTASOLICITUDDESERVICIO_QNAME, features);
    }

    public ConsultaSolicitudDeServicio_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaSolicitudDeServicio_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaSolicitudDeServicio
     */
    @WebEndpoint(name = "ConsultaSolicitudDeServicio")
    public ConsultaSolicitudDeServicio getConsultaSolicitudDeServicio() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaSolicitudDeServicio",
                                       "ConsultaSolicitudDeServicio"), ConsultaSolicitudDeServicio.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaSolicitudDeServicio
     */
    @WebEndpoint(name = "ConsultaSolicitudDeServicio")
    public ConsultaSolicitudDeServicio getConsultaSolicitudDeServicio(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaSolicitudDeServicio",
                                       "ConsultaSolicitudDeServicio"), ConsultaSolicitudDeServicio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTASOLICITUDDESERVICIO_EXCEPTION != null) {
            throw CONSULTASOLICITUDDESERVICIO_EXCEPTION;
        }
        return CONSULTASOLICITUDDESERVICIO_WSDL_LOCATION;
    }

}
