
package mx.com.sky.sel.proxyclients.pagweb.admonbtgew;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagweb.admonbtgew.types.AdmonBTGEWINType;
import mx.com.sky.sel.proxyclients.pagweb.admonbtgew.types.AdmonBTGEWOUTType;
import mx.com.sky.sel.proxyclients.pagweb.admonbtgew.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "AdmonBTGEW", targetNamespace = "http://xmlns.oracle.com/SKYPortal/AdmonBTGEW/AdmonBTGEW")
@XmlSeeAlso({ ObjectFactory.class })
public interface AdmonBTGEW {


    /**
     *
     * @param input
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagweb.admonbtgew.types.AdmonBTGEWOUTType
     */
    @WebMethod(action = "process")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/SKYPortal/AdmonBTGEW/AdmonBTGEW")
    @RequestWrapper(localName = "process", targetNamespace = "http://xmlns.oracle.com/SKYPortal/AdmonBTGEW/AdmonBTGEW",
                    className = "mx.com.sky.sel.proxyclients.pagweb.admonbtgew.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace = "http://xmlns.oracle.com/SKYPortal/AdmonBTGEW/AdmonBTGEW",
                     className = "mx.com.sky.sel.proxyclients.pagweb.admonbtgew.types.ProcessResponse")
    public AdmonBTGEWOUTType process(@WebParam(name = "input",
                                               targetNamespace =
                                               "http://xmlns.oracle.com/SKYPortal/AdmonBTGEW/AdmonBTGEW")
                                     AdmonBTGEWINType input);

}
