
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultacrdirecciones;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaControlRemotoDirecciones",
                  targetNamespace = "http://xmlns.oracle.com/ConsultaControlRemotoDirecciones",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaControlRemotoDirecciones/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaControlRemotoDirecciones%7DConsultaControlRemotoDirecciones")
public class ConsultaControlRemotoDirecciones_Service extends Service {

    private final static URL CONSULTACONTROLREMOTODIRECCIONES_WSDL_LOCATION;
    private final static WebServiceException CONSULTACONTROLREMOTODIRECCIONES_EXCEPTION;
    private final static QName CONSULTACONTROLREMOTODIRECCIONES_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaControlRemotoDirecciones", "ConsultaControlRemotoDirecciones");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaControlRemotoDirecciones/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaControlRemotoDirecciones%7DConsultaControlRemotoDirecciones");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTACONTROLREMOTODIRECCIONES_WSDL_LOCATION = url;
        CONSULTACONTROLREMOTODIRECCIONES_EXCEPTION = e;
    }

    public ConsultaControlRemotoDirecciones_Service() {
        super(__getWsdlLocation(), CONSULTACONTROLREMOTODIRECCIONES_QNAME);
    }

    public ConsultaControlRemotoDirecciones_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTACONTROLREMOTODIRECCIONES_QNAME, features);
    }

    public ConsultaControlRemotoDirecciones_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTACONTROLREMOTODIRECCIONES_QNAME);
    }

    public ConsultaControlRemotoDirecciones_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTACONTROLREMOTODIRECCIONES_QNAME, features);
    }

    public ConsultaControlRemotoDirecciones_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaControlRemotoDirecciones_Service(URL wsdlLocation, QName serviceName,
                                                    WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaControlRemotoDirecciones
     */
    @WebEndpoint(name = "ConsultaControlRemotoDirecciones")
    public ConsultaControlRemotoDirecciones getConsultaControlRemotoDirecciones() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaControlRemotoDirecciones",
                                       "ConsultaControlRemotoDirecciones"), ConsultaControlRemotoDirecciones.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaControlRemotoDirecciones
     */
    @WebEndpoint(name = "ConsultaControlRemotoDirecciones")
    public ConsultaControlRemotoDirecciones getConsultaControlRemotoDirecciones(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaControlRemotoDirecciones",
                                       "ConsultaControlRemotoDirecciones"), ConsultaControlRemotoDirecciones.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTACONTROLREMOTODIRECCIONES_EXCEPTION != null) {
            throw CONSULTACONTROLREMOTODIRECCIONES_EXCEPTION;
        }
        return CONSULTACONTROLREMOTODIRECCIONES_WSDL_LOCATION;
    }

}
