
package mx.com.sky.sel.proxyclients.selabcs.consultapaqadicionaldatos;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaPaqAdicionalDatosSelABCS_ep",
                  targetNamespace =
                  "http://xmlns.sky.com.mx/ABCSImpl/Sel/ConsultarPaqAdicionalDatos",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_ABCS/ConsultaPaqAdicionalDatosSelABCS/ConsultaPaqAdicionalDatosSelABCS_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FABCSImpl%2FSel%2FConsultarPaqAdicionalDatos%7DConsultaPaqAdicionalDatosSelABCS_ep")
public class ConsultaPaqAdicionalDatosSelABCSEp extends Service {

    private final static URL CONSULTAPAQADICIONALDATOSSELABCSEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPAQADICIONALDATOSSELABCSEP_EXCEPTION;
    private final static QName CONSULTAPAQADICIONALDATOSSELABCSEP_QNAME =
        new QName("http://xmlns.sky.com.mx/ABCSImpl/Sel/ConsultarPaqAdicionalDatos",
                  "ConsultaPaqAdicionalDatosSelABCS_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_ABCS/ConsultaPaqAdicionalDatosSelABCS/ConsultaPaqAdicionalDatosSelABCS_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FABCSImpl%2FSel%2FConsultarPaqAdicionalDatos%7DConsultaPaqAdicionalDatosSelABCS_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPAQADICIONALDATOSSELABCSEP_WSDL_LOCATION = url;
        CONSULTAPAQADICIONALDATOSSELABCSEP_EXCEPTION = e;
    }

    public ConsultaPaqAdicionalDatosSelABCSEp() {
        super(__getWsdlLocation(), CONSULTAPAQADICIONALDATOSSELABCSEP_QNAME);
    }

    public ConsultaPaqAdicionalDatosSelABCSEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPAQADICIONALDATOSSELABCSEP_QNAME,
              features);
    }

    public ConsultaPaqAdicionalDatosSelABCSEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPAQADICIONALDATOSSELABCSEP_QNAME);
    }

    public ConsultaPaqAdicionalDatosSelABCSEp(URL wsdlLocation,
                                              WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPAQADICIONALDATOSSELABCSEP_QNAME, features);
    }

    public ConsultaPaqAdicionalDatosSelABCSEp(URL wsdlLocation,
                                              QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaPaqAdicionalDatosSelABCSEp(URL wsdlLocation,
                                              QName serviceName,
                                              WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaPaqAdicionalDatosSelABCS
     */
    @WebEndpoint(name = "ConsultaPaqAdicionalDatosSelABCS_pt")
    public ConsultaPaqAdicionalDatosSelABCS getConsultaPaqAdicionalDatosSelABCSPt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/ABCSImpl/Sel/ConsultarPaqAdicionalDatos",
                                       "ConsultaPaqAdicionalDatosSelABCS_pt"),
                             ConsultaPaqAdicionalDatosSelABCS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaPaqAdicionalDatosSelABCS
     */
    @WebEndpoint(name = "ConsultaPaqAdicionalDatosSelABCS_pt")
    public ConsultaPaqAdicionalDatosSelABCS getConsultaPaqAdicionalDatosSelABCSPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/ABCSImpl/Sel/ConsultarPaqAdicionalDatos",
                                       "ConsultaPaqAdicionalDatosSelABCS_pt"),
                             ConsultaPaqAdicionalDatosSelABCS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPAQADICIONALDATOSSELABCSEP_EXCEPTION != null) {
            throw CONSULTAPAQADICIONALDATOSSELABCSEP_EXCEPTION;
        }
        return CONSULTAPAQADICIONALDATOSSELABCSEP_WSDL_LOCATION;
    }

}
