
package mx.com.sky.sel.proxyclients.pagweb.validacrecimientosvetv;

import java.math.BigDecimal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagweb.validacrecimientosvetv.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ValidaCrecimientos_VeTV",
            targetNamespace =
            "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_VeTV")
@XmlSeeAlso({ ObjectFactory.class })
public interface ValidaCrecimientosVeTV {


    /**
     *
     * @param precio
     * @param codigoError
     * @param cuentaSKY
     * @param valido
     * @param descError
     */
    @WebMethod(action = "validaCrecimientosVeTV")
    @RequestWrapper(localName = "validaCrecimientosVeTV",
                    targetNamespace =
                    "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_VeTV",
                    className =
                    "mx.com.sky.sel.proxyclients.pagweb.validacrecimientosvetv.types.ValidaCrecimientosVeTV")
    @ResponseWrapper(localName = "validaCrecimientosVeTVResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_VeTV",
                     className =
                     "mx.com.sky.sel.proxyclients.pagweb.validacrecimientosvetv.types.ValidaCrecimientosVeTVResponse")
    public void validaCrecimientosVeTV(@WebParam(name = "cuentaSKY",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_VeTV")
                                       String cuentaSKY,
                                       @WebParam(name = "valido",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_VeTV",
                                                 mode = WebParam.Mode.OUT) Holder<BigDecimal> valido,
                                       @WebParam(name = "precio",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_VeTV",
                                                 mode = WebParam.Mode.OUT) Holder<String> precio,
                                       @WebParam(name = "codigoError",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_VeTV",
                                                 mode = WebParam.Mode.OUT) Holder<String> codigoError,
                                       @WebParam(name = "descError",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_VeTV",
                                                 mode = WebParam.Mode.OUT) Holder<String> descError);

}
