
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultacanalescarta;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaCanalesALaCarta", targetNamespace = "http://xmlns.oracle.com/ConsultaCanalesALaCarta",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaCanalesALaCarta/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaCanalesALaCarta%7DConsultaCanalesALaCarta")
public class ConsultaCanalesALaCarta_Service extends Service {

    private final static URL CONSULTACANALESALACARTA_WSDL_LOCATION;
    private final static WebServiceException CONSULTACANALESALACARTA_EXCEPTION;
    private final static QName CONSULTACANALESALACARTA_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaCanalesALaCarta", "ConsultaCanalesALaCarta");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaCanalesALaCarta/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaCanalesALaCarta%7DConsultaCanalesALaCarta");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTACANALESALACARTA_WSDL_LOCATION = url;
        CONSULTACANALESALACARTA_EXCEPTION = e;
    }

    public ConsultaCanalesALaCarta_Service() {
        super(__getWsdlLocation(), CONSULTACANALESALACARTA_QNAME);
    }

    public ConsultaCanalesALaCarta_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTACANALESALACARTA_QNAME, features);
    }

    public ConsultaCanalesALaCarta_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTACANALESALACARTA_QNAME);
    }

    public ConsultaCanalesALaCarta_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTACANALESALACARTA_QNAME, features);
    }

    public ConsultaCanalesALaCarta_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaCanalesALaCarta_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaCanalesALaCarta
     */
    @WebEndpoint(name = "ConsultaCanalesALaCarta")
    public ConsultaCanalesALaCarta getConsultaCanalesALaCarta() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaCanalesALaCarta", "ConsultaCanalesALaCarta"),
                             ConsultaCanalesALaCarta.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaCanalesALaCarta
     */
    @WebEndpoint(name = "ConsultaCanalesALaCarta")
    public ConsultaCanalesALaCarta getConsultaCanalesALaCarta(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaCanalesALaCarta", "ConsultaCanalesALaCarta"),
                             ConsultaCanalesALaCarta.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTACANALESALACARTA_EXCEPTION != null) {
            throw CONSULTACANALESALACARTA_EXCEPTION;
        }
        return CONSULTACANALESALACARTA_WSDL_LOCATION;
    }

}
