package mx.com.sky.sel.proxyclients.pagwebregistro.reenviamailpreregistro;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ReEnviaMailPreRegistroClient {
    public static void main(String[] args) {
        ReEnviaMailPreRegistro_Service reEnviaMailPreRegistro_Service = new ReEnviaMailPreRegistro_Service();
        ReEnviaMailPreRegistro reEnviaMailPreRegistro = reEnviaMailPreRegistro_Service.getReEnviaMailPreRegistro();
        // Add your code to call the desired methods.


    }
}
