
package mx.com.sky.sel.proxyclients.soainterface.consultacobertura;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseobjects.soa.consultacoberturainterface.ConsultaCoberturaRequestEBMType;
import mx.com.sky.enterpriseobjects.soa.consultacoberturainterface.ConsultaCoberturaResponseEBMType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaCoberturaSoaInterface",
            targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaCobertura")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ mx.com.sky.soasky.ObjectFactory.class, mx.com.sky.enterpriseobjects.sel.common.v1.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.soa.consultacoberturainterface.ObjectFactory.class,
              org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class,
              org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class
    })
public interface ConsultaCoberturaSoaInterface {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseobjects.soa.consultacoberturainterface.ConsultaCoberturaResponseEBMType
     */
    @WebMethod(action = "http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaCobertura/consultaCobertura")
    @WebResult(name = "ConsultaCoberturaResponseEBM",
               targetNamespace = "http://www.sky.com.mx/EnterpriseObjects/Soa/ConsultaCoberturaInterface",
               partName = "payload")
    public ConsultaCoberturaResponseEBMType consultaCobertura(@WebParam(name = "ConsultaCoberturaRequestEBM",
                                                                        targetNamespace =
                                                                        "http://www.sky.com.mx/EnterpriseObjects/Soa/ConsultaCoberturaInterface",
                                                                        partName = "payload")
                                                              ConsultaCoberturaRequestEBMType payload);

}
