package mx.com.sky.sel.proxyclients.selebf.recuperarpasswordusr;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class RecuperarPasswordUsrSelEBF_ptClient {
    public static void main(String[] args) {
        RecuperarPasswordUsrSelEBFEp recuperarPasswordUsrSelEBFEp = new RecuperarPasswordUsrSelEBFEp();
        RecuperarPasswordUsrSelEBF recuperarPasswordUsrSelEBF =
            recuperarPasswordUsrSelEBFEp.getRecuperarPasswordUsrSelEBFPt();
        // Add your code to call the desired methods.


    }
}
