package mx.com.sky.sel.proxyclients.pagweb.consultaldap;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaLDAPClient {
    public static void main(String[] args) {
        ConsultaLDAP_Service consultaLDAP_Service = new ConsultaLDAP_Service();
        ConsultaLDAP consultaLDAP = consultaLDAP_Service.getConsultaLDAP();
        // Add your code to call the desired methods.


    }
}
