package mx.com.sky.sel.proxyclients.soainterface.consultappvcontratados;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="https://qaselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/Suscriptor_consultaPPVContratadosSOAInterface/suscriptor_consultappvcontratadossoainterface_client_ep?WSDL",
  targetNamespace="http://xmlns.sky.com.mx/InterfaceServices/SOA/Suscriptor_consultaPPVContratadosSOAInterface",
  name="Suscriptor_consultaPPVContratadosSOAInterface")
@XmlSeeAlso(
  { mx.com.sky.sel.proxyclients.soainterface.consultappvcontratados.types.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface Suscriptor_consultaPPVContratadosSOAInterface
{
  @WebMethod(action="http://xmlns.sky.com.mx/InterfaceServices/SOA/Suscriptor_consultaPPVContratadosSOAInterface/suscriptorConsultaPPVContratados")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.sky.com.mx/InterfaceServices/SOA/Suscriptor_consultaPPVContratadosSOAInterface/suscriptorConsultaPPVContratados",
    output="http://xmlns.sky.com.mx/InterfaceServices/SOA/Suscriptor_consultaPPVContratadosSOAInterface/Suscriptor_consultaPPVContratadosSOAInterface/suscriptorConsultaPPVContratadosResponse")
  @WebResult(targetNamespace="http://www.sky.com.mx/EnterpriseObjects/SOA/Suscriptor_consultaPPVContratadosEBM",
    partName="payload", name="Suscriptor_consultaPPVContratadosEBMResponse")
  public mx.com.sky.sel.proxyclients.soainterface.consultappvcontratados.types.SuscriptorConsultaPPVContratadosEBMResponseTYPESalida suscriptorConsultaPPVContratados(@WebParam(targetNamespace="http://www.sky.com.mx/EnterpriseObjects/SOA/Suscriptor_consultaPPVContratadosEBM",
      partName="payload", name="Suscriptor_consultaPPVContratadosEBMRequest")
    mx.com.sky.sel.proxyclients.soainterface.consultappvcontratados.types.SuscriptorConsultaPPVContratadosEBMRequestTYPE payload);
}
