
package mx.com.sky.sel.proxyclients.pagweb.admonmodulares;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "AdmonModulares", targetNamespace = "http://xmlns.oracle.com/AdmonModulares",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagweb/AdmonModulares/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FAdmonModulares%7DAdmonModulares")
public class AdmonModulares_Service extends Service {

    private final static URL ADMONMODULARES_WSDL_LOCATION;
    private final static WebServiceException ADMONMODULARES_EXCEPTION;
    private final static QName ADMONMODULARES_QNAME =
        new QName("http://xmlns.oracle.com/AdmonModulares", "AdmonModulares");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagweb/AdmonModulares/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FAdmonModulares%7DAdmonModulares");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMONMODULARES_WSDL_LOCATION = url;
        ADMONMODULARES_EXCEPTION = e;
    }

    public AdmonModulares_Service() {
        super(__getWsdlLocation(), ADMONMODULARES_QNAME);
    }

    public AdmonModulares_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMONMODULARES_QNAME, features);
    }

    public AdmonModulares_Service(URL wsdlLocation) {
        super(wsdlLocation, ADMONMODULARES_QNAME);
    }

    public AdmonModulares_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMONMODULARES_QNAME, features);
    }

    public AdmonModulares_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdmonModulares_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AdmonModulares
     */
    @WebEndpoint(name = "AdmonModulares")
    public AdmonModulares getAdmonModulares() {
        return super.getPort(new QName("http://xmlns.oracle.com/AdmonModulares", "AdmonModulares"),
                             AdmonModulares.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdmonModulares
     */
    @WebEndpoint(name = "AdmonModulares")
    public AdmonModulares getAdmonModulares(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/AdmonModulares", "AdmonModulares"),
                             AdmonModulares.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMONMODULARES_EXCEPTION != null) {
            throw ADMONMODULARES_EXCEPTION;
        }
        return ADMONMODULARES_WSDL_LOCATION;
    }

}
