
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultauuidsicof;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "consultauuidsicof_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/AppFacturaEdicom/ConsultaFacturasSICOF/ConsultaUUIDSicof",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaFacturasSICOF/consultauuidsicof_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FAppFacturaEdicom%2FConsultaFacturasSICOF%2FConsultaUUIDSicof%7Dconsultauuidsicof_client_ep")
public class ConsultauuidsicofClientEp extends Service {

    private final static URL CONSULTAUUIDSICOFCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTAUUIDSICOFCLIENTEP_EXCEPTION;
    private final static QName CONSULTAUUIDSICOFCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/AppFacturaEdicom/ConsultaFacturasSICOF/ConsultaUUIDSicof",
                  "consultauuidsicof_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaFacturasSICOF/consultauuidsicof_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FAppFacturaEdicom%2FConsultaFacturasSICOF%2FConsultaUUIDSicof%7Dconsultauuidsicof_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAUUIDSICOFCLIENTEP_WSDL_LOCATION = url;
        CONSULTAUUIDSICOFCLIENTEP_EXCEPTION = e;
    }

    public ConsultauuidsicofClientEp() {
        super(__getWsdlLocation(), CONSULTAUUIDSICOFCLIENTEP_QNAME);
    }

    public ConsultauuidsicofClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAUUIDSICOFCLIENTEP_QNAME, features);
    }

    public ConsultauuidsicofClientEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAUUIDSICOFCLIENTEP_QNAME);
    }

    public ConsultauuidsicofClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAUUIDSICOFCLIENTEP_QNAME, features);
    }

    public ConsultauuidsicofClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultauuidsicofClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaUUIDSicof
     */
    @WebEndpoint(name = "ConsultaUUIDSicof_pt")
    public ConsultaUUIDSicof getConsultaUUIDSicofPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/AppFacturaEdicom/ConsultaFacturasSICOF/ConsultaUUIDSicof",
                                       "ConsultaUUIDSicof_pt"), ConsultaUUIDSicof.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaUUIDSicof
     */
    @WebEndpoint(name = "ConsultaUUIDSicof_pt")
    public ConsultaUUIDSicof getConsultaUUIDSicofPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/AppFacturaEdicom/ConsultaFacturasSICOF/ConsultaUUIDSicof",
                                       "ConsultaUUIDSicof_pt"), ConsultaUUIDSicof.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAUUIDSICOFCLIENTEP_EXCEPTION != null) {
            throw CONSULTAUUIDSICOFCLIENTEP_EXCEPTION;
        }
        return CONSULTAUUIDSICOFCLIENTEP_WSDL_LOCATION;
    }

}
