
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultauuidsicof;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultauuidsicof.types.ConsultaUUIDInType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultauuidsicof.types.ConsultaUUIDOutType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultauuidsicof.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaUUIDSicof",
            targetNamespace = "http://xmlns.oracle.com/AppFacturaEdicom/ConsultaFacturasSICOF/ConsultaUUIDSicof")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaUUIDSicof {


    /**
     *
     * @param input
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultauuidsicof.types.ConsultaUUIDOutType
     */
    @WebMethod(action = "process")
    @WebResult(name = "result",
               targetNamespace = "http://xmlns.oracle.com/AppFacturaEdicom/ConsultaFacturasSICOF/ConsultaUUIDSicof")
    @RequestWrapper(localName = "process",
                    targetNamespace =
                    "http://xmlns.oracle.com/AppFacturaEdicom/ConsultaFacturasSICOF/ConsultaUUIDSicof",
                    className = "mx.com.sky.sel.proxyclients.pagwebconsultas.consultauuidsicof.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/AppFacturaEdicom/ConsultaFacturasSICOF/ConsultaUUIDSicof",
                     className = "mx.com.sky.sel.proxyclients.pagwebconsultas.consultauuidsicof.types.ProcessResponse")
    public ConsultaUUIDOutType process(@WebParam(name = "input",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/AppFacturaEdicom/ConsultaFacturasSICOF/ConsultaUUIDSicof")
                                       ConsultaUUIDInType input);

}
