
package mx.com.sky.sel.proxyclients.soainterface.crearsolicitudservicio;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CrearSolicitudServicioSoaInterface_ep",
                  targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Soa/CrearSolicitudServicioSoaInterface",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/CrearSolicitudServicioSoaInterface/CrearSolicitudServicioSoaInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSoa%2FCrearSolicitudServicioSoaInterface%7DCrearSolicitudServicioSoaInterface_ep")
public class CrearSolicitudServicioSoaInterfaceEp extends Service {

    private final static URL CREARSOLICITUDSERVICIOSOAINTERFACEEP_WSDL_LOCATION;
    private final static WebServiceException CREARSOLICITUDSERVICIOSOAINTERFACEEP_EXCEPTION;
    private final static QName CREARSOLICITUDSERVICIOSOAINTERFACEEP_QNAME =
        new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/CrearSolicitudServicioSoaInterface",
                  "CrearSolicitudServicioSoaInterface_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/CrearSolicitudServicioSoaInterface/CrearSolicitudServicioSoaInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSoa%2FCrearSolicitudServicioSoaInterface%7DCrearSolicitudServicioSoaInterface_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREARSOLICITUDSERVICIOSOAINTERFACEEP_WSDL_LOCATION = url;
        CREARSOLICITUDSERVICIOSOAINTERFACEEP_EXCEPTION = e;
    }

    public CrearSolicitudServicioSoaInterfaceEp() {
        super(__getWsdlLocation(), CREARSOLICITUDSERVICIOSOAINTERFACEEP_QNAME);
    }

    public CrearSolicitudServicioSoaInterfaceEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREARSOLICITUDSERVICIOSOAINTERFACEEP_QNAME, features);
    }

    public CrearSolicitudServicioSoaInterfaceEp(URL wsdlLocation) {
        super(wsdlLocation, CREARSOLICITUDSERVICIOSOAINTERFACEEP_QNAME);
    }

    public CrearSolicitudServicioSoaInterfaceEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREARSOLICITUDSERVICIOSOAINTERFACEEP_QNAME, features);
    }

    public CrearSolicitudServicioSoaInterfaceEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrearSolicitudServicioSoaInterfaceEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CrearSolicitudServicioSoaInterface
     */
    @WebEndpoint(name = "CrearSolicitudServicioSoaInterface_pt")
    public CrearSolicitudServicioSoaInterface getCrearSolicitudServicioSoaInterfacePt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/CrearSolicitudServicioSoaInterface",
                                       "CrearSolicitudServicioSoaInterface_pt"),
                             CrearSolicitudServicioSoaInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrearSolicitudServicioSoaInterface
     */
    @WebEndpoint(name = "CrearSolicitudServicioSoaInterface_pt")
    public CrearSolicitudServicioSoaInterface getCrearSolicitudServicioSoaInterfacePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/CrearSolicitudServicioSoaInterface",
                                       "CrearSolicitudServicioSoaInterface_pt"),
                             CrearSolicitudServicioSoaInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREARSOLICITUDSERVICIOSOAINTERFACEEP_EXCEPTION != null) {
            throw CREARSOLICITUDSERVICIOSOAINTERFACEEP_EXCEPTION;
        }
        return CREARSOLICITUDSERVICIOSOAINTERFACEEP_WSDL_LOCATION;
    }

}
