
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultatiirdprincipal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultatiirdprincipal.types.CTINType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultatiirdprincipal.types.CTOutType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultatiirdprincipal.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaTI_IRD_Principal",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaCambioTitular/ConsultaTI_IRD_Principal")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaTIIRDPrincipal {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultatiirdprincipal.types.CTOutType
     */
    @WebMethod(action = "process")
    @WebResult(name = "CT_Out", targetNamespace = "http://cambiotitular.serviciosenlinea.sky.com.mx",
               partName = "payload")
    public CTOutType process(@WebParam(name = "CT_In",
                                       targetNamespace = "http://cambiotitular.serviciosenlinea.sky.com.mx",
                                       partName = "payload") CTINType payload);

}
