package mx.com.sky.sel.proxyclients.pagwebconsultas.consultatiirdprincipal;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaTI_IRD_Principal_ptClient {
    public static void main(String[] args) {
        ConsultatiIrdPrincipalClientEp consultatiIrdPrincipalClientEp = new ConsultatiIrdPrincipalClientEp();
        ConsultaTIIRDPrincipal consultaTIIRDPrincipal = consultatiIrdPrincipalClientEp.getConsultaTIIRDPrincipalPt();
        // Add your code to call the desired methods.


    }
}
