
package mx.com.sky.sel.proxyclients.pagweb.bamsessions;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "bpel_bam_sessions_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/PAGWEB_BAM/PAGWEB_BAM/BPEL_BAM_SESSIONS",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagweb/PAGWEB_BAM/bpel_bam_sessions_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FPAGWEB_BAM%2FPAGWEB_BAM%2FBPEL_BAM_SESSIONS%7Dbpel_bam_sessions_client_ep")
public class BpelBamSessionsClientEp extends Service {

    private final static URL BPELBAMSESSIONSCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BPELBAMSESSIONSCLIENTEP_EXCEPTION;
    private final static QName BPELBAMSESSIONSCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/PAGWEB_BAM/PAGWEB_BAM/BPEL_BAM_SESSIONS", "bpel_bam_sessions_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagweb/PAGWEB_BAM/bpel_bam_sessions_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FPAGWEB_BAM%2FPAGWEB_BAM%2FBPEL_BAM_SESSIONS%7Dbpel_bam_sessions_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BPELBAMSESSIONSCLIENTEP_WSDL_LOCATION = url;
        BPELBAMSESSIONSCLIENTEP_EXCEPTION = e;
    }

    public BpelBamSessionsClientEp() {
        super(__getWsdlLocation(), BPELBAMSESSIONSCLIENTEP_QNAME);
    }

    public BpelBamSessionsClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BPELBAMSESSIONSCLIENTEP_QNAME, features);
    }

    public BpelBamSessionsClientEp(URL wsdlLocation) {
        super(wsdlLocation, BPELBAMSESSIONSCLIENTEP_QNAME);
    }

    public BpelBamSessionsClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BPELBAMSESSIONSCLIENTEP_QNAME, features);
    }

    public BpelBamSessionsClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BpelBamSessionsClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BPELBAMSESSIONS
     */
    @WebEndpoint(name = "BPEL_BAM_SESSIONS_pt")
    public BPELBAMSESSIONS getBPELBAMSESSIONSPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/PAGWEB_BAM/PAGWEB_BAM/BPEL_BAM_SESSIONS",
                                       "BPEL_BAM_SESSIONS_pt"), BPELBAMSESSIONS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BPELBAMSESSIONS
     */
    @WebEndpoint(name = "BPEL_BAM_SESSIONS_pt")
    public BPELBAMSESSIONS getBPELBAMSESSIONSPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/PAGWEB_BAM/PAGWEB_BAM/BPEL_BAM_SESSIONS",
                                       "BPEL_BAM_SESSIONS_pt"), BPELBAMSESSIONS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BPELBAMSESSIONSCLIENTEP_EXCEPTION != null) {
            throw BPELBAMSESSIONSCLIENTEP_EXCEPTION;
        }
        return BPELBAMSESSIONSCLIENTEP_WSDL_LOCATION;
    }

}
