
package mx.com.sky.sel.proxyclients.pagweb.bamsessions;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagweb.bamsessions.types.ObjectFactory;
import mx.com.sky.sel.proxyclients.pagweb.bamsessions.types.PWBAMSESSIONCollection;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "BPEL_BAM_SESSIONS",
            targetNamespace = "http://xmlns.oracle.com/PAGWEB_BAM/PAGWEB_BAM/BPEL_BAM_SESSIONS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface BPELBAMSESSIONS {


    /**
     *
     * @param payload
     */
    @WebMethod(action = "process")
    @Oneway
    public void process(@WebParam(name = "_PW_BAM_SESSIONCollection", targetNamespace = "http://xmlns.oracle.com/bam",
                                  partName = "payload") PWBAMSESSIONCollection payload);

}
