package mx.com.sky.sel.proxyclients.pagwebss.altasolicitudsw;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class AltaSolicitudDeServicioWebClient {
    public static void main(String[] args) {
        AltaSolicitudDeServicioWeb_Service altaSolicitudDeServicioWeb_Service =
            new AltaSolicitudDeServicioWeb_Service();
        AltaSolicitudDeServicioWeb altaSolicitudDeServicioWeb =
            altaSolicitudDeServicioWeb_Service.getAltaSolicitudDeServicioWeb();
        // Add your code to call the desired methods.


    }
}
