
package mx.com.sky.sel.proxyclients.secinterface.datoscuentacrececombo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseobjects.sec.datoscuentacrececombointerface.DatosCuentaCreceComboRequestEBMType;
import mx.com.sky.enterpriseobjects.sec.datoscuentacrececombointerface.DatosCuentaCreceComboResponseEBMType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "DatosCuentaCreceComboSecInterface",
            targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Sec/DatosCuentaCreceCombo")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ com.oracle.xmlns.pcbpel.adapter.db.sp.dbdatoscuentacrececombosec.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sec.datoscuentacrececombointerface.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.common.v1.ObjectFactory.class,
              org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class,
              org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class
    })
public interface DatosCuentaCreceComboSecInterface {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseobjects.sec.datoscuentacrececombointerface.DatosCuentaCreceComboResponseEBMType
     */
    @WebMethod(action =
               "http://xmlns.sky.com.mx/InterfaceServices/Sec/DatosCuentaCreceCombo/datosCuentaCreceComboSecInterface")
    @WebResult(name = "DatosCuentaCreceComboResponseEBM",
               targetNamespace = "http://www.sky.com.mx/EnterpriseObjects/Sec/DatosCuentaCreceComboInterface",
               partName = "payload")
    public DatosCuentaCreceComboResponseEBMType datosCuentaCreceComboSecInterface(@WebParam(name =
                                                                                            "DatosCuentaCreceComboRequestEBM",
                                                                                            targetNamespace =
                                                                                            "http://www.sky.com.mx/EnterpriseObjects/Sec/DatosCuentaCreceComboInterface",
                                                                                            partName = "payload")
                                                                                  DatosCuentaCreceComboRequestEBMType payload);

}
