
package mx.com.sky.sel.proxyclients.selinterface.consultarregimenfiscalselinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseobjects.sel.consultarregimenfiscal.ConsultarRegimenFiscalRequestType;
import mx.com.sky.enterpriseobjects.sel.consultarregimenfiscal.ConsultarRegimenFiscalResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultarRegimenFiscal",
            targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarRegimenFiscal")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ com.oracle.xmlns.pcbpel.adapter.db.dbunificadoregimenfiscal.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.common.v1.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.consultarregimenfiscal.ObjectFactory.class
    })
public interface ConsultarRegimenFiscal {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseobjects.sel.consultarregimenfiscal.ConsultarRegimenFiscalResponseType
     */
    @WebMethod(action = "http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarRegimenFiscal/process")
    @WebResult(name = "ConsultarRegimenFiscalResponse",
               targetNamespace = "http://www.sky.com.mx/EnterpriseObjects/Sel/ConsultarRegimenFiscal",
               partName = "payload")
    public ConsultarRegimenFiscalResponseType process(@WebParam(name = "ConsultarRegimenFiscalRequest",
                                                                targetNamespace =
                                                                "http://www.sky.com.mx/EnterpriseObjects/Sel/ConsultarRegimenFiscal",
                                                                partName = "payload")
                                                      ConsultarRegimenFiscalRequestType payload);

}
