
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultadatoscs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultadatoscs.types.MensajeInType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultadatoscs.types.MensajeOutType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultadatoscs.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaDatosCS",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaDatosCuentaSuscriptor/ConsultaDatosCS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaDatosCS {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultadatoscs.types.MensajeOutType
     */
    @WebMethod(action = "process")
    @WebResult(name = "mensajeOUT", targetNamespace = "http://www.sky.com.mx.consultadatos", partName = "payload")
    public MensajeOutType process(@WebParam(name = "mensajeIN", targetNamespace = "http://www.sky.com.mx.consultadatos",
                                            partName = "payload") MensajeInType payload);

}
