
package mx.com.sky.sel.proxyclients.pagwebconsultas.primerlogin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebconsultas.primerlogin.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "BPELUpdatePrimerLogin",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaUsers/BPELUpdatePrimerLogin")
@XmlSeeAlso({ ObjectFactory.class })
public interface BPELUpdatePrimerLogin {


    /**
     *
     * @param errordesc
     * @param error
     * @param username
     */
    @WebMethod(action = "process")
    @RequestWrapper(localName = "process",
                    targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaUsers/BPELUpdatePrimerLogin",
                    className = "mx.com.sky.sel.proxyclients.pagwebconsultas.primerlogin.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaUsers/BPELUpdatePrimerLogin",
                     className = "mx.com.sky.sel.proxyclients.pagwebconsultas.primerlogin.types.ProcessResponse")
    public void process(@WebParam(name = "username",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYConsultas/ConsultaUsers/BPELUpdatePrimerLogin")
                        String username,
                        @WebParam(name = "error",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYConsultas/ConsultaUsers/BPELUpdatePrimerLogin",
                                  mode = WebParam.Mode.OUT) Holder<String> error,
                        @WebParam(name = "errordesc",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYConsultas/ConsultaUsers/BPELUpdatePrimerLogin",
                                  mode = WebParam.Mode.OUT) Holder<String> errordesc);

}
