
package mx.com.sky.sel.proxyclients.pagwebconsultas.configgeneral;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagwebconsultas.configgeneral.types.ConsultaConfigProcessRequest;
import mx.com.sky.sel.proxyclients.pagwebconsultas.configgeneral.types.ConsultaConfigProcessResponse;
import mx.com.sky.sel.proxyclients.pagwebconsultas.configgeneral.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "BPELConfigGeneral",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaConfig_General/BPELConfigGeneral")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface BPELConfigGeneral {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.configgeneral.types.ConsultaConfigProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "ConsultaConfigProcessResponse", targetNamespace = "http://xmlns.oracle.com/ConsultaConfig",
               partName = "payload")
    public ConsultaConfigProcessResponse process(@WebParam(name = "ConsultaConfigProcessRequest",
                                                           targetNamespace = "http://xmlns.oracle.com/ConsultaConfig",
                                                           partName = "payload") ConsultaConfigProcessRequest payload);

}
