
package mx.com.sky.sel.proxyclients.selebf.gestionarpagocontdcguardadaselebf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseflowmessages.sel.gestionarpagocontdcguardada.GestionarPagoConTDCGuardadaRequestEBMType;
import mx.com.sky.enterpriseflowmessages.sel.gestionarpagocontdcguardada.GestionarPagoConTDCGuardadaResponseEBMType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "GestionarPagoConTDCGuardadaSelEBF",
            targetNamespace =
            "http://xmlns.sky.com.mx/EnterpriseFlows/Sel/GestionarPagoConTDCGuardada")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ mx.com.sky.enterpriseflowmessages.sel.gestionarpagocontdcguardada.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.common.v1.ObjectFactory.class })
public interface GestionarPagoConTDCGuardadaSelEBF {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseflowmessages.sel.gestionarpagocontdcguardada.GestionarPagoConTDCGuardadaResponseEBMType
     */
    @WebMethod(action =
               "http://xmlns.sky.com.mx/EnterpriseFlows/Sel/GestionarPagoConTDCGuardada/gestionarPagoConTDCGuardada")
    @WebResult(name = "GestionarPagoConTDCGuardadaResponseEBM",
               targetNamespace =
               "http://www.sky.com.mx/EnterpriseFlowMessages/Sel/GestionarPagoConTDCGuardada",
               partName = "payload")
    public GestionarPagoConTDCGuardadaResponseEBMType gestionarPagoConTDCGuardada(@WebParam(name =
                                                                                            "GestionarPagoConTDCGuardadaRequestEBM",
                                                                                            targetNamespace =
                                                                                            "http://www.sky.com.mx/EnterpriseFlowMessages/Sel/GestionarPagoConTDCGuardada",
                                                                                            partName =
                                                                                            "payload")
                                                                                  GestionarPagoConTDCGuardadaRequestEBMType payload);

}
