
package mx.com.sky.sel.proxyclients.pagweb.admintarjetapago;

import java.math.BigDecimal;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagweb.admintarjetapago.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "BPELAdministraTarjetasPago",
            targetNamespace = "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago")
@XmlSeeAlso({ ObjectFactory.class })
public interface BPELAdministraTarjetasPago {


    /**
     *
     * @param ccName
     * @param userId
     * @param orgId
     * @param ccCd
     * @param ccType
     * @param expMonth
     * @param ccNumber
     * @param tarjetas
     * @param tipoConsulta
     * @param expYear
     * @param id
     * @param respuesta
     * @param respuestadesc
     */
    @WebMethod(action = "process")
    @RequestWrapper(localName = "process",
                    targetNamespace =
                    "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago",
                    className = "mx.com.sky.sel.proxyclients.pagweb.admintarjetapago.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago",
                     className = "mx.com.sky.sel.proxyclients.pagweb.admintarjetapago.types.ProcessResponse")
    public void process(@WebParam(name = "TipoConsulta",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago")
                        String tipoConsulta,
                        @WebParam(name = "id",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago")
                        BigDecimal id,
                        @WebParam(name = "ccName",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago")
                        String ccName,
                        @WebParam(name = "ccNumber",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago")
                        String ccNumber,
                        @WebParam(name = "ccType",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago")
                        String ccType,
                        @WebParam(name = "expYear",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago")
                        String expYear,
                        @WebParam(name = "expMonth",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago")
                        String expMonth,
                        @WebParam(name = "userId",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago")
                        String userId,
                        @WebParam(name = "ccCd",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago")
                        String ccCd,
                        @WebParam(name = "OrgId",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago")
                        String orgId,
                        @WebParam(name = "respuesta",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago",
                                  mode = WebParam.Mode.OUT) Holder<String> respuesta,
                        @WebParam(name = "respuestadesc",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago",
                                  mode = WebParam.Mode.OUT) Holder<String> respuestadesc,
                        @WebParam(name = "Tarjetas",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYPortal/AdministraTarjetasPago/BPELAdministraTarjetasPago",
                                  mode = WebParam.Mode.OUT)
                        Holder<List<mx.com.sky.sel.proxyclients.pagweb.admintarjetapago.types.ProcessResponse.Tarjetas>> tarjetas);

}
