package mx.com.sky.sel.proxyclients.selebf.preregistro;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class PreRegistroSelEBF_ptClient {
    public static void main(String[] args) {
        PreRegistroSelEBFEp preRegistroSelEBFEp = new PreRegistroSelEBFEp();
        PreRegistroSelEBF preRegistroSelEBF = preRegistroSelEBFEp.getPreRegistroSelEBFPt();
        // Add your code to call the desired methods.


    }
}
