
package mx.com.sky.sel.proxyclients.selebf.preregistro;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "PreRegistroSelEBF_ep",
                  targetNamespace = "http://xmlns.sky.com.mx/EnterpriseFlows/Sel/PreRegistroSel",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_EBF/PreRegistroSelEBF/PreRegistroSelEBF_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FEnterpriseFlows%2FSel%2FPreRegistroSel%7DPreRegistroSelEBF_ep")
public class PreRegistroSelEBFEp extends Service {

    private final static URL PREREGISTROSELEBFEP_WSDL_LOCATION;
    private final static WebServiceException PREREGISTROSELEBFEP_EXCEPTION;
    private final static QName PREREGISTROSELEBFEP_QNAME =
        new QName("http://xmlns.sky.com.mx/EnterpriseFlows/Sel/PreRegistroSel", "PreRegistroSelEBF_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_EBF/PreRegistroSelEBF/PreRegistroSelEBF_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FEnterpriseFlows%2FSel%2FPreRegistroSel%7DPreRegistroSelEBF_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PREREGISTROSELEBFEP_WSDL_LOCATION = url;
        PREREGISTROSELEBFEP_EXCEPTION = e;
    }

    public PreRegistroSelEBFEp() {
        super(__getWsdlLocation(), PREREGISTROSELEBFEP_QNAME);
    }

    public PreRegistroSelEBFEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), PREREGISTROSELEBFEP_QNAME, features);
    }

    public PreRegistroSelEBFEp(URL wsdlLocation) {
        super(wsdlLocation, PREREGISTROSELEBFEP_QNAME);
    }

    public PreRegistroSelEBFEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PREREGISTROSELEBFEP_QNAME, features);
    }

    public PreRegistroSelEBFEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PreRegistroSelEBFEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PreRegistroSelEBF
     */
    @WebEndpoint(name = "PreRegistroSelEBF_pt")
    public PreRegistroSelEBF getPreRegistroSelEBFPt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/EnterpriseFlows/Sel/PreRegistroSel",
                                       "PreRegistroSelEBF_pt"), PreRegistroSelEBF.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PreRegistroSelEBF
     */
    @WebEndpoint(name = "PreRegistroSelEBF_pt")
    public PreRegistroSelEBF getPreRegistroSelEBFPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/EnterpriseFlows/Sel/PreRegistroSel",
                                       "PreRegistroSelEBF_pt"), PreRegistroSelEBF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PREREGISTROSELEBFEP_EXCEPTION != null) {
            throw PREREGISTROSELEBFEP_EXCEPTION;
        }
        return PREREGISTROSELEBFEP_WSDL_LOCATION;
    }

}
