package mx.com.sky.sel.proxyclients.selinterface.consultaroperadororigenselsecinterface;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1224
public class ConsultarOperadorOrigen_ptClient {
    public static void main(String[] args) {
        ConsultaroperadororigenClientEp consultaroperadororigenClientEp = new ConsultaroperadororigenClientEp();
        ConsultarOperadorOrigen consultarOperadorOrigen =
            consultaroperadororigenClientEp.getConsultarOperadorOrigenPt();
        // Add your code to call the desired methods.


    }
}
