package mx.com.sky.sel.proxyclients.soainterface.consultasaldoscorrientesnew;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaSaldosCorrientesSoaInterface_ptClient {
    public static void main(String[] args) {
        ConsultaSaldosCorrientesSoaInterfaceEp consultaSaldosCorrientesSoaInterfaceEp =
            new ConsultaSaldosCorrientesSoaInterfaceEp();
        ConsultaSaldosCorrientesSoaInterface consultaSaldosCorrientesSoaInterface =
            consultaSaldosCorrientesSoaInterfaceEp.getConsultaSaldosCorrientesSoaInterfacePt();
        // Add your code to call the desired methods.


    }
}
