package mx.com.sky.sel.proxyclients.selebf.reenviaremailprereg;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ReEnviarEmailPreRegSelEBF_ptClient {
    public static void main(String[] args) {
        ReEnviarEmailPreRegSelEBFEp reEnviarEmailPreRegSelEBFEp = new ReEnviarEmailPreRegSelEBFEp();
        ReEnviarEmailPreRegSelEBF reEnviarEmailPreRegSelEBF =
            reEnviarEmailPreRegSelEBFEp.getReEnviarEmailPreRegSelEBFPt();
        // Add your code to call the desired methods.


    }
}
