
package mx.com.sky.sel.proxyclients.btgew.upgradepaquete;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.btgew.upgradepaquete.types.BtgewUpgradePaqueteInType;
import mx.com.sky.sel.proxyclients.btgew.upgradepaquete.types.BtgewUpgradePaqueteOutType;
import mx.com.sky.sel.proxyclients.btgew.upgradepaquete.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "BTGEW_UpgradePaquete",
            targetNamespace = "http://xmlns.oracle.com/SKY_BTGEW/UpgradePaquete/BTGEW_UpgradePaquete")
@XmlSeeAlso({ ObjectFactory.class })
public interface BTGEWUpgradePaquete {


    /**
     *
     * @param input
     * @return
     *     returns mx.com.sky.sel.proxyclients.btgew.upgradepaquete.types.BtgewUpgradePaqueteOutType
     */
    @WebMethod(action = "process")
    @WebResult(name = "result",
               targetNamespace = "http://xmlns.oracle.com/SKY_BTGEW/UpgradePaquete/BTGEW_UpgradePaquete")
    @RequestWrapper(localName = "process",
                    targetNamespace = "http://xmlns.oracle.com/SKY_BTGEW/UpgradePaquete/BTGEW_UpgradePaquete",
                    className = "mx.com.sky.sel.proxyclients.btgew.upgradepaquete.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace = "http://xmlns.oracle.com/SKY_BTGEW/UpgradePaquete/BTGEW_UpgradePaquete",
                     className = "mx.com.sky.sel.proxyclients.btgew.upgradepaquete.types.ProcessResponse")
    public BtgewUpgradePaqueteOutType process(@WebParam(name = "input",
                                                        targetNamespace =
                                                        "http://xmlns.oracle.com/SKY_BTGEW/UpgradePaquete/BTGEW_UpgradePaquete")
                                              BtgewUpgradePaqueteInType input);

}
