
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultaactdatosusuario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultaactdatosusuario.types.ConsultaADUInType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultaactdatosusuario.types.ConsultaADUOutType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultaactdatosusuario.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaActualizaDatosUsuario",
            targetNamespace =
            "http://xmlns.oracle.com/SKYConsultas/ConsultaActualizaDatosUsuario/ConsultaActualizaDatosUsuario")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaActualizaDatosUsuario {


    /**
     *
     * @param request
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultaactdatosusuario.types.ConsultaADUOutType
     */
    @WebMethod(action = "process")
    @WebResult(name = "result",
               targetNamespace =
               "http://xmlns.oracle.com/SKYConsultas/ConsultaActualizaDatosUsuario/ConsultaActualizaDatosUsuario")
    @RequestWrapper(localName = "process",
                    targetNamespace =
                    "http://xmlns.oracle.com/SKYConsultas/ConsultaActualizaDatosUsuario/ConsultaActualizaDatosUsuario",
                    className = "mx.com.sky.sel.proxyclients.pagwebconsultas.consultaactdatosusuario.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/SKYConsultas/ConsultaActualizaDatosUsuario/ConsultaActualizaDatosUsuario",
                     className =
                     "mx.com.sky.sel.proxyclients.pagwebconsultas.consultaactdatosusuario.types.ProcessResponse")
    public ConsultaADUOutType process(@WebParam(name = "request",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKYConsultas/ConsultaActualizaDatosUsuario/ConsultaActualizaDatosUsuario")
                                      ConsultaADUInType request);

}
