
package mx.com.sky.sel.proxyclients.secinterface.ventacrecimientoscombo;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "VentaCrecimientosComboSecInterface_ep",
                  targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Sec/VentaCrecimientosCombo",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/SEC_Interface/VentaCrecimientosComboSecInterface/VentaCrecimientosComboSecInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSec%2FVentaCrecimientosCombo%7DVentaCrecimientosComboSecInterface_ep")
public class VentaCrecimientosComboSecInterfaceEp extends Service {

    private final static URL VENTACRECIMIENTOSCOMBOSECINTERFACEEP_WSDL_LOCATION;
    private final static WebServiceException VENTACRECIMIENTOSCOMBOSECINTERFACEEP_EXCEPTION;
    private final static QName VENTACRECIMIENTOSCOMBOSECINTERFACEEP_QNAME =
        new QName("http://xmlns.sky.com.mx/InterfaceServices/Sec/VentaCrecimientosCombo",
                  "VentaCrecimientosComboSecInterface_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/SEC_Interface/VentaCrecimientosComboSecInterface/VentaCrecimientosComboSecInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSec%2FVentaCrecimientosCombo%7DVentaCrecimientosComboSecInterface_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VENTACRECIMIENTOSCOMBOSECINTERFACEEP_WSDL_LOCATION = url;
        VENTACRECIMIENTOSCOMBOSECINTERFACEEP_EXCEPTION = e;
    }

    public VentaCrecimientosComboSecInterfaceEp() {
        super(__getWsdlLocation(), VENTACRECIMIENTOSCOMBOSECINTERFACEEP_QNAME);
    }

    public VentaCrecimientosComboSecInterfaceEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), VENTACRECIMIENTOSCOMBOSECINTERFACEEP_QNAME, features);
    }

    public VentaCrecimientosComboSecInterfaceEp(URL wsdlLocation) {
        super(wsdlLocation, VENTACRECIMIENTOSCOMBOSECINTERFACEEP_QNAME);
    }

    public VentaCrecimientosComboSecInterfaceEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VENTACRECIMIENTOSCOMBOSECINTERFACEEP_QNAME, features);
    }

    public VentaCrecimientosComboSecInterfaceEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VentaCrecimientosComboSecInterfaceEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns VentaCrecimientosComboSecInterface
     */
    @WebEndpoint(name = "VentaCrecimientosComboSecInterface_pt")
    public VentaCrecimientosComboSecInterface getVentaCrecimientosComboSecInterfacePt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Sec/VentaCrecimientosCombo",
                                       "VentaCrecimientosComboSecInterface_pt"),
                             VentaCrecimientosComboSecInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VentaCrecimientosComboSecInterface
     */
    @WebEndpoint(name = "VentaCrecimientosComboSecInterface_pt")
    public VentaCrecimientosComboSecInterface getVentaCrecimientosComboSecInterfacePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Sec/VentaCrecimientosCombo",
                                       "VentaCrecimientosComboSecInterface_pt"),
                             VentaCrecimientosComboSecInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VENTACRECIMIENTOSCOMBOSECINTERFACEEP_EXCEPTION != null) {
            throw VENTACRECIMIENTOSCOMBOSECINTERFACEEP_EXCEPTION;
        }
        return VENTACRECIMIENTOSCOMBOSECINTERFACEEP_WSDL_LOCATION;
    }

}
