
package mx.com.sky.sel.proxyclients.pagweb.borracargaom;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "BorraCargaOM", targetNamespace = "http://xmlns.oracle.com/BorraCargaOM",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagweb/BorraCargaOM/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FBorraCargaOM%7DBorraCargaOM")
public class BorraCargaOM_Service extends Service {

    private final static URL BORRACARGAOM_WSDL_LOCATION;
    private final static WebServiceException BORRACARGAOM_EXCEPTION;
    private final static QName BORRACARGAOM_QNAME = new QName("http://xmlns.oracle.com/BorraCargaOM", "BorraCargaOM");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagweb/BorraCargaOM/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FBorraCargaOM%7DBorraCargaOM");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BORRACARGAOM_WSDL_LOCATION = url;
        BORRACARGAOM_EXCEPTION = e;
    }

    public BorraCargaOM_Service() {
        super(__getWsdlLocation(), BORRACARGAOM_QNAME);
    }

    public BorraCargaOM_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BORRACARGAOM_QNAME, features);
    }

    public BorraCargaOM_Service(URL wsdlLocation) {
        super(wsdlLocation, BORRACARGAOM_QNAME);
    }

    public BorraCargaOM_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BORRACARGAOM_QNAME, features);
    }

    public BorraCargaOM_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BorraCargaOM_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BorraCargaOM
     */
    @WebEndpoint(name = "BorraCargaOM")
    public BorraCargaOM getBorraCargaOM() {
        return super.getPort(new QName("http://xmlns.oracle.com/BorraCargaOM", "BorraCargaOM"), BorraCargaOM.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BorraCargaOM
     */
    @WebEndpoint(name = "BorraCargaOM")
    public BorraCargaOM getBorraCargaOM(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/BorraCargaOM", "BorraCargaOM"), BorraCargaOM.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (BORRACARGAOM_EXCEPTION != null) {
            throw BORRACARGAOM_EXCEPTION;
        }
        return BORRACARGAOM_WSDL_LOCATION;
    }

}
