package mx.com.sky.sel.proxyclients.pwconsultas.pwconsultainformacionfiscal;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaInformacionFiscal_ptClient {
    public static void main(String[] args) {
        ConsultainformacionfiscalClientEp consultainformacionfiscalClientEp = new ConsultainformacionfiscalClientEp();
        ConsultaInformacionFiscal consultaInformacionFiscal =
            consultainformacionfiscalClientEp.getConsultaInformacionFiscalPt();
        // Add your code to call the desired methods.


    }
}
