
package mx.com.sky.sel.proxyclients.pwconsultas.pwconsultainformacionfiscal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import com.oracle.xmlns.consultas.pwconsultainformacionfiscal.consultainformacionfiscal.ObjectFactory;
import com.oracle.xmlns.consultas.pwconsultainformacionfiscal.consultainformacionfiscal.Proceso;
import com.oracle.xmlns.consultas.pwconsultainformacionfiscal.consultainformacionfiscal.RespuestaProceso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaInformacionFiscal",
            targetNamespace = "http://xmlns.oracle.com/Consultas/PWConsultaInformacionFiscal/ConsultaInformacionFiscal")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaInformacionFiscal {


    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.consultas.pwconsultainformacionfiscal.consultainformacionfiscal.RespuestaProceso
     */
    @WebMethod(action = "process")
    @WebResult(name = "respuestaProceso",
               targetNamespace =
               "http://xmlns.oracle.com/Consultas/PWConsultaInformacionFiscal/ConsultaInformacionFiscal",
               partName = "payload")
    public RespuestaProceso process(@WebParam(name = "proceso",
                                              targetNamespace =
                                              "http://xmlns.oracle.com/Consultas/PWConsultaInformacionFiscal/ConsultaInformacionFiscal",
                                              partName = "payload") Proceso payload);

}
