package mx.com.sky.sel.proxyclients.pagweb.pwbamoperaciones;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class BPEL_PW_BAM_OPERACIONES_ptClient {
    public static void main(String[] args) {
        BpelPwBamOperacionesClientEp bpelPwBamOperacionesClientEp = new BpelPwBamOperacionesClientEp();
        BPELPWBAMOPERACIONES bPELPWBAMOPERACIONES = bpelPwBamOperacionesClientEp.getBPELPWBAMOPERACIONESPt();
        // Add your code to call the desired methods.


    }
}
