
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultarecargasvetv;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultarecargasvetv.types.ObjectFactory;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultarecargasvetv.types.RecargasVeTVOutput;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaRecargasVeTV",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaFormasPago/ConsultaRecargasVeTV")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaRecargasVeTV {


    /**
     *
     * @param cuentaSKY
     * @param resultado
     * @param resultadodesc
     * @param recargasVeTV
     */
    @WebMethod(action = "process")
    @RequestWrapper(localName = "process",
                    targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaFormasPago/ConsultaRecargasVeTV",
                    className = "mx.com.sky.sel.proxyclients.pagwebconsultas.consultarecargasvetv.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaFormasPago/ConsultaRecargasVeTV",
                     className =
                     "mx.com.sky.sel.proxyclients.pagwebconsultas.consultarecargasvetv.types.ProcessResponse")
    public void process(@WebParam(name = "CuentaSKY",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYConsultas/ConsultaFormasPago/ConsultaRecargasVeTV")
                        String cuentaSKY,
                        @WebParam(name = "resultado",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYConsultas/ConsultaFormasPago/ConsultaRecargasVeTV",
                                  mode = WebParam.Mode.OUT) Holder<String> resultado,
                        @WebParam(name = "resultadodesc",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYConsultas/ConsultaFormasPago/ConsultaRecargasVeTV",
                                  mode = WebParam.Mode.OUT) Holder<String> resultadodesc,
                        @WebParam(name = "recargasVeTV",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYConsultas/ConsultaFormasPago/ConsultaRecargasVeTV",
                                  mode = WebParam.Mode.OUT) Holder<List<RecargasVeTVOutput>> recargasVeTV);

}
