
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultarecargasvetv;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "consultarecargasvetv_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaFormasPago/ConsultaRecargasVeTV",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaFormasPago/consultarecargasvetv_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKYConsultas%2FConsultaFormasPago%2FConsultaRecargasVeTV%7Dconsultarecargasvetv_client_ep")
public class ConsultarecargasvetvClientEp extends Service {

    private final static URL CONSULTARECARGASVETVCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTARECARGASVETVCLIENTEP_EXCEPTION;
    private final static QName CONSULTARECARGASVETVCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaFormasPago/ConsultaRecargasVeTV",
                  "consultarecargasvetv_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaFormasPago/consultarecargasvetv_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKYConsultas%2FConsultaFormasPago%2FConsultaRecargasVeTV%7Dconsultarecargasvetv_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARECARGASVETVCLIENTEP_WSDL_LOCATION = url;
        CONSULTARECARGASVETVCLIENTEP_EXCEPTION = e;
    }

    public ConsultarecargasvetvClientEp() {
        super(__getWsdlLocation(), CONSULTARECARGASVETVCLIENTEP_QNAME);
    }

    public ConsultarecargasvetvClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARECARGASVETVCLIENTEP_QNAME, features);
    }

    public ConsultarecargasvetvClientEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARECARGASVETVCLIENTEP_QNAME);
    }

    public ConsultarecargasvetvClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARECARGASVETVCLIENTEP_QNAME, features);
    }

    public ConsultarecargasvetvClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarecargasvetvClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaRecargasVeTV
     */
    @WebEndpoint(name = "ConsultaRecargasVeTV_pt")
    public ConsultaRecargasVeTV getConsultaRecargasVeTVPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaFormasPago/ConsultaRecargasVeTV",
                                       "ConsultaRecargasVeTV_pt"), ConsultaRecargasVeTV.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaRecargasVeTV
     */
    @WebEndpoint(name = "ConsultaRecargasVeTV_pt")
    public ConsultaRecargasVeTV getConsultaRecargasVeTVPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaFormasPago/ConsultaRecargasVeTV",
                                       "ConsultaRecargasVeTV_pt"), ConsultaRecargasVeTV.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARECARGASVETVCLIENTEP_EXCEPTION != null) {
            throw CONSULTARECARGASVETVCLIENTEP_EXCEPTION;
        }
        return CONSULTARECARGASVETVCLIENTEP_WSDL_LOCATION;
    }

}
