
package mx.com.sky.sel.proxyclients.pagweb.admonpromos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagweb.admonpromos.types.AdmonPromocionesProcessRequest;
import mx.com.sky.sel.proxyclients.pagweb.admonpromos.types.AdmonPromocionesProcessResponse;
import mx.com.sky.sel.proxyclients.pagweb.admonpromos.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "AdmonPromociones", targetNamespace = "http://xmlns.oracle.com/AdmonPromociones")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface AdmonPromociones {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagweb.admonpromos.types.AdmonPromocionesProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "AdmonPromocionesProcessResponse", targetNamespace = "http://xmlns.oracle.com/AdmonPromociones",
               partName = "payload")
    public AdmonPromocionesProcessResponse process(@WebParam(name = "AdmonPromocionesProcessRequest",
                                                             targetNamespace =
                                                             "http://xmlns.oracle.com/AdmonPromociones",
                                                             partName = "payload")
                                                   AdmonPromocionesProcessRequest payload);

}
