
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultadatosgenerales;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultadatosgenerales.types.ConsultaDatosGeneralesIn;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultadatosgenerales.types.ConsultaDatosGeneralesOut;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultadatosgenerales.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaDatosGenerales",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaDatosGenerales/ConsultaDatosGenerales")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaDatosGenerales {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultadatosgenerales.types.ConsultaDatosGeneralesOut
     */
    @WebMethod(action = "process")
    @WebResult(name = "ConsultaDatosGeneralesOut", targetNamespace = "http://xmlns.oracle.com/ConsultaDatosGenerales",
               partName = "payload")
    public ConsultaDatosGeneralesOut process(@WebParam(name = "ConsultaDatosGeneralesIn",
                                                       targetNamespace =
                                                       "http://xmlns.oracle.com/ConsultaDatosGenerales",
                                                       partName = "payload") ConsultaDatosGeneralesIn payload);

}
