
package mx.com.sky.sel.proxyclients.secinterface.consultarcapacidadfs;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultarCapacidadFSSecInterface_ep",
                  targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Sec/ConsultarCapacidadFS",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/SEC_Interface/ConsultarCapacidadFSSecInterface/ConsultarCapacidadFSSecInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSec%2FConsultarCapacidadFS%7DConsultarCapacidadFSSecInterface_ep")
public class ConsultarCapacidadFSSecInterfaceEp extends Service {

    private final static URL CONSULTARCAPACIDADFSSECINTERFACEEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTARCAPACIDADFSSECINTERFACEEP_EXCEPTION;
    private final static QName CONSULTARCAPACIDADFSSECINTERFACEEP_QNAME =
        new QName("http://xmlns.sky.com.mx/InterfaceServices/Sec/ConsultarCapacidadFS",
                  "ConsultarCapacidadFSSecInterface_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/SEC_Interface/ConsultarCapacidadFSSecInterface/ConsultarCapacidadFSSecInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSec%2FConsultarCapacidadFS%7DConsultarCapacidadFSSecInterface_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARCAPACIDADFSSECINTERFACEEP_WSDL_LOCATION = url;
        CONSULTARCAPACIDADFSSECINTERFACEEP_EXCEPTION = e;
    }

    public ConsultarCapacidadFSSecInterfaceEp() {
        super(__getWsdlLocation(), CONSULTARCAPACIDADFSSECINTERFACEEP_QNAME);
    }

    public ConsultarCapacidadFSSecInterfaceEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARCAPACIDADFSSECINTERFACEEP_QNAME, features);
    }

    public ConsultarCapacidadFSSecInterfaceEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARCAPACIDADFSSECINTERFACEEP_QNAME);
    }

    public ConsultarCapacidadFSSecInterfaceEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARCAPACIDADFSSECINTERFACEEP_QNAME, features);
    }

    public ConsultarCapacidadFSSecInterfaceEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarCapacidadFSSecInterfaceEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultarCapacidadFSSecInterface
     */
    @WebEndpoint(name = "ConsultarCapacidadFSSecInterface_pt")
    public ConsultarCapacidadFSSecInterface getConsultarCapacidadFSSecInterfacePt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Sec/ConsultarCapacidadFS",
                                       "ConsultarCapacidadFSSecInterface_pt"), ConsultarCapacidadFSSecInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarCapacidadFSSecInterface
     */
    @WebEndpoint(name = "ConsultarCapacidadFSSecInterface_pt")
    public ConsultarCapacidadFSSecInterface getConsultarCapacidadFSSecInterfacePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Sec/ConsultarCapacidadFS",
                                       "ConsultarCapacidadFSSecInterface_pt"), ConsultarCapacidadFSSecInterface.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARCAPACIDADFSSECINTERFACEEP_EXCEPTION != null) {
            throw CONSULTARCAPACIDADFSSECINTERFACEEP_EXCEPTION;
        }
        return CONSULTARCAPACIDADFSSECINTERFACEEP_WSDL_LOCATION;
    }

}
