
package mx.com.sky.sel.proxyclients.secinterface.consultarcapacidadfs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseobjects.sec.consultarcapacidadfsinterface.ConsultarCapacidadFSRequestEBMType;
import mx.com.sky.enterpriseobjects.sec.consultarcapacidadfsinterface.ConsultarCapacidadFSResponseEBMType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultarCapacidadFSSecInterface",
            targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Sec/ConsultarCapacidadFS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ mx.com.sky.enterpriseobjects.sec.common.v1.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sec.consultarcapacidadfsebo.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sec.consultarcapacidadfsinterface.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.common.v1.ObjectFactory.class,
              org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class,
              org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class
    })
public interface ConsultarCapacidadFSSecInterface {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseobjects.sec.consultarcapacidadfsinterface.ConsultarCapacidadFSResponseEBMType
     */
    @WebMethod(action =
               "http://xmlns.sky.com.mx/InterfaceServices/Sec/ConsultarCapacidadFS/consultarCapacidadFSSecInterface")
    @WebResult(name = "ConsultarCapacidadFSResponseEBM",
               targetNamespace = "http://www.sky.com.mx/EnterpriseObjects/Sec/ConsultarCapacidadFSInterface",
               partName = "payload")
    public ConsultarCapacidadFSResponseEBMType consultarCapacidadFSSecInterface(@WebParam(name =
                                                                                          "ConsultarCapacidadFSRequestEBM",
                                                                                          targetNamespace =
                                                                                          "http://www.sky.com.mx/EnterpriseObjects/Sec/ConsultarCapacidadFSInterface",
                                                                                          partName = "payload")
                                                                                ConsultarCapacidadFSRequestEBMType payload);

}
