
package mx.com.sky.sel.proxyclients.btgew.activacion;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "btgew_activacion_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/SKY_BTGEW/Activacion/BTGEW_Activacion",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/btgew/Activacion/btgew_activacion_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKY_BTGEW%2FActivacion%2FBTGEW_Activacion%7Dbtgew_activacion_client_ep")
public class BtgewActivacionClientEp extends Service {

    private final static URL BTGEWACTIVACIONCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException BTGEWACTIVACIONCLIENTEP_EXCEPTION;
    private final static QName BTGEWACTIVACIONCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/SKY_BTGEW/Activacion/BTGEW_Activacion", "btgew_activacion_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/btgew/Activacion/btgew_activacion_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKY_BTGEW%2FActivacion%2FBTGEW_Activacion%7Dbtgew_activacion_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BTGEWACTIVACIONCLIENTEP_WSDL_LOCATION = url;
        BTGEWACTIVACIONCLIENTEP_EXCEPTION = e;
    }

    public BtgewActivacionClientEp() {
        super(__getWsdlLocation(), BTGEWACTIVACIONCLIENTEP_QNAME);
    }

    public BtgewActivacionClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), BTGEWACTIVACIONCLIENTEP_QNAME, features);
    }

    public BtgewActivacionClientEp(URL wsdlLocation) {
        super(wsdlLocation, BTGEWACTIVACIONCLIENTEP_QNAME);
    }

    public BtgewActivacionClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BTGEWACTIVACIONCLIENTEP_QNAME, features);
    }

    public BtgewActivacionClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BtgewActivacionClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BTGEWActivacion
     */
    @WebEndpoint(name = "BTGEW_Activacion_pt")
    public BTGEWActivacion getBTGEWActivacionPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/SKY_BTGEW/Activacion/BTGEW_Activacion",
                                       "BTGEW_Activacion_pt"), BTGEWActivacion.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BTGEWActivacion
     */
    @WebEndpoint(name = "BTGEW_Activacion_pt")
    public BTGEWActivacion getBTGEWActivacionPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/SKY_BTGEW/Activacion/BTGEW_Activacion",
                                       "BTGEW_Activacion_pt"), BTGEWActivacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BTGEWACTIVACIONCLIENTEP_EXCEPTION != null) {
            throw BTGEWACTIVACIONCLIENTEP_EXCEPTION;
        }
        return BTGEWACTIVACIONCLIENTEP_WSDL_LOCATION;
    }

}
