
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultamodulos;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaModulos", targetNamespace = "http://xmlns.oracle.com/ConsultaModulos",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaModulos/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaModulos%7DConsultaModulos")
public class ConsultaModulos_Service extends Service {

    private final static URL CONSULTAMODULOS_WSDL_LOCATION;
    private final static WebServiceException CONSULTAMODULOS_EXCEPTION;
    private final static QName CONSULTAMODULOS_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaModulos", "ConsultaModulos");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaModulos/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaModulos%7DConsultaModulos");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAMODULOS_WSDL_LOCATION = url;
        CONSULTAMODULOS_EXCEPTION = e;
    }

    public ConsultaModulos_Service() {
        super(__getWsdlLocation(), CONSULTAMODULOS_QNAME);
    }

    public ConsultaModulos_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAMODULOS_QNAME, features);
    }

    public ConsultaModulos_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAMODULOS_QNAME);
    }

    public ConsultaModulos_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAMODULOS_QNAME, features);
    }

    public ConsultaModulos_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaModulos_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaModulos
     */
    @WebEndpoint(name = "ConsultaModulos")
    public ConsultaModulos getConsultaModulos() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaModulos", "ConsultaModulos"),
                             ConsultaModulos.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaModulos
     */
    @WebEndpoint(name = "ConsultaModulos")
    public ConsultaModulos getConsultaModulos(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaModulos", "ConsultaModulos"),
                             ConsultaModulos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAMODULOS_EXCEPTION != null) {
            throw CONSULTAMODULOS_EXCEPTION;
        }
        return CONSULTAMODULOS_WSDL_LOCATION;
    }

}
