
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultatmpbtgew;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultatmpbtgew.types.ObjectFactory;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultatmpbtgew.types.TmpBTGEWINType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultatmpbtgew.types.TmpBTGEWOUTType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaTMP_BTGEW",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaTMPBlueToGoEveryWhere/ConsultaTMP_BTGEW")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaTMPBTGEW {


    /**
     *
     * @param input
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultatmpbtgew.types.TmpBTGEWOUTType
     */
    @WebMethod(action = "process")
    @WebResult(name = "result",
               targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaTMPBlueToGoEveryWhere/ConsultaTMP_BTGEW")
    @RequestWrapper(localName = "process",
                    targetNamespace =
                    "http://xmlns.oracle.com/SKYConsultas/ConsultaTMPBlueToGoEveryWhere/ConsultaTMP_BTGEW",
                    className = "mx.com.sky.sel.proxyclients.pagwebconsultas.consultatmpbtgew.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/SKYConsultas/ConsultaTMPBlueToGoEveryWhere/ConsultaTMP_BTGEW",
                     className = "mx.com.sky.sel.proxyclients.pagwebconsultas.consultatmpbtgew.types.ProcessResponse")
    public TmpBTGEWOUTType process(@WebParam(name = "input",
                                             targetNamespace =
                                             "http://xmlns.oracle.com/SKYConsultas/ConsultaTMPBlueToGoEveryWhere/ConsultaTMP_BTGEW")
                                   TmpBTGEWINType input);

}
