package mx.com.sky.sel.proxyclients.pagwebconsultas.consultainformacionfiscal;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaInformacionFiscalClient {
    public static void main(String[] args) {
        ConsultaInformacionFiscal_Service consultaInformacionFiscal_Service = new ConsultaInformacionFiscal_Service();
        ConsultaInformacionFiscal consultaInformacionFiscal =
            consultaInformacionFiscal_Service.getConsultaInformacionFiscal();
        // Add your code to call the desired methods.


    }
}
