
package mx.com.sky.sel.proxyclients.pagweb.reenviosenal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagweb.reenviosenal.types.ObjectFactory;
import mx.com.sky.sel.proxyclients.pagweb.reenviosenal.types.ReenvioDeSenalProcessRequest;
import mx.com.sky.sel.proxyclients.pagweb.reenviosenal.types.ReenvioDeSenalProcessResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "BPEL_ReenvioSenal",
            targetNamespace = "http://xmlns.oracle.com/SKYPortal/ReenvioSenal/BPEL_ReenvioSenal")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface BPELReenvioSenal {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagweb.reenviosenal.types.ReenvioDeSenalProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "ReenvioDeSenalProcessResponse", targetNamespace = "http://xmlns.oracle.com/ReenvioSenal",
               partName = "payload")
    public ReenvioDeSenalProcessResponse process(@WebParam(name = "ReenvioDeSenalProcessRequest",
                                                           targetNamespace = "http://xmlns.oracle.com/ReenvioSenal",
                                                           partName = "payload") ReenvioDeSenalProcessRequest payload);

}
