package mx.com.sky.sel.proxyclients.pagwebconsultas.consultappv;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaPPVClient {
    public static void main(String[] args) {
        ConsultaPPV_Service consultaPPV_Service = new ConsultaPPV_Service();
        ConsultaPPV consultaPPV = consultaPPV_Service.getConsultaPPV();
        // Add your code to call the desired methods.


    }
}
