package mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="https://preselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/ConsultaEstadoDeCuentaSoaInterface/ConsultaEstadoDeCuentaSoaInterface_ep?WSDL",
  targetNamespace="http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaEstadoDeCuenta",
  name="ConsultaEstadoDeCuentaSoaInterface")
@XmlSeeAlso(
  { mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta.types.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface ConsultaEstadoDeCuentaSoaInterface
{
  @WebMethod(action="http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaEstadoDeCuenta/consultaEstadoDeCuenta")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaEstadoDeCuenta/consultaEstadoDeCuenta",
    output="http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaEstadoDeCuenta/ConsultaEstadoDeCuentaSoaInterface/consultaEstadoDeCuentaResponse")
  @WebResult(targetNamespace="http://www.sky.com.mx/EnterpriseObjects/Soa/ConsultaEstadoDeCuentaInterface",
    partName="payload", name="ConsultaEstadoDeCuentaResponseEBM")
  public mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta.types.ConsultaEstadoDeCuentaResponseEBMType consultaEstadoDeCuenta(@WebParam(targetNamespace="http://www.sky.com.mx/EnterpriseObjects/Soa/ConsultaEstadoDeCuentaInterface",
      partName="payload", name="ConsultaEstadoDeCuentaEBM")
    mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta.types.ConsultaEstadoDeCuentaEBMType payload);
}
