package mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="https://qaselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/ConsultaEstadoDeCuentaSoaInterface/ConsultaEstadoDeCuentaSoaInterface_ep?WSDL",
  targetNamespace="http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaEstadoDeCuenta",
  name="ConsultaEstadoDeCuentaSoaInterface_ep")
public class ConsultaEstadoDeCuentaSoaInterface_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta.ConsultaEstadoDeCuentaSoaInterface_ep");
      URL baseUrl =
        ConsultaEstadoDeCuentaSoaInterface_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ConsultaEstadoDeCuentaSoaInterface_ep.class.getResource("https://qaselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/ConsultaEstadoDeCuentaSoaInterface/ConsultaEstadoDeCuentaSoaInterface_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "https://qaselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/ConsultaEstadoDeCuentaSoaInterface/ConsultaEstadoDeCuentaSoaInterface_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "https://qaselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/ConsultaEstadoDeCuentaSoaInterface/ConsultaEstadoDeCuentaSoaInterface_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using https://qaselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/ConsultaEstadoDeCuentaSoaInterface/ConsultaEstadoDeCuentaSoaInterface_ep?WSDL",
          e);
    }
  }

  public ConsultaEstadoDeCuentaSoaInterface_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaEstadoDeCuenta",
                    "ConsultaEstadoDeCuentaSoaInterface_ep"));
  }

  public ConsultaEstadoDeCuentaSoaInterface_ep(URL wsdlLocation,
                                               QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ConsultaEstadoDeCuentaSoaInterface_pt")
  public mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta.ConsultaEstadoDeCuentaSoaInterface getConsultaEstadoDeCuentaSoaInterface_pt()
  {
    return (mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta.ConsultaEstadoDeCuentaSoaInterface) super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaEstadoDeCuenta",
                                                                                                                                      "ConsultaEstadoDeCuentaSoaInterface_pt"),
                                                                                                                            mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta.ConsultaEstadoDeCuentaSoaInterface.class);
  }

  @WebEndpoint(name="ConsultaEstadoDeCuentaSoaInterface_pt")
  public mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta.ConsultaEstadoDeCuentaSoaInterface getConsultaEstadoDeCuentaSoaInterface_pt(WebServiceFeature... features)
  {
    return (mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta.ConsultaEstadoDeCuentaSoaInterface) super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaEstadoDeCuenta",
                                                                                                                                      "ConsultaEstadoDeCuentaSoaInterface_pt"),
                                                                                                                            mx.com.sky.sel.proxyclients.soainterface.consultaestadocuenta.ConsultaEstadoDeCuentaSoaInterface.class,
                                                                                                                            features);
  }
}
