
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultadireccionservicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultadireccionservicio.types.ConsultaDireccionDeServicioProcessRequest;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultadireccionservicio.types.ConsultaDireccionDeServicioProcessResponse;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultadireccionservicio.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaDireccionDeServicio",
            targetNamespace = "http://xmlns.oracle.com/ConsultaDireccionDeServicio")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaDireccionDeServicio {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultadireccionservicio.types.ConsultaDireccionDeServicioProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "ConsultaDireccionDeServicioProcessResponse",
               targetNamespace = "http://xmlns.oracle.com/ConsultaDireccionDeServicio", partName = "payload")
    public ConsultaDireccionDeServicioProcessResponse process(@WebParam(name =
                                                                        "ConsultaDireccionDeServicioProcessRequest",
                                                                        targetNamespace =
                                                                        "http://xmlns.oracle.com/ConsultaDireccionDeServicio",
                                                                        partName = "payload")
                                                              ConsultaDireccionDeServicioProcessRequest payload);

}
