
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultavetvfechasrenta;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultavetvfechasrenta.types.ConsultaVeTVFechasInType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultavetvfechasrenta.types.ConsultaVeTVFechasOutType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultavetvfechasrenta.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaVeTVFechasRenta",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaVeTVFechasRenta/ConsultaVeTVFechasRenta")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaVeTVFechasRenta {


    /**
     *
     * @param input
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultavetvfechasrenta.types.ConsultaVeTVFechasOutType
     */
    @WebMethod(action = "process")
    @WebResult(name = "result",
               targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaVeTVFechasRenta/ConsultaVeTVFechasRenta")
    @RequestWrapper(localName = "process",
                    targetNamespace =
                    "http://xmlns.oracle.com/SKYConsultas/ConsultaVeTVFechasRenta/ConsultaVeTVFechasRenta",
                    className = "mx.com.sky.sel.proxyclients.pagwebconsultas.consultavetvfechasrenta.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/SKYConsultas/ConsultaVeTVFechasRenta/ConsultaVeTVFechasRenta",
                     className =
                     "mx.com.sky.sel.proxyclients.pagwebconsultas.consultavetvfechasrenta.types.ProcessResponse")
    public ConsultaVeTVFechasOutType process(@WebParam(name = "input",
                                                       targetNamespace =
                                                       "http://xmlns.oracle.com/SKYConsultas/ConsultaVeTVFechasRenta/ConsultaVeTVFechasRenta")
                                             ConsultaVeTVFechasInType input);

}
