
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultactaespecial;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaCuentaEspecial", targetNamespace = "http://xmlns.oracle.com/ConsultaCuentaEspecial",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaCuentaEspecial/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaCuentaEspecial%7DConsultaCuentaEspecial")
public class ConsultaCuentaEspecial_Service extends Service {

    private final static URL CONSULTACUENTAESPECIAL_WSDL_LOCATION;
    private final static WebServiceException CONSULTACUENTAESPECIAL_EXCEPTION;
    private final static QName CONSULTACUENTAESPECIAL_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaCuentaEspecial", "ConsultaCuentaEspecial");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaCuentaEspecial/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaCuentaEspecial%7DConsultaCuentaEspecial");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTACUENTAESPECIAL_WSDL_LOCATION = url;
        CONSULTACUENTAESPECIAL_EXCEPTION = e;
    }

    public ConsultaCuentaEspecial_Service() {
        super(__getWsdlLocation(), CONSULTACUENTAESPECIAL_QNAME);
    }

    public ConsultaCuentaEspecial_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTACUENTAESPECIAL_QNAME, features);
    }

    public ConsultaCuentaEspecial_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTACUENTAESPECIAL_QNAME);
    }

    public ConsultaCuentaEspecial_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTACUENTAESPECIAL_QNAME, features);
    }

    public ConsultaCuentaEspecial_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaCuentaEspecial_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaCuentaEspecial
     */
    @WebEndpoint(name = "ConsultaCuentaEspecial")
    public ConsultaCuentaEspecial getConsultaCuentaEspecial() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaCuentaEspecial", "ConsultaCuentaEspecial"),
                             ConsultaCuentaEspecial.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaCuentaEspecial
     */
    @WebEndpoint(name = "ConsultaCuentaEspecial")
    public ConsultaCuentaEspecial getConsultaCuentaEspecial(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaCuentaEspecial", "ConsultaCuentaEspecial"),
                             ConsultaCuentaEspecial.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTACUENTAESPECIAL_EXCEPTION != null) {
            throw CONSULTACUENTAESPECIAL_EXCEPTION;
        }
        return CONSULTACUENTAESPECIAL_WSDL_LOCATION;
    }

}
