package mx.com.sky.sel.proxyclients.pagwebconsultas.consultactaespecial;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaCuentaEspecialClient {
    public static void main(String[] args) {
        ConsultaCuentaEspecial_Service consultaCuentaEspecial_Service = new ConsultaCuentaEspecial_Service();
        ConsultaCuentaEspecial consultaCuentaEspecial = consultaCuentaEspecial_Service.getConsultaCuentaEspecial();
        // Add your code to call the desired methods.


    }
}
