package mx.com.sky.sel.proxyclients.pagwebconsultas.consultaticorp;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaTI_CorpClient {
    public static void main(String[] args) {
        ConsultaTICorp_Service consultaTICorp_Service = new ConsultaTICorp_Service();
        ConsultaTICorp consultaTICorp = consultaTICorp_Service.getConsultaTICorp();
        // Add your code to call the desired methods.


    }
}
