
package mx.com.sky.sel.proxyclients.secinterface.validacrecimientosppbti;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ValidaCrecimientosPpBtiSecInterface_ep",
                  targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Sec/ValidaCrecimientosPpBti",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/SEC_Interface/ValidaCrecimientosPpBtiSecInterface/ValidaCrecimientosPpBtiSecInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSec%2FValidaCrecimientosPpBti%7DValidaCrecimientosPpBtiSecInterface_ep")
public class ValidaCrecimientosPpBtiSecInterfaceEp extends Service {

    private final static URL VALIDACRECIMIENTOSPPBTISECINTERFACEEP_WSDL_LOCATION;
    private final static WebServiceException VALIDACRECIMIENTOSPPBTISECINTERFACEEP_EXCEPTION;
    private final static QName VALIDACRECIMIENTOSPPBTISECINTERFACEEP_QNAME =
        new QName("http://xmlns.sky.com.mx/InterfaceServices/Sec/ValidaCrecimientosPpBti",
                  "ValidaCrecimientosPpBtiSecInterface_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/SEC_Interface/ValidaCrecimientosPpBtiSecInterface/ValidaCrecimientosPpBtiSecInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSec%2FValidaCrecimientosPpBti%7DValidaCrecimientosPpBtiSecInterface_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDACRECIMIENTOSPPBTISECINTERFACEEP_WSDL_LOCATION = url;
        VALIDACRECIMIENTOSPPBTISECINTERFACEEP_EXCEPTION = e;
    }

    public ValidaCrecimientosPpBtiSecInterfaceEp() {
        super(__getWsdlLocation(), VALIDACRECIMIENTOSPPBTISECINTERFACEEP_QNAME);
    }

    public ValidaCrecimientosPpBtiSecInterfaceEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDACRECIMIENTOSPPBTISECINTERFACEEP_QNAME, features);
    }

    public ValidaCrecimientosPpBtiSecInterfaceEp(URL wsdlLocation) {
        super(wsdlLocation, VALIDACRECIMIENTOSPPBTISECINTERFACEEP_QNAME);
    }

    public ValidaCrecimientosPpBtiSecInterfaceEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDACRECIMIENTOSPPBTISECINTERFACEEP_QNAME, features);
    }

    public ValidaCrecimientosPpBtiSecInterfaceEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidaCrecimientosPpBtiSecInterfaceEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ValidaCrecimientosPpBtiSecInterface
     */
    @WebEndpoint(name = "ValidaCrecimientosPpBtiSecInterface_pt")
    public ValidaCrecimientosPpBtiSecInterface getValidaCrecimientosPpBtiSecInterfacePt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Sec/ValidaCrecimientosPpBti",
                                       "ValidaCrecimientosPpBtiSecInterface_pt"),
                             ValidaCrecimientosPpBtiSecInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidaCrecimientosPpBtiSecInterface
     */
    @WebEndpoint(name = "ValidaCrecimientosPpBtiSecInterface_pt")
    public ValidaCrecimientosPpBtiSecInterface getValidaCrecimientosPpBtiSecInterfacePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Sec/ValidaCrecimientosPpBti",
                                       "ValidaCrecimientosPpBtiSecInterface_pt"),
                             ValidaCrecimientosPpBtiSecInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDACRECIMIENTOSPPBTISECINTERFACEEP_EXCEPTION != null) {
            throw VALIDACRECIMIENTOSPPBTISECINTERFACEEP_EXCEPTION;
        }
        return VALIDACRECIMIENTOSPPBTISECINTERFACEEP_WSDL_LOCATION;
    }

}
