
package mx.com.sky.sel.proxyclients.secinterface.validacrecimientosppbti;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseobjects.sec.validacrecimientosppbtiinterface.ValidaCrecimientosPpBtiRequestEBMType;
import mx.com.sky.enterpriseobjects.sec.validacrecimientosppbtiinterface.ValidaCrecimientosPpBtiResponseEBMType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ValidaCrecimientosPpBtiSecInterface",
            targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Sec/ValidaCrecimientosPpBti")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ com.oracle.xmlns.pcbpel.adapter.db.sp.dbvalidacrecimientosppbtisec.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sec.validacrecimientosppbtiinterface.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.common.v1.ObjectFactory.class,
              org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class,
              org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class
    })
public interface ValidaCrecimientosPpBtiSecInterface {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseobjects.sec.validacrecimientosppbtiinterface.ValidaCrecimientosPpBtiResponseEBMType
     */
    @WebMethod(action =
               "http://xmlns.sky.com.mx/InterfaceServices/Sec/ValidaCrecimientosPpBti/validaCrecimientosPpBtiSecInterface")
    @WebResult(name = "ValidaCrecimientosPpBtiResponseEBM",
               targetNamespace = "http://www.sky.com.mx/EnterpriseObjects/Sec/ValidaCrecimientosPpBtiInterface",
               partName = "payload")
    public ValidaCrecimientosPpBtiResponseEBMType validaCrecimientosPpBtiSecInterface(@WebParam(name =
                                                                                                "ValidaCrecimientosPpBtiRequestEBM",
                                                                                                targetNamespace =
                                                                                                "http://www.sky.com.mx/EnterpriseObjects/Sec/ValidaCrecimientosPpBtiInterface",
                                                                                                partName = "payload")
                                                                                      ValidaCrecimientosPpBtiRequestEBMType payload);

}
