
package mx.com.sky.sel.proxyclients.pagweb.insertacrecimientostya;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "insertacrecimientos_tya_client_ep",
                  targetNamespace =
                  "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagweb/CrecimientosEquipos/insertacrecimientos_tya_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKY_CrecimientosEquipos%2FSKY_Crecimientos%2FInsertaCrecimientos_TYA%7Dinsertacrecimientos_tya_client_ep")
public class InsertacrecimientosTyaClientEp extends Service {

    private final static URL INSERTACRECIMIENTOSTYACLIENTEP_WSDL_LOCATION;
    private final static WebServiceException INSERTACRECIMIENTOSTYACLIENTEP_EXCEPTION;
    private final static QName INSERTACRECIMIENTOSTYACLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA",
                  "insertacrecimientos_tya_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagweb/CrecimientosEquipos/insertacrecimientos_tya_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKY_CrecimientosEquipos%2FSKY_Crecimientos%2FInsertaCrecimientos_TYA%7Dinsertacrecimientos_tya_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSERTACRECIMIENTOSTYACLIENTEP_WSDL_LOCATION = url;
        INSERTACRECIMIENTOSTYACLIENTEP_EXCEPTION = e;
    }

    public InsertacrecimientosTyaClientEp() {
        super(__getWsdlLocation(), INSERTACRECIMIENTOSTYACLIENTEP_QNAME);
    }

    public InsertacrecimientosTyaClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSERTACRECIMIENTOSTYACLIENTEP_QNAME, features);
    }

    public InsertacrecimientosTyaClientEp(URL wsdlLocation) {
        super(wsdlLocation, INSERTACRECIMIENTOSTYACLIENTEP_QNAME);
    }

    public InsertacrecimientosTyaClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSERTACRECIMIENTOSTYACLIENTEP_QNAME, features);
    }

    public InsertacrecimientosTyaClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsertacrecimientosTyaClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns InsertaCrecimientosTYA
     */
    @WebEndpoint(name = "InsertaCrecimientos_TYA_pt")
    public InsertaCrecimientosTYA getInsertaCrecimientosTYAPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA",
                                       "InsertaCrecimientos_TYA_pt"), InsertaCrecimientosTYA.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsertaCrecimientosTYA
     */
    @WebEndpoint(name = "InsertaCrecimientos_TYA_pt")
    public InsertaCrecimientosTYA getInsertaCrecimientosTYAPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA",
                                       "InsertaCrecimientos_TYA_pt"), InsertaCrecimientosTYA.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSERTACRECIMIENTOSTYACLIENTEP_EXCEPTION != null) {
            throw INSERTACRECIMIENTOSTYACLIENTEP_EXCEPTION;
        }
        return INSERTACRECIMIENTOSTYACLIENTEP_WSDL_LOCATION;
    }

}
