
package mx.com.sky.sel.proxyclients.pagweb.insertacrecimientostya;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagweb.insertacrecimientostya.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "InsertaCrecimientos_TYA",
            targetNamespace =
            "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
@XmlSeeAlso({ ObjectFactory.class })
public interface InsertaCrecimientosTYA {


    /**
     *
     * @param vendedor
     * @param codigoError
     * @param cuentaSKY
     * @param sistema
     * @param descError
     * @param mig
     * @param fechaAtencion
     * @param creceA
     * @param distribuidor
     * @param phd
     * @param equiposActivos
     * @param paquete
     * @param sd
     * @param horaAtencion
     * @param hd
     * @param totalCrec
     * @param sr
     * @param hmc
     */
    @WebMethod(action = "insertaCrecimientosTYA")
    @RequestWrapper(localName = "insertaCrecimientosTYA",
                    targetNamespace =
                    "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA",
                    className =
                    "mx.com.sky.sel.proxyclients.pagweb.insertacrecimientostya.types.InsertaCrecimientosTYA")
    @ResponseWrapper(localName = "insertaCrecimientosTYAResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA",
                     className =
                     "mx.com.sky.sel.proxyclients.pagweb.insertacrecimientostya.types.InsertaCrecimientosTYAResponse")
    public void insertaCrecimientosTYA(@WebParam(name = "cuentaSKY",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String cuentaSKY,
                                       @WebParam(name = "vendedor",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String vendedor,
                                       @WebParam(name = "distribuidor",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String distribuidor,
                                       @WebParam(name = "fechaAtencion",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String fechaAtencion,
                                       @WebParam(name = "horaAtencion",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String horaAtencion,
                                       @WebParam(name = "sistema",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String sistema,
                                       @WebParam(name = "sr",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String sr,
                                       @WebParam(name = "sd",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String sd,
                                       @WebParam(name = "hd",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String hd,
                                       @WebParam(name = "phd",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String phd,
                                       @WebParam(name = "hmc",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String hmc,
                                       @WebParam(name = "paquete",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String paquete,
                                       @WebParam(name = "creceA",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String creceA,
                                       @WebParam(name = "totalCrec",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String totalCrec,
                                       @WebParam(name = "equiposActivos",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String equiposActivos,
                                       @WebParam(name = "mig",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA")
                                       String mig,
                                       @WebParam(name = "codigoError",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA",
                                                 mode = WebParam.Mode.OUT) Holder<String> codigoError,
                                       @WebParam(name = "descError",
                                                 targetNamespace =
                                                 "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/InsertaCrecimientos_TYA",
                                                 mode = WebParam.Mode.OUT) Holder<String> descError);

}
