
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultastatuspreregistro;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaStatusPreregistro",
                  targetNamespace = "http://xmlns.oracle.com/ConsultaStatusPreregistro",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaStatusPreregistro/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaStatusPreregistro%7DConsultaStatusPreregistro")
public class ConsultaStatusPreregistro_Service extends Service {

    private final static URL CONSULTASTATUSPREREGISTRO_WSDL_LOCATION;
    private final static WebServiceException CONSULTASTATUSPREREGISTRO_EXCEPTION;
    private final static QName CONSULTASTATUSPREREGISTRO_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaStatusPreregistro", "ConsultaStatusPreregistro");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaStatusPreregistro/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaStatusPreregistro%7DConsultaStatusPreregistro");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTASTATUSPREREGISTRO_WSDL_LOCATION = url;
        CONSULTASTATUSPREREGISTRO_EXCEPTION = e;
    }

    public ConsultaStatusPreregistro_Service() {
        super(__getWsdlLocation(), CONSULTASTATUSPREREGISTRO_QNAME);
    }

    public ConsultaStatusPreregistro_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTASTATUSPREREGISTRO_QNAME, features);
    }

    public ConsultaStatusPreregistro_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTASTATUSPREREGISTRO_QNAME);
    }

    public ConsultaStatusPreregistro_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTASTATUSPREREGISTRO_QNAME, features);
    }

    public ConsultaStatusPreregistro_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaStatusPreregistro_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaStatusPreregistro
     */
    @WebEndpoint(name = "ConsultaStatusPreregistro")
    public ConsultaStatusPreregistro getConsultaStatusPreregistro() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaStatusPreregistro",
                                       "ConsultaStatusPreregistro"), ConsultaStatusPreregistro.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaStatusPreregistro
     */
    @WebEndpoint(name = "ConsultaStatusPreregistro")
    public ConsultaStatusPreregistro getConsultaStatusPreregistro(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaStatusPreregistro",
                                       "ConsultaStatusPreregistro"), ConsultaStatusPreregistro.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTASTATUSPREREGISTRO_EXCEPTION != null) {
            throw CONSULTASTATUSPREREGISTRO_EXCEPTION;
        }
        return CONSULTASTATUSPREREGISTRO_WSDL_LOCATION;
    }

}
