
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultapagos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultapagos.types.ConsultaPagosProcessRequest;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultapagos.types.ConsultaPagosProcessResponse;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultapagos.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaPagos", targetNamespace = "http://xmlns.oracle.com/ConsultaPagos")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaPagos {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultapagos.types.ConsultaPagosProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "ConsultaPagosProcessResponse", targetNamespace = "http://xmlns.oracle.com/ConsultaPagos",
               partName = "payload")
    public ConsultaPagosProcessResponse process(@WebParam(name = "ConsultaPagosProcessRequest",
                                                          targetNamespace = "http://xmlns.oracle.com/ConsultaPagos",
                                                          partName = "payload") ConsultaPagosProcessRequest payload);

}
