package mx.com.sky.sel.proxyclients.pagwebconsultas.consultapagos;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaPagosClient {
    public static void main(String[] args) {
        ConsultaPagos_Service consultaPagos_Service = new ConsultaPagos_Service();
        ConsultaPagos consultaPagos = consultaPagos_Service.getConsultaPagos();
        // Add your code to call the desired methods.


    }
}
