package mx.com.sky.sel.proxyclients.pagwebss.actualizatablabatch;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ActualizaTablaBatchSSClient {
    public static void main(String[] args) {
        ActualizaTablaBatchSS_Service actualizaTablaBatchSS_Service = new ActualizaTablaBatchSS_Service();
        ActualizaTablaBatchSS actualizaTablaBatchSS = actualizaTablaBatchSS_Service.getActualizaTablaBatchSS();
        // Add your code to call the desired methods.


    }
}
