
package mx.com.sky.sel.proxyclients.selebf.autenticarusuario;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "AutenticarUsuarioSelEBF_ep",
                  targetNamespace =
                  "http://xmlns.sky.com.mx/EnterpriseFlows/Sel/AutenticarUsuario",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_EBF/AutenticarUsuarioSelEBF/AutenticarUsuarioSelEBF_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FEnterpriseFlows%2FSel%2FAutenticarUsuario%7DAutenticarUsuarioSelEBF_ep")
public class AutenticarUsuarioSelEBFEp extends Service {

    private final static URL AUTENTICARUSUARIOSELEBFEP_WSDL_LOCATION;
    private final static WebServiceException AUTENTICARUSUARIOSELEBFEP_EXCEPTION;
    private final static QName AUTENTICARUSUARIOSELEBFEP_QNAME =
        new QName("http://xmlns.sky.com.mx/EnterpriseFlows/Sel/AutenticarUsuario",
                  "AutenticarUsuarioSelEBF_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_EBF/AutenticarUsuarioSelEBF/AutenticarUsuarioSelEBF_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FEnterpriseFlows%2FSel%2FAutenticarUsuario%7DAutenticarUsuarioSelEBF_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTENTICARUSUARIOSELEBFEP_WSDL_LOCATION = url;
        AUTENTICARUSUARIOSELEBFEP_EXCEPTION = e;
    }

    public AutenticarUsuarioSelEBFEp() {
        super(__getWsdlLocation(), AUTENTICARUSUARIOSELEBFEP_QNAME);
    }

    public AutenticarUsuarioSelEBFEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTENTICARUSUARIOSELEBFEP_QNAME, features);
    }

    public AutenticarUsuarioSelEBFEp(URL wsdlLocation) {
        super(wsdlLocation, AUTENTICARUSUARIOSELEBFEP_QNAME);
    }

    public AutenticarUsuarioSelEBFEp(URL wsdlLocation,
                                     WebServiceFeature... features) {
        super(wsdlLocation, AUTENTICARUSUARIOSELEBFEP_QNAME, features);
    }

    public AutenticarUsuarioSelEBFEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutenticarUsuarioSelEBFEp(URL wsdlLocation, QName serviceName,
                                     WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns AutenticarUsuarioSelEBF
     */
    @WebEndpoint(name = "AutenticarUsuarioSelEBF_pt")
    public AutenticarUsuarioSelEBF getAutenticarUsuarioSelEBFPt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/EnterpriseFlows/Sel/AutenticarUsuario",
                                       "AutenticarUsuarioSelEBF_pt"),
                             AutenticarUsuarioSelEBF.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutenticarUsuarioSelEBF
     */
    @WebEndpoint(name = "AutenticarUsuarioSelEBF_pt")
    public AutenticarUsuarioSelEBF getAutenticarUsuarioSelEBFPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/EnterpriseFlows/Sel/AutenticarUsuario",
                                       "AutenticarUsuarioSelEBF_pt"),
                             AutenticarUsuarioSelEBF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTENTICARUSUARIOSELEBFEP_EXCEPTION != null) {
            throw AUTENTICARUSUARIOSELEBFEP_EXCEPTION;
        }
        return AUTENTICARUSUARIOSELEBFEP_WSDL_LOCATION;
    }

}
