
package mx.com.sky.sel.proxyclients.pagwebregistro.preregistrousuario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebregistro.preregistrousuario.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "PreRegistroUsuarioProcess",
            targetNamespace = "http://xmlns.oracle.com/Application1/PreRegistroUsuario/PreRegistroUsuarioProcess")
@XmlSeeAlso({ ObjectFactory.class })
public interface PreRegistroUsuarioProcess {


    /**
     *
     * @param resultado
     * @param email
     * @param resultadodesc
     */
    @WebMethod(action = "process")
    @RequestWrapper(localName = "process",
                    targetNamespace =
                    "http://xmlns.oracle.com/Application1/PreRegistroUsuario/PreRegistroUsuarioProcess",
                    className = "mx.com.sky.sel.proxyclients.pagwebregistro.preregistrousuario.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/Application1/PreRegistroUsuario/PreRegistroUsuarioProcess",
                     className = "mx.com.sky.sel.proxyclients.pagwebregistro.preregistrousuario.types.ProcessResponse")
    public void process(@WebParam(name = "email",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/Application1/PreRegistroUsuario/PreRegistroUsuarioProcess")
                        String email,
                        @WebParam(name = "resultado",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/Application1/PreRegistroUsuario/PreRegistroUsuarioProcess",
                                  mode = WebParam.Mode.OUT) Holder<String> resultado,
                        @WebParam(name = "resultadodesc",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/Application1/PreRegistroUsuario/PreRegistroUsuarioProcess",
                                  mode = WebParam.Mode.OUT) Holder<String> resultadodesc);

}
