
package mx.com.sky.sel.proxyclients.pagwebregistro.preregistrousuario;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "preRegistroUsuario_ep",
                  targetNamespace = "http://xmlns.oracle.com/Application1/PreRegistroUsuario/PreRegistroUsuarioProcess",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebregistro/PreRegistroUsuario/preRegistroUsuario_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FApplication1%2FPreRegistroUsuario%2FPreRegistroUsuarioProcess%7DpreRegistroUsuario_ep")
public class PreRegistroUsuarioEp extends Service {

    private final static URL PREREGISTROUSUARIOEP_WSDL_LOCATION;
    private final static WebServiceException PREREGISTROUSUARIOEP_EXCEPTION;
    private final static QName PREREGISTROUSUARIOEP_QNAME =
        new QName("http://xmlns.oracle.com/Application1/PreRegistroUsuario/PreRegistroUsuarioProcess",
                  "preRegistroUsuario_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebregistro/PreRegistroUsuario/preRegistroUsuario_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FApplication1%2FPreRegistroUsuario%2FPreRegistroUsuarioProcess%7DpreRegistroUsuario_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PREREGISTROUSUARIOEP_WSDL_LOCATION = url;
        PREREGISTROUSUARIOEP_EXCEPTION = e;
    }

    public PreRegistroUsuarioEp() {
        super(__getWsdlLocation(), PREREGISTROUSUARIOEP_QNAME);
    }

    public PreRegistroUsuarioEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), PREREGISTROUSUARIOEP_QNAME, features);
    }

    public PreRegistroUsuarioEp(URL wsdlLocation) {
        super(wsdlLocation, PREREGISTROUSUARIOEP_QNAME);
    }

    public PreRegistroUsuarioEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PREREGISTROUSUARIOEP_QNAME, features);
    }

    public PreRegistroUsuarioEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PreRegistroUsuarioEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns PreRegistroUsuarioProcess
     */
    @WebEndpoint(name = "PreRegistroUsuarioProcess_pt")
    public PreRegistroUsuarioProcess getPreRegistroUsuarioProcessPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/Application1/PreRegistroUsuario/PreRegistroUsuarioProcess",
                                       "PreRegistroUsuarioProcess_pt"), PreRegistroUsuarioProcess.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PreRegistroUsuarioProcess
     */
    @WebEndpoint(name = "PreRegistroUsuarioProcess_pt")
    public PreRegistroUsuarioProcess getPreRegistroUsuarioProcessPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/Application1/PreRegistroUsuario/PreRegistroUsuarioProcess",
                                       "PreRegistroUsuarioProcess_pt"), PreRegistroUsuarioProcess.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PREREGISTROUSUARIOEP_EXCEPTION != null) {
            throw PREREGISTROUSUARIOEP_EXCEPTION;
        }
        return PREREGISTROUSUARIOEP_WSDL_LOCATION;
    }

}
