
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultamundialactivo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultamundialactivo.types.CodigoError;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultamundialactivo.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaMundialActivo",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaMundialActivo/ConsultaMundialActivo")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaMundialActivo {


    /**
     *
     * @param codigoError
     * @param numeroCuenta
     * @param tipoMercado
     * @param mundialActivo
     */
    @WebMethod(action =
               "http://xmlns.oracle.com/SKYConsultas/ConsultaMundialActivo/ConsultaMundialActivo/consultaMundialActivo")
    @RequestWrapper(localName = "consultaMundialActivo",
                    targetNamespace =
                    "http://xmlns.oracle.com/SKYConsultas/ConsultaMundialActivo/ConsultaMundialActivo",
                    className =
                    "mx.com.sky.sel.proxyclients.pagwebconsultas.consultamundialactivo.types.ConsultaMundialActivo")
    @ResponseWrapper(localName = "consultaMundialActivoResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/SKYConsultas/ConsultaMundialActivo/ConsultaMundialActivo",
                     className =
                     "mx.com.sky.sel.proxyclients.pagwebconsultas.consultamundialactivo.types.ConsultaMundialActivoResponse")
    public void consultaMundialActivo(@WebParam(name = "NumeroCuenta",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKYConsultas/ConsultaMundialActivo/ConsultaMundialActivo")
                                      String numeroCuenta,
                                      @WebParam(name = "TipoMercado",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKYConsultas/ConsultaMundialActivo/ConsultaMundialActivo")
                                      String tipoMercado,
                                      @WebParam(name = "CodigoError",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKYConsultas/ConsultaMundialActivo/ConsultaMundialActivo",
                                                mode = WebParam.Mode.OUT) Holder<CodigoError> codigoError,
                                      @WebParam(name = "MundialActivo",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKYConsultas/ConsultaMundialActivo/ConsultaMundialActivo",
                                                mode = WebParam.Mode.OUT) Holder<String> mundialActivo);

}
