
package mx.com.sky.sel.proxyclients.selabcs.eliminartarjetapagoselabcs;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "EliminarTarjetaPagoSelABCS_ep",
                  targetNamespace =
                  "http://xmlns.sky.com.mx/ABCSImpl/Sel/EliminarTarjetaPago",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_ABCS/EliminarTarjetaPagoSelABCS/EliminarTarjetaPagoSelABCS_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FABCSImpl%2FSel%2FEliminarTarjetaPago%7DEliminarTarjetaPagoSelABCS_ep")
public class EliminarTarjetaPagoSelABCSEp extends Service {

    private final static URL ELIMINARTARJETAPAGOSELABCSEP_WSDL_LOCATION;
    private final static WebServiceException ELIMINARTARJETAPAGOSELABCSEP_EXCEPTION;
    private final static QName ELIMINARTARJETAPAGOSELABCSEP_QNAME =
        new QName("http://xmlns.sky.com.mx/ABCSImpl/Sel/EliminarTarjetaPago",
                  "EliminarTarjetaPagoSelABCS_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_ABCS/EliminarTarjetaPagoSelABCS/EliminarTarjetaPagoSelABCS_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FABCSImpl%2FSel%2FEliminarTarjetaPago%7DEliminarTarjetaPagoSelABCS_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ELIMINARTARJETAPAGOSELABCSEP_WSDL_LOCATION = url;
        ELIMINARTARJETAPAGOSELABCSEP_EXCEPTION = e;
    }

    public EliminarTarjetaPagoSelABCSEp() {
        super(__getWsdlLocation(), ELIMINARTARJETAPAGOSELABCSEP_QNAME);
    }

    public EliminarTarjetaPagoSelABCSEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), ELIMINARTARJETAPAGOSELABCSEP_QNAME,
              features);
    }

    public EliminarTarjetaPagoSelABCSEp(URL wsdlLocation) {
        super(wsdlLocation, ELIMINARTARJETAPAGOSELABCSEP_QNAME);
    }

    public EliminarTarjetaPagoSelABCSEp(URL wsdlLocation,
                                        WebServiceFeature... features) {
        super(wsdlLocation, ELIMINARTARJETAPAGOSELABCSEP_QNAME, features);
    }

    public EliminarTarjetaPagoSelABCSEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EliminarTarjetaPagoSelABCSEp(URL wsdlLocation, QName serviceName,
                                        WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns EliminarTarjetaPagoSelABCS
     */
    @WebEndpoint(name = "EliminarTarjetaPagoSelABCS_pt")
    public EliminarTarjetaPagoSelABCS getEliminarTarjetaPagoSelABCSPt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/ABCSImpl/Sel/EliminarTarjetaPago",
                                       "EliminarTarjetaPagoSelABCS_pt"),
                             EliminarTarjetaPagoSelABCS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EliminarTarjetaPagoSelABCS
     */
    @WebEndpoint(name = "EliminarTarjetaPagoSelABCS_pt")
    public EliminarTarjetaPagoSelABCS getEliminarTarjetaPagoSelABCSPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/ABCSImpl/Sel/EliminarTarjetaPago",
                                       "EliminarTarjetaPagoSelABCS_pt"),
                             EliminarTarjetaPagoSelABCS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ELIMINARTARJETAPAGOSELABCSEP_EXCEPTION != null) {
            throw ELIMINARTARJETAPAGOSELABCSEP_EXCEPTION;
        }
        return ELIMINARTARJETAPAGOSELABCSEP_WSDL_LOCATION;
    }

}
