package mx.com.sky.sel.proxyclients.edicom.obtenerfactura;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="https://dessapsoa.sky.com.mx:443/soa-infra/services/facturacion/FacturaEdicom/obtenerfactura_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/AppFacturaEdicom/FacturaEdicom/ObtenerFactura",
  name="ObtenerFactura")
@XmlSeeAlso(
  { mx.com.sky.sel.proxyclients.edicom.obtenerfactura.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface ObtenerFactura
{
  @WebMethod(action="process")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="process", output="http://xmlns.oracle.com/AppFacturaEdicom/FacturaEdicom/ObtenerFactura/ObtenerFactura/processResponse")
  @WebResult(targetNamespace="http://factura.edicom.factura.sky.com.mx",
    partName="payload", name="ObtenerFacturaOUT")
  public mx.com.sky.sel.proxyclients.edicom.obtenerfactura.ObtenerFacturaOUTType process(@WebParam(targetNamespace="http://factura.edicom.factura.sky.com.mx",
      partName="payload", name="ObtenerFacturaIN")
    mx.com.sky.sel.proxyclients.edicom.obtenerfactura.ObtenerFacturaINType payload);
}
