package mx.com.sky.sel.proxyclients.edicom.obtenerfactura;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="https://dessapsoa.sky.com.mx:443/soa-infra/services/facturacion/FacturaEdicom/obtenerfactura_client_ep?WSDL",
  targetNamespace="http://xmlns.oracle.com/AppFacturaEdicom/FacturaEdicom/ObtenerFactura",
  name="obtenerfactura_client_ep")
public class Obtenerfactura_client_ep
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("mx.com.sky.sel.proxyclients.edicom.obtenerfactura.Obtenerfactura_client_ep");
      URL baseUrl = Obtenerfactura_client_ep.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            Obtenerfactura_client_ep.class.getResource("https://dessapsoa.sky.com.mx:443/soa-infra/services/facturacion/FacturaEdicom/obtenerfactura_client_ep?WSDL");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "https://dessapsoa.sky.com.mx:443/soa-infra/services/facturacion/FacturaEdicom/obtenerfactura_client_ep?WSDL");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "https://dessapsoa.sky.com.mx:443/soa-infra/services/facturacion/FacturaEdicom/obtenerfactura_client_ep?WSDL");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using https://dessapsoa.sky.com.mx:443/soa-infra/services/facturacion/FacturaEdicom/obtenerfactura_client_ep?WSDL",
          e);
    }
  }

  public Obtenerfactura_client_ep()
  {
    super(wsdlLocationURL,
          new QName("http://xmlns.oracle.com/AppFacturaEdicom/FacturaEdicom/ObtenerFactura",
                    "obtenerfactura_client_ep"));
  }

  public Obtenerfactura_client_ep(URL wsdlLocation, QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ObtenerFactura_pt")
  public mx.com.sky.sel.proxyclients.edicom.obtenerfactura.ObtenerFactura getObtenerFactura_pt()
  {
    return (mx.com.sky.sel.proxyclients.edicom.obtenerfactura.ObtenerFactura) super.getPort(new QName("http://xmlns.oracle.com/AppFacturaEdicom/FacturaEdicom/ObtenerFactura",
                                                                                           "ObtenerFactura_pt"),
                                                                                 mx.com.sky.sel.proxyclients.edicom.obtenerfactura.ObtenerFactura.class);
  }

  @WebEndpoint(name="ObtenerFactura_pt")
  public mx.com.sky.sel.proxyclients.edicom.obtenerfactura.ObtenerFactura getObtenerFactura_pt(WebServiceFeature... features)
  {
    return (mx.com.sky.sel.proxyclients.edicom.obtenerfactura.ObtenerFactura) super.getPort(new QName("http://xmlns.oracle.com/AppFacturaEdicom/FacturaEdicom/ObtenerFactura",
                                                                                           "ObtenerFactura_pt"),
                                                                                 mx.com.sky.sel.proxyclients.edicom.obtenerfactura.ObtenerFactura.class,
                                                                                 features);
  }
}
