
package mx.com.sky.sel.proxyclients.selinterface.consultarcuentaacthd;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultarCuentaActHdSelInterface_ep",
                  targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarCuentaActHd",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_Interface/ConsultarCuentaActHdSelInterface/ConsultarCuentaActHdSelInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSel%2FConsultarCuentaActHd%7DConsultarCuentaActHdSelInterface_ep")
public class ConsultarCuentaActHdSelInterfaceEp extends Service {

    private final static URL CONSULTARCUENTAACTHDSELINTERFACEEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTARCUENTAACTHDSELINTERFACEEP_EXCEPTION;
    private final static QName CONSULTARCUENTAACTHDSELINTERFACEEP_QNAME =
        new QName("http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarCuentaActHd",
                  "ConsultarCuentaActHdSelInterface_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_Interface/ConsultarCuentaActHdSelInterface/ConsultarCuentaActHdSelInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSel%2FConsultarCuentaActHd%7DConsultarCuentaActHdSelInterface_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARCUENTAACTHDSELINTERFACEEP_WSDL_LOCATION = url;
        CONSULTARCUENTAACTHDSELINTERFACEEP_EXCEPTION = e;
    }

    public ConsultarCuentaActHdSelInterfaceEp() {
        super(__getWsdlLocation(), CONSULTARCUENTAACTHDSELINTERFACEEP_QNAME);
    }

    public ConsultarCuentaActHdSelInterfaceEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARCUENTAACTHDSELINTERFACEEP_QNAME, features);
    }

    public ConsultarCuentaActHdSelInterfaceEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARCUENTAACTHDSELINTERFACEEP_QNAME);
    }

    public ConsultarCuentaActHdSelInterfaceEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARCUENTAACTHDSELINTERFACEEP_QNAME, features);
    }

    public ConsultarCuentaActHdSelInterfaceEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarCuentaActHdSelInterfaceEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultarCuentaActHdSelInterface
     */
    @WebEndpoint(name = "ConsultarCuentaActHdSelInterface_pt")
    public ConsultarCuentaActHdSelInterface getConsultarCuentaActHdSelInterfacePt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarCuentaActHd",
                                       "ConsultarCuentaActHdSelInterface_pt"), ConsultarCuentaActHdSelInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarCuentaActHdSelInterface
     */
    @WebEndpoint(name = "ConsultarCuentaActHdSelInterface_pt")
    public ConsultarCuentaActHdSelInterface getConsultarCuentaActHdSelInterfacePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarCuentaActHd",
                                       "ConsultarCuentaActHdSelInterface_pt"), ConsultarCuentaActHdSelInterface.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARCUENTAACTHDSELINTERFACEEP_EXCEPTION != null) {
            throw CONSULTARCUENTAACTHDSELINTERFACEEP_EXCEPTION;
        }
        return CONSULTARCUENTAACTHDSELINTERFACEEP_WSDL_LOCATION;
    }

}
