package mx.com.sky.sel.proxyclients.selinterface.consultarcuentaacthd;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultarCuentaActHdSelInterface_ptClient {
    public static void main(String[] args) {
        ConsultarCuentaActHdSelInterfaceEp consultarCuentaActHdSelInterfaceEp =
            new ConsultarCuentaActHdSelInterfaceEp();
        ConsultarCuentaActHdSelInterface consultarCuentaActHdSelInterface =
            consultarCuentaActHdSelInterfaceEp.getConsultarCuentaActHdSelInterfacePt();
        // Add your code to call the desired methods.


    }
}
