
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultamenu;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaMenu", targetNamespace = "http://xmlns.oracle.com/ConsultaMenu",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaMenu/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaMenu%7DConsultaMenu")
public class ConsultaMenu_Service extends Service {

    private final static URL CONSULTAMENU_WSDL_LOCATION;
    private final static WebServiceException CONSULTAMENU_EXCEPTION;
    private final static QName CONSULTAMENU_QNAME = new QName("http://xmlns.oracle.com/ConsultaMenu", "ConsultaMenu");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaMenu/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaMenu%7DConsultaMenu");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAMENU_WSDL_LOCATION = url;
        CONSULTAMENU_EXCEPTION = e;
    }

    public ConsultaMenu_Service() {
        super(__getWsdlLocation(), CONSULTAMENU_QNAME);
    }

    public ConsultaMenu_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAMENU_QNAME, features);
    }

    public ConsultaMenu_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAMENU_QNAME);
    }

    public ConsultaMenu_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAMENU_QNAME, features);
    }

    public ConsultaMenu_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaMenu_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaMenu
     */
    @WebEndpoint(name = "ConsultaMenu")
    public ConsultaMenu getConsultaMenu() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaMenu", "ConsultaMenu"), ConsultaMenu.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaMenu
     */
    @WebEndpoint(name = "ConsultaMenu")
    public ConsultaMenu getConsultaMenu(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaMenu", "ConsultaMenu"), ConsultaMenu.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAMENU_EXCEPTION != null) {
            throw CONSULTAMENU_EXCEPTION;
        }
        return CONSULTAMENU_WSDL_LOCATION;
    }

}
