package mx.com.sky.sel.proxyclients.pagwebconsultas.consultamenu;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaMenuClient {
    public static void main(String[] args) {
        ConsultaMenu_Service consultaMenu_Service = new ConsultaMenu_Service();
        ConsultaMenu consultaMenu = consultaMenu_Service.getConsultaMenu();
        // Add your code to call the desired methods.


    }
}
