
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultareceptordigital;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultareceptordigital.types.CTReceptorInType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultareceptordigital.types.CTReceptorOutType;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultareceptordigital.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaReceptorDigital",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaCambioTitular/ConsultaReceptorDigital")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaReceptorDigital {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultareceptordigital.types.CTReceptorOutType
     */
    @WebMethod(action = "process")
    @WebResult(name = "CTReceptorOut", targetNamespace = "http://cambiotitular.serviciosenlinea.sky.com.mx",
               partName = "payload")
    public CTReceptorOutType process(@WebParam(name = "CTReceptorIn",
                                               targetNamespace = "http://cambiotitular.serviciosenlinea.sky.com.mx",
                                               partName = "payload") CTReceptorInType payload);

}
