package mx.com.sky.sel.proxyclients.pagwebconsultas.consultactasasociadas;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaCuentasAsociadasClient {
    public static void main(String[] args) {
        ConsultaCuentasAsociadas_Service consultaCuentasAsociadas_Service = new ConsultaCuentasAsociadas_Service();
        ConsultaCuentasAsociadas consultaCuentasAsociadas =
            consultaCuentasAsociadas_Service.getConsultaCuentasAsociadas();
        // Add your code to call the desired methods.


    }
}
