
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultapreciocanal;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "consultapreciocanal_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaCanalesALaCarta/ConsultaPrecioCanal",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaCanalesALaCarta/consultapreciocanal_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKYConsultas%2FConsultaCanalesALaCarta%2FConsultaPrecioCanal%7Dconsultapreciocanal_client_ep")
public class ConsultapreciocanalClientEp extends Service {

    private final static URL CONSULTAPRECIOCANALCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPRECIOCANALCLIENTEP_EXCEPTION;
    private final static QName CONSULTAPRECIOCANALCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaCanalesALaCarta/ConsultaPrecioCanal",
                  "consultapreciocanal_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaCanalesALaCarta/consultapreciocanal_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKYConsultas%2FConsultaCanalesALaCarta%2FConsultaPrecioCanal%7Dconsultapreciocanal_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPRECIOCANALCLIENTEP_WSDL_LOCATION = url;
        CONSULTAPRECIOCANALCLIENTEP_EXCEPTION = e;
    }

    public ConsultapreciocanalClientEp() {
        super(__getWsdlLocation(), CONSULTAPRECIOCANALCLIENTEP_QNAME);
    }

    public ConsultapreciocanalClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPRECIOCANALCLIENTEP_QNAME, features);
    }

    public ConsultapreciocanalClientEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPRECIOCANALCLIENTEP_QNAME);
    }

    public ConsultapreciocanalClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPRECIOCANALCLIENTEP_QNAME, features);
    }

    public ConsultapreciocanalClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultapreciocanalClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaPrecioCanal
     */
    @WebEndpoint(name = "ConsultaPrecioCanal_pt")
    public ConsultaPrecioCanal getConsultaPrecioCanalPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaCanalesALaCarta/ConsultaPrecioCanal",
                                       "ConsultaPrecioCanal_pt"), ConsultaPrecioCanal.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaPrecioCanal
     */
    @WebEndpoint(name = "ConsultaPrecioCanal_pt")
    public ConsultaPrecioCanal getConsultaPrecioCanalPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaCanalesALaCarta/ConsultaPrecioCanal",
                                       "ConsultaPrecioCanal_pt"), ConsultaPrecioCanal.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPRECIOCANALCLIENTEP_EXCEPTION != null) {
            throw CONSULTAPRECIOCANALCLIENTEP_EXCEPTION;
        }
        return CONSULTAPRECIOCANALCLIENTEP_WSDL_LOCATION;
    }

}
