
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultabines;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaBines", targetNamespace = "http://xmlns.oracle.com/ConsultaBines",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaBines/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaBines%7DConsultaBines")
public class ConsultaBines_Service extends Service {

    private final static URL CONSULTABINES_WSDL_LOCATION;
    private final static WebServiceException CONSULTABINES_EXCEPTION;
    private final static QName CONSULTABINES_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaBines", "ConsultaBines");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaBines/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaBines%7DConsultaBines");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTABINES_WSDL_LOCATION = url;
        CONSULTABINES_EXCEPTION = e;
    }

    public ConsultaBines_Service() {
        super(__getWsdlLocation(), CONSULTABINES_QNAME);
    }

    public ConsultaBines_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTABINES_QNAME, features);
    }

    public ConsultaBines_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTABINES_QNAME);
    }

    public ConsultaBines_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTABINES_QNAME, features);
    }

    public ConsultaBines_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaBines_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaBines
     */
    @WebEndpoint(name = "ConsultaBines")
    public ConsultaBines getConsultaBines() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaBines", "ConsultaBines"), ConsultaBines.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaBines
     */
    @WebEndpoint(name = "ConsultaBines")
    public ConsultaBines getConsultaBines(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaBines", "ConsultaBines"), ConsultaBines.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTABINES_EXCEPTION != null) {
            throw CONSULTABINES_EXCEPTION;
        }
        return CONSULTABINES_WSDL_LOCATION;
    }

}
