
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultainfofiscalvigente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultainfofiscalvigente.types.ConsultaInformacionFiscalVigenteProcessRequest;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultainfofiscalvigente.types.ConsultaInformacionFiscalVigenteProcessResponse;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultainfofiscalvigente.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaInformacionFiscalVigente",
            targetNamespace = "http://xmlns.oracle.com/ConsultaInformacionFiscalVigente")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaInformacionFiscalVigente {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultainfofiscalvigente.types.ConsultaInformacionFiscalVigenteProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "ConsultaInformacionFiscalVigenteProcessResponse",
               targetNamespace = "http://xmlns.oracle.com/ConsultaInformacionFiscalVigente", partName = "payload")
    public ConsultaInformacionFiscalVigenteProcessResponse process(@WebParam(name =
                                                                             "ConsultaInformacionFiscalVigenteProcessRequest",
                                                                             targetNamespace =
                                                                             "http://xmlns.oracle.com/ConsultaInformacionFiscalVigente",
                                                                             partName = "payload")
                                                                   ConsultaInformacionFiscalVigenteProcessRequest payload);

}
