
package mx.com.sky.sel.proxyclients.selebf.registrardatosfiscalesselebf;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "RegistrarDatosFiscalesSelEBF_ep",
                  targetNamespace = "http://xmlns.oracle.com/InterfaceServices/Sel/RegistrarDatosFiscales",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx/soa-infra/services/SEL_EBF/RegistrarDatosFiscalesSelEBF/RegistrarDatosFiscalesSelEBF_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FInterfaceServices%2FSel%2FRegistrarDatosFiscales%7DRegistrarDatosFiscalesSelEBF_ep")
public class RegistrarDatosFiscalesSelEBFEp extends Service {

    private final static URL REGISTRARDATOSFISCALESSELEBFEP_WSDL_LOCATION;
    private final static WebServiceException REGISTRARDATOSFISCALESSELEBFEP_EXCEPTION;
    private final static QName REGISTRARDATOSFISCALESSELEBFEP_QNAME =
        new QName("http://xmlns.oracle.com/InterfaceServices/Sel/RegistrarDatosFiscales",
                  "RegistrarDatosFiscalesSelEBF_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx/soa-infra/services/SEL_EBF/RegistrarDatosFiscalesSelEBF/RegistrarDatosFiscalesSelEBF_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FInterfaceServices%2FSel%2FRegistrarDatosFiscales%7DRegistrarDatosFiscalesSelEBF_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REGISTRARDATOSFISCALESSELEBFEP_WSDL_LOCATION = url;
        REGISTRARDATOSFISCALESSELEBFEP_EXCEPTION = e;
    }

    public RegistrarDatosFiscalesSelEBFEp() {
        super(__getWsdlLocation(), REGISTRARDATOSFISCALESSELEBFEP_QNAME);
    }

    public RegistrarDatosFiscalesSelEBFEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), REGISTRARDATOSFISCALESSELEBFEP_QNAME, features);
    }

    public RegistrarDatosFiscalesSelEBFEp(URL wsdlLocation) {
        super(wsdlLocation, REGISTRARDATOSFISCALESSELEBFEP_QNAME);
    }

    public RegistrarDatosFiscalesSelEBFEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REGISTRARDATOSFISCALESSELEBFEP_QNAME, features);
    }

    public RegistrarDatosFiscalesSelEBFEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrarDatosFiscalesSelEBFEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RegistrarDatosFiscalesSelEBF
     */
    @WebEndpoint(name = "RegistrarDatosFiscalesSelEBF_pt")
    public RegistrarDatosFiscalesSelEBF getRegistrarDatosFiscalesSelEBFPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/InterfaceServices/Sel/RegistrarDatosFiscales",
                                       "RegistrarDatosFiscalesSelEBF_pt"), RegistrarDatosFiscalesSelEBF.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrarDatosFiscalesSelEBF
     */
    @WebEndpoint(name = "RegistrarDatosFiscalesSelEBF_pt")
    public RegistrarDatosFiscalesSelEBF getRegistrarDatosFiscalesSelEBFPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/InterfaceServices/Sel/RegistrarDatosFiscales",
                                       "RegistrarDatosFiscalesSelEBF_pt"), RegistrarDatosFiscalesSelEBF.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (REGISTRARDATOSFISCALESSELEBFEP_EXCEPTION != null) {
            throw REGISTRARDATOSFISCALESSELEBFEP_EXCEPTION;
        }
        return REGISTRARDATOSFISCALESSELEBFEP_WSDL_LOCATION;
    }

}
