
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultapaquete;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaPaquete", targetNamespace = "http://xmlns.oracle.com/ConsultaPaquete",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaPaquete/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaPaquete%7DConsultaPaquete")
public class ConsultaPaquete_Service extends Service {

    private final static URL CONSULTAPAQUETE_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPAQUETE_EXCEPTION;
    private final static QName CONSULTAPAQUETE_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaPaquete", "ConsultaPaquete");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaPaquete/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaPaquete%7DConsultaPaquete");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPAQUETE_WSDL_LOCATION = url;
        CONSULTAPAQUETE_EXCEPTION = e;
    }

    public ConsultaPaquete_Service() {
        super(__getWsdlLocation(), CONSULTAPAQUETE_QNAME);
    }

    public ConsultaPaquete_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPAQUETE_QNAME, features);
    }

    public ConsultaPaquete_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPAQUETE_QNAME);
    }

    public ConsultaPaquete_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPAQUETE_QNAME, features);
    }

    public ConsultaPaquete_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaPaquete_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaPaquete
     */
    @WebEndpoint(name = "ConsultaPaquete")
    public ConsultaPaquete getConsultaPaquete() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaPaquete", "ConsultaPaquete"),
                             ConsultaPaquete.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaPaquete
     */
    @WebEndpoint(name = "ConsultaPaquete")
    public ConsultaPaquete getConsultaPaquete(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaPaquete", "ConsultaPaquete"),
                             ConsultaPaquete.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPAQUETE_EXCEPTION != null) {
            throw CONSULTAPAQUETE_EXCEPTION;
        }
        return CONSULTAPAQUETE_WSDL_LOCATION;
    }

}
