
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultapaquete;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultapaquete.types.ConsultaPaqueteProcessRequest;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultapaquete.types.ConsultaPaqueteProcessResponse;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultapaquete.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaPaquete", targetNamespace = "http://xmlns.oracle.com/ConsultaPaquete")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaPaquete {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultapaquete.types.ConsultaPaqueteProcessResponse
     */
    @WebMethod(action = "process")
    @WebResult(name = "ConsultaPaqueteProcessResponse", targetNamespace = "http://xmlns.oracle.com/ConsultaPaquete",
               partName = "payload")
    public ConsultaPaqueteProcessResponse process(@WebParam(name = "ConsultaPaqueteProcessRequest",
                                                            targetNamespace = "http://xmlns.oracle.com/ConsultaPaquete",
                                                            partName = "payload")
                                                  ConsultaPaqueteProcessRequest payload);

}
