
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultapagosporevento;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaPagosPorEvento", targetNamespace = "http://xmlns.oracle.com/ConsultaPagosPorEvento",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaPagosPorEvento/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaPagosPorEvento%7DConsultaPagosPorEvento")
public class ConsultaPagosPorEvento_Service extends Service {

    private final static URL CONSULTAPAGOSPOREVENTO_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPAGOSPOREVENTO_EXCEPTION;
    private final static QName CONSULTAPAGOSPOREVENTO_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaPagosPorEvento", "ConsultaPagosPorEvento");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaPagosPorEvento/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaPagosPorEvento%7DConsultaPagosPorEvento");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPAGOSPOREVENTO_WSDL_LOCATION = url;
        CONSULTAPAGOSPOREVENTO_EXCEPTION = e;
    }

    public ConsultaPagosPorEvento_Service() {
        super(__getWsdlLocation(), CONSULTAPAGOSPOREVENTO_QNAME);
    }

    public ConsultaPagosPorEvento_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPAGOSPOREVENTO_QNAME, features);
    }

    public ConsultaPagosPorEvento_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPAGOSPOREVENTO_QNAME);
    }

    public ConsultaPagosPorEvento_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPAGOSPOREVENTO_QNAME, features);
    }

    public ConsultaPagosPorEvento_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaPagosPorEvento_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaPagosPorEvento
     */
    @WebEndpoint(name = "ConsultaPagosPorEvento")
    public ConsultaPagosPorEvento getConsultaPagosPorEvento() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaPagosPorEvento", "ConsultaPagosPorEvento"),
                             ConsultaPagosPorEvento.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaPagosPorEvento
     */
    @WebEndpoint(name = "ConsultaPagosPorEvento")
    public ConsultaPagosPorEvento getConsultaPagosPorEvento(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaPagosPorEvento", "ConsultaPagosPorEvento"),
                             ConsultaPagosPorEvento.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPAGOSPOREVENTO_EXCEPTION != null) {
            throw CONSULTAPAGOSPOREVENTO_EXCEPTION;
        }
        return CONSULTAPAGOSPOREVENTO_WSDL_LOCATION;
    }

}
