
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultareenviosenal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultareenviosenal.types.ObjectFactory;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultareenviosenal.types.ResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaReenvioSenal",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaReenvioSenal/ConsultaReenvioSenal")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaReenvioSenal {


    /**
     *
     * @param cuentaSKY
     * @return
     *     returns mx.com.sky.sel.proxyclients.pagwebconsultas.consultareenviosenal.types.ResponseType
     */
    @WebMethod(action = "process")
    @WebResult(name = "result",
               targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaReenvioSenal/ConsultaReenvioSenal")
    @RequestWrapper(localName = "process",
                    targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaReenvioSenal/ConsultaReenvioSenal",
                    className = "mx.com.sky.sel.proxyclients.pagwebconsultas.consultareenviosenal.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaReenvioSenal/ConsultaReenvioSenal",
                     className =
                     "mx.com.sky.sel.proxyclients.pagwebconsultas.consultareenviosenal.types.ProcessResponse")
    public ResponseType process(@WebParam(name = "cuentaSKY",
                                          targetNamespace =
                                          "http://xmlns.oracle.com/SKYConsultas/ConsultaReenvioSenal/ConsultaReenvioSenal")
                                String cuentaSKY);

}
