
package mx.com.sky.sel.proxyclients.selinterface.consultarusocfdiselinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseobjects.sel.consultarusocfdi.ConsultarUsoCFDIRequestType;
import mx.com.sky.enterpriseobjects.sel.consultarusocfdi.ConsultarUsoCFDIResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultarUsoCFDI",
            targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarUsoCFDI")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ com.oracle.xmlns.pcbpel.adapter.db.dbconsultarusocfdi.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.common.v1.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.consultarusocfdi.ObjectFactory.class
    })
public interface ConsultarUsoCFDI {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseobjects.sel.consultarusocfdi.ConsultarUsoCFDIResponseType
     */
    @WebMethod(operationName = "ConsultarUsoCFDI",
               action = "http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarUsoCFDI/ConsultarUsoCFDI")
    @WebResult(name = "ConsultarUsoCFDIResponse",
               targetNamespace = "http://www.sky.com.mx/EnterpriseObjects/Sel/ConsultarUsoCFDI", partName = "payload")
    public ConsultarUsoCFDIResponseType consultarUsoCFDI(@WebParam(name = "ConsultarUsoCFDIRequest",
                                                                   targetNamespace =
                                                                   "http://www.sky.com.mx/EnterpriseObjects/Sel/ConsultarUsoCFDI",
                                                                   partName = "payload")
                                                         ConsultarUsoCFDIRequestType payload);

}
