
package mx.com.sky.sel.proxyclients.selinterface.consultarusocfdiselinterface;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultarUsoCFDI_ep",
                  targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarUsoCFDI",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx/soa-infra/services/SEL_Interface/ConsultarUsoCFDISelInterface/ConsultarUsoCFDI_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSel%2FConsultarUsoCFDI%7DConsultarUsoCFDI_ep")
public class ConsultarUsoCFDIEp extends Service {

    private final static URL CONSULTARUSOCFDIEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTARUSOCFDIEP_EXCEPTION;
    private final static QName CONSULTARUSOCFDIEP_QNAME =
        new QName("http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarUsoCFDI", "ConsultarUsoCFDI_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx/soa-infra/services/SEL_Interface/ConsultarUsoCFDISelInterface/ConsultarUsoCFDI_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSel%2FConsultarUsoCFDI%7DConsultarUsoCFDI_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARUSOCFDIEP_WSDL_LOCATION = url;
        CONSULTARUSOCFDIEP_EXCEPTION = e;
    }

    public ConsultarUsoCFDIEp() {
        super(__getWsdlLocation(), CONSULTARUSOCFDIEP_QNAME);
    }

    public ConsultarUsoCFDIEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARUSOCFDIEP_QNAME, features);
    }

    public ConsultarUsoCFDIEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARUSOCFDIEP_QNAME);
    }

    public ConsultarUsoCFDIEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARUSOCFDIEP_QNAME, features);
    }

    public ConsultarUsoCFDIEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarUsoCFDIEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultarUsoCFDI
     */
    @WebEndpoint(name = "ConsultarUsoCFDI_pt")
    public ConsultarUsoCFDI getConsultarUsoCFDIPt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarUsoCFDI",
                                       "ConsultarUsoCFDI_pt"), ConsultarUsoCFDI.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarUsoCFDI
     */
    @WebEndpoint(name = "ConsultarUsoCFDI_pt")
    public ConsultarUsoCFDI getConsultarUsoCFDIPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarUsoCFDI",
                                       "ConsultarUsoCFDI_pt"), ConsultarUsoCFDI.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARUSOCFDIEP_EXCEPTION != null) {
            throw CONSULTARUSOCFDIEP_EXCEPTION;
        }
        return CONSULTARUSOCFDIEP_WSDL_LOCATION;
    }

}
