
package mx.com.sky.sel.proxyclients.selebf.certificaconcesionbeneficio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseflowmessage.sel.certificaconcesionbeneficio.CertificaConcesionBeneficioRequestEBMType;
import mx.com.sky.enterpriseflowmessage.sel.certificaconcesionbeneficio.CertificaConcesionBeneficioResponseEBMType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "CertificaConcesionBeneficioSelEBF",
            targetNamespace = "http://www.sky.com.mx/EnterpriseFlows/Sel/CertificaConcesionBeneficio")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ mx.com.sky.enterpriseflowmessage.sel.certificaconcesionbeneficio.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.common.v1.ObjectFactory.class })
public interface CertificaConcesionBeneficioSelEBF {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseflowmessage.sel.certificaconcesionbeneficio.CertificaConcesionBeneficioResponseEBMType
     */
    @WebMethod(operationName = "CertificaConcesionBeneficio",
               action =
               "http://www.sky.com.mx/EnterpriseFlows/Sel/CertificaConcesionBeneficio/CertificaConcesionBeneficio")
    @WebResult(name = "CertificaConcesionBeneficioResponseEBM",
               targetNamespace = "http://www.sky.com.mx/EnterpriseFlowMessage/Sel/CertificaConcesionBeneficio",
               partName = "payload")
    public CertificaConcesionBeneficioResponseEBMType certificaConcesionBeneficio(@WebParam(name =
                                                                                            "CertificaConcesionBeneficioRequestEBM",
                                                                                            targetNamespace =
                                                                                            "http://www.sky.com.mx/EnterpriseFlowMessage/Sel/CertificaConcesionBeneficio",
                                                                                            partName = "payload")
                                                                                  CertificaConcesionBeneficioRequestEBMType payload);

}
