
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultaprodcontratado;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultaprodcontratado.types.CodigoError;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultaprodcontratado.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaProductoContratado",
            targetNamespace =
            "http://xmlns.oracle.com/SKYConsultas/ConsultaProductoContratado/ConsultaProductoContratado")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaProductoContratado {


    /**
     *
     * @param codigoError
     * @param productoContratado
     * @param numeroCuenta
     * @param tarjetaInteligente
     * @param nombreProducto
     */
    @WebMethod(action =
               "http://xmlns.oracle.com/SKYConsultas/ConsultaProductoContratado/ConsultaProductoContratado/consultaProductoContratado")
    @RequestWrapper(localName = "consultaProductoContratado",
                    targetNamespace =
                    "http://xmlns.oracle.com/SKYConsultas/ConsultaProductoContratado/ConsultaProductoContratado",
                    className =
                    "mx.com.sky.sel.proxyclients.pagwebconsultas.consultaprodcontratado.types.ConsultaProductoContratado")
    @ResponseWrapper(localName = "consultaProductoContratadoResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/SKYConsultas/ConsultaProductoContratado/ConsultaProductoContratado",
                     className =
                     "mx.com.sky.sel.proxyclients.pagwebconsultas.consultaprodcontratado.types.ConsultaProductoContratadoResponse")
    public void consultaProductoContratado(@WebParam(name = "NumeroCuenta",
                                                     targetNamespace =
                                                     "http://xmlns.oracle.com/SKYConsultas/ConsultaProductoContratado/ConsultaProductoContratado")
                                           String numeroCuenta,
                                           @WebParam(name = "NombreProducto",
                                                     targetNamespace =
                                                     "http://xmlns.oracle.com/SKYConsultas/ConsultaProductoContratado/ConsultaProductoContratado")
                                           String nombreProducto,
                                           @WebParam(name = "TarjetaInteligente",
                                                     targetNamespace =
                                                     "http://xmlns.oracle.com/SKYConsultas/ConsultaProductoContratado/ConsultaProductoContratado")
                                           String tarjetaInteligente,
                                           @WebParam(name = "CodigoError",
                                                     targetNamespace =
                                                     "http://xmlns.oracle.com/SKYConsultas/ConsultaProductoContratado/ConsultaProductoContratado",
                                                     mode = WebParam.Mode.OUT) Holder<CodigoError> codigoError,
                                           @WebParam(name = "ProductoContratado",
                                                     targetNamespace =
                                                     "http://xmlns.oracle.com/SKYConsultas/ConsultaProductoContratado/ConsultaProductoContratado",
                                                     mode = WebParam.Mode.OUT) Holder<String> productoContratado);

}
