
package mx.com.sky.sel.proxyclients.pwoperaciones.bpelpwconfiggenerales;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import com.oracle.xmlns.pwoperaciones.pwconfiggenerales.bpelpwconfiggenerales.ObjectFactory;
import com.oracle.xmlns.pwoperaciones.pwconfiggenerales.bpelpwconfiggenerales.Proceso;
import com.oracle.xmlns.pwoperaciones.pwconfiggenerales.bpelpwconfiggenerales.RespuestaProceso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "BPELPWConfigGenerales",
            targetNamespace = "http://xmlns.oracle.com/PWOperaciones/PWConfigGenerales/BPELPWConfigGenerales")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface BPELPWConfigGenerales {


    /**
     *
     * @param payload
     * @return
     *     returns com.oracle.xmlns.pwoperaciones.pwconfiggenerales.bpelpwconfiggenerales.RespuestaProceso
     */
    @WebMethod(action = "process")
    @WebResult(name = "respuestaProceso",
               targetNamespace = "http://xmlns.oracle.com/PWOperaciones/PWConfigGenerales/BPELPWConfigGenerales",
               partName = "payload")
    public RespuestaProceso process(@WebParam(name = "proceso",
                                              targetNamespace =
                                              "http://xmlns.oracle.com/PWOperaciones/PWConfigGenerales/BPELPWConfigGenerales",
                                              partName = "payload") Proceso payload);

}
