
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultaprompago;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaPromesaDePago", targetNamespace = "http://xmlns.oracle.com/ConsultaPromesaDePago",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaPromesaDePago/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaPromesaDePago%7DConsultaPromesaDePago")
public class ConsultaPromesaDePago_Service extends Service {

    private final static URL CONSULTAPROMESADEPAGO_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPROMESADEPAGO_EXCEPTION;
    private final static QName CONSULTAPROMESADEPAGO_QNAME =
        new QName("http://xmlns.oracle.com/ConsultaPromesaDePago", "ConsultaPromesaDePago");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaPromesaDePago/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FConsultaPromesaDePago%7DConsultaPromesaDePago");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPROMESADEPAGO_WSDL_LOCATION = url;
        CONSULTAPROMESADEPAGO_EXCEPTION = e;
    }

    public ConsultaPromesaDePago_Service() {
        super(__getWsdlLocation(), CONSULTAPROMESADEPAGO_QNAME);
    }

    public ConsultaPromesaDePago_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPROMESADEPAGO_QNAME, features);
    }

    public ConsultaPromesaDePago_Service(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPROMESADEPAGO_QNAME);
    }

    public ConsultaPromesaDePago_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPROMESADEPAGO_QNAME, features);
    }

    public ConsultaPromesaDePago_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaPromesaDePago_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaPromesaDePago
     */
    @WebEndpoint(name = "ConsultaPromesaDePago")
    public ConsultaPromesaDePago getConsultaPromesaDePago() {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaPromesaDePago", "ConsultaPromesaDePago"),
                             ConsultaPromesaDePago.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaPromesaDePago
     */
    @WebEndpoint(name = "ConsultaPromesaDePago")
    public ConsultaPromesaDePago getConsultaPromesaDePago(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/ConsultaPromesaDePago", "ConsultaPromesaDePago"),
                             ConsultaPromesaDePago.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPROMESADEPAGO_EXCEPTION != null) {
            throw CONSULTAPROMESADEPAGO_EXCEPTION;
        }
        return CONSULTAPROMESADEPAGO_WSDL_LOCATION;
    }

}
