
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultatipocambiomoneda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagwebconsultas.consultatipocambiomoneda.types.ObjectFactory;
import mx.com.sky.sel.proxyclients.pagwebconsultas.consultatipocambiomoneda.types.TipoCambioOutput;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaTipoCambioMoneda",
            targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaTipoCambio/ConsultaTipoCambioMoneda")
@XmlSeeAlso({ ObjectFactory.class })
public interface ConsultaTipoCambioMoneda {


    /**
     *
     * @param tipoCambio
     * @param organization
     * @param respuesta
     * @param respuestadesc
     */
    @WebMethod(action = "process")
    @RequestWrapper(localName = "process",
                    targetNamespace =
                    "http://xmlns.oracle.com/SKYConsultas/ConsultaTipoCambio/ConsultaTipoCambioMoneda",
                    className = "mx.com.sky.sel.proxyclients.pagwebconsultas.consultatipocambiomoneda.types.Process")
    @ResponseWrapper(localName = "processResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/SKYConsultas/ConsultaTipoCambio/ConsultaTipoCambioMoneda",
                     className =
                     "mx.com.sky.sel.proxyclients.pagwebconsultas.consultatipocambiomoneda.types.ProcessResponse")
    public void process(@WebParam(name = "Organization",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYConsultas/ConsultaTipoCambio/ConsultaTipoCambioMoneda")
                        String organization,
                        @WebParam(name = "respuesta",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYConsultas/ConsultaTipoCambio/ConsultaTipoCambioMoneda",
                                  mode = WebParam.Mode.OUT) Holder<String> respuesta,
                        @WebParam(name = "respuestadesc",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYConsultas/ConsultaTipoCambio/ConsultaTipoCambioMoneda",
                                  mode = WebParam.Mode.OUT) Holder<String> respuestadesc,
                        @WebParam(name = "tipoCambio",
                                  targetNamespace =
                                  "http://xmlns.oracle.com/SKYConsultas/ConsultaTipoCambio/ConsultaTipoCambioMoneda",
                                  mode = WebParam.Mode.OUT) Holder<TipoCambioOutput> tipoCambio);

}
