<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ConsultarInformacionFiscal" targetNamespace="http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarInformacionFiscal" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarInformacionFiscal" xmlns:ns1="http://www.sky.com.mx/EnterpriseObjects/Sel/ConsultarInformacionFiscal" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:documentation>
    <abstractWSDL>https://qaselsoa.sky.com.mx:443/soa-infra/services/SEL_Interface/ConsultarInformacionFiscalSelInterface!20220322-2018/WSDLs/ConsultarInformacionFiscal.wsdl</abstractWSDL>
  </wsdl:documentation>
  <plnk:partnerLinkType name="ConsultarInformacionFiscal">
    <plnk:role name="ConsultarInformacionFiscalProvider" portType="client:ConsultarInformacionFiscal"/>
  </plnk:partnerLinkType>
  <wsdl:types>
    <schema xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://www.sky.com.mx/EnterpriseObjects/Sel/ConsultarInformacionFiscal" schemaLocation="ConsultarInformacionFiscalSelEBM.xsd"/>
    </schema>
  </wsdl:types>
  <wsdl:message name="ConsultarInformacionFiscalRequestMessage">
    <wsdl:part name="payload" element="ns1:ConsultarInformacionFiscalRequest"/>
  </wsdl:message>
  <wsdl:message name="ConsultarInformacionFiscalResponseMessage">
    <wsdl:part name="payload" element="ns1:ConsultarInformacionFiscalResponse"/>
  </wsdl:message>
  <wsdl:portType name="ConsultarInformacionFiscal">
    <wsdl:operation name="ConsultarInformacionFiscal">
      <wsdl:input message="client:ConsultarInformacionFiscalRequestMessage"/>
      <wsdl:output message="client:ConsultarInformacionFiscalResponseMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="ConsultarInformacionFiscalBinding" type="client:ConsultarInformacionFiscal">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="ConsultarInformacionFiscal">
      <soap:operation style="document" soapAction="http://xmlns.sky.com.mx/InterfaceServices/Sel/ConsultarInformacionFiscal/ConsultarInformacionFiscal"/>
      <wsdl:input>
        <soap:body use="literal" parts="payload"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" parts="payload"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="ConsultarInformacionFiscal_ep">
    <wsdl:port name="ConsultarInformacionFiscal_pt" binding="client:ConsultarInformacionFiscalBinding">
      <soap:address location="https://qaselsoa.sky.com.mx:443/soa-infra/services/SEL_Interface/ConsultarInformacionFiscalSelInterface/ConsultarInformacionFiscal_ep"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>