
package mx.com.sky.sel.proxyclients.soainterface.consultasaldoproducto;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseservices.soa.consultasaldoproductointerface.ConsultaSaldoProductoRequestEBMType;
import mx.com.sky.enterpriseservices.soa.consultasaldoproductointerface.ConsultaSaldoProductoResponseEBMType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ConsultaSaldoProductoSoaInterface",
            targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaSaldoProductoSoaInterface")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ mx.com.sky.soasky.ObjectFactory.class, mx.com.sky.enterpriseobjects.sel.common.v1.ObjectFactory.class,
              mx.com.sky.enterpriseservices.soa.consultasaldoproductointerface.ObjectFactory.class })
public interface ConsultaSaldoProductoSoaInterface {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseservices.soa.consultasaldoproductointerface.ConsultaSaldoProductoResponseEBMType
     */
    @WebMethod(action =
               "http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaSaldoProductoSoaInterface/consultarSaldoProducto")
    @WebResult(name = "ConsultaSaldoProductoResponseEBM",
               targetNamespace = "http://www.sky.com.mx/EnterpriseServices/Soa/ConsultaSaldoProductoInterface",
               partName = "payload")
    public ConsultaSaldoProductoResponseEBMType consultarSaldoProducto(@WebParam(name =
                                                                                 "ConsultaSaldoProductoRequestEBM",
                                                                                 targetNamespace =
                                                                                 "http://www.sky.com.mx/EnterpriseServices/Soa/ConsultaSaldoProductoInterface",
                                                                                 partName = "payload")
                                                                       ConsultaSaldoProductoRequestEBMType payload);

}
