
package mx.com.sky.sel.proxyclients.soainterface.consultasaldoproducto;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ConsultaSaldoProductoSoaInterface_ep",
                  targetNamespace = "http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaSaldoProductoSoaInterface",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/ConsultaSaldoProductoSoaInterface/ConsultaSaldoProductoSoaInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSoa%2FConsultaSaldoProductoSoaInterface%7DConsultaSaldoProductoSoaInterface_ep")
public class ConsultaSaldoProductoSoaInterfaceEp extends Service {

    private final static URL CONSULTASALDOPRODUCTOSOAINTERFACEEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTASALDOPRODUCTOSOAINTERFACEEP_EXCEPTION;
    private final static QName CONSULTASALDOPRODUCTOSOAINTERFACEEP_QNAME =
        new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaSaldoProductoSoaInterface",
                  "ConsultaSaldoProductoSoaInterface_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/SOA_Interface/ConsultaSaldoProductoSoaInterface/ConsultaSaldoProductoSoaInterface_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FInterfaceServices%2FSoa%2FConsultaSaldoProductoSoaInterface%7DConsultaSaldoProductoSoaInterface_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTASALDOPRODUCTOSOAINTERFACEEP_WSDL_LOCATION = url;
        CONSULTASALDOPRODUCTOSOAINTERFACEEP_EXCEPTION = e;
    }

    public ConsultaSaldoProductoSoaInterfaceEp() {
        super(__getWsdlLocation(), CONSULTASALDOPRODUCTOSOAINTERFACEEP_QNAME);
    }

    public ConsultaSaldoProductoSoaInterfaceEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTASALDOPRODUCTOSOAINTERFACEEP_QNAME, features);
    }

    public ConsultaSaldoProductoSoaInterfaceEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTASALDOPRODUCTOSOAINTERFACEEP_QNAME);
    }

    public ConsultaSaldoProductoSoaInterfaceEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTASALDOPRODUCTOSOAINTERFACEEP_QNAME, features);
    }

    public ConsultaSaldoProductoSoaInterfaceEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaSaldoProductoSoaInterfaceEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaSaldoProductoSoaInterface
     */
    @WebEndpoint(name = "ConsultaSaldoProductoSoaInterface_pt")
    public ConsultaSaldoProductoSoaInterface getConsultaSaldoProductoSoaInterfacePt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaSaldoProductoSoaInterface",
                                       "ConsultaSaldoProductoSoaInterface_pt"),
                             ConsultaSaldoProductoSoaInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaSaldoProductoSoaInterface
     */
    @WebEndpoint(name = "ConsultaSaldoProductoSoaInterface_pt")
    public ConsultaSaldoProductoSoaInterface getConsultaSaldoProductoSoaInterfacePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/InterfaceServices/Soa/ConsultaSaldoProductoSoaInterface",
                                       "ConsultaSaldoProductoSoaInterface_pt"), ConsultaSaldoProductoSoaInterface.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTASALDOPRODUCTOSOAINTERFACEEP_EXCEPTION != null) {
            throw CONSULTASALDOPRODUCTOSOAINTERFACEEP_EXCEPTION;
        }
        return CONSULTASALDOPRODUCTOSOAINTERFACEEP_WSDL_LOCATION;
    }

}
