
package mx.com.sky.sel.proxyclients.selebf.modificarpasswordregistro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseflowmessage.sel.modificarpasswordregistro.ModificarPasswordRegistroRequestEBMType;
import mx.com.sky.enterpriseflowmessage.sel.modificarpasswordregistro.ModificarPasswordRegistroResponseEBMType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ModificarPasswordRegistroSelEBF",
            targetNamespace = "http://xmlns.sky.com.mx/EnterpriseFlows/Sel/ModificarPasswordRegistro")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ mx.com.sky.enterpriseflowmessage.sel.modificarpasswordregistro.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.common.v1.ObjectFactory.class,
              mx.com.sky.xmlns.enterpriseflows.sel.modificarpasswordregistro.ObjectFactory.class
    })
public interface ModificarPasswordRegistroSelEBF {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseflowmessage.sel.modificarpasswordregistro.ModificarPasswordRegistroResponseEBMType
     */
    @WebMethod(action =
               "http://xmlns.sky.com.mx/EnterpriseFlows/Sel/ModificarPasswordRegistro/modificarPaswwordRegistroSel")
    @WebResult(name = "ModificarPasswordRegistroResponseEBM",
               targetNamespace = "http://www.sky.com.mx/EnterpriseFlowMessage/Sel/ModificarPasswordRegistro",
               partName = "payload")
    public ModificarPasswordRegistroResponseEBMType modificarPasswordRegistroSel(@WebParam(name =
                                                                                           "ModificarPasswordRegistroRequestEBM",
                                                                                           targetNamespace =
                                                                                           "http://www.sky.com.mx/EnterpriseFlowMessage/Sel/ModificarPasswordRegistro",
                                                                                           partName = "payload")
                                                                                 ModificarPasswordRegistroRequestEBMType payload);

}
