package mx.com.sky.sel.proxyclients.pagwebss.batchaltasolicitudessw;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class BatchAltaSolicitudesDeServicioWebClient {
    public static void main(String[] args) {
        BatchAltaSolicitudesDeServicioWeb_Service batchAltaSolicitudesDeServicioWeb_Service =
            new BatchAltaSolicitudesDeServicioWeb_Service();
        BatchAltaSolicitudesDeServicioWeb batchAltaSolicitudesDeServicioWeb =
            batchAltaSolicitudesDeServicioWeb_Service.getBatchAltaSolicitudesDeServicioWeb();
        // Add your code to call the desired methods.


    }
}
