
package mx.com.sky.sel.proxyclients.pagwebss.batchaltasolicitudessw;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "BatchAltaSolicitudesDeServicioWeb",
                  targetNamespace = "http://xmlns.oracle.com/BatchAltaSolicitudesDeServicioWeb",
                  wsdlLocation =
                  "https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebss/BatchAltaSolicitudesDeServicioWeb/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FBatchAltaSolicitudesDeServicioWeb%7DBatchAltaSolicitudesDeServicioWeb")
public class BatchAltaSolicitudesDeServicioWeb_Service extends Service {

    private final static URL BATCHALTASOLICITUDESDESERVICIOWEB_WSDL_LOCATION;
    private final static WebServiceException BATCHALTASOLICITUDESDESERVICIOWEB_EXCEPTION;
    private final static QName BATCHALTASOLICITUDESDESERVICIOWEB_QNAME =
        new QName("http://xmlns.oracle.com/BatchAltaSolicitudesDeServicioWeb", "BatchAltaSolicitudesDeServicioWeb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://qaselsoa.sky.com.mx:443/soa-infra/services/pagwebss/BatchAltaSolicitudesDeServicioWeb/client?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FBatchAltaSolicitudesDeServicioWeb%7DBatchAltaSolicitudesDeServicioWeb");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BATCHALTASOLICITUDESDESERVICIOWEB_WSDL_LOCATION = url;
        BATCHALTASOLICITUDESDESERVICIOWEB_EXCEPTION = e;
    }

    public BatchAltaSolicitudesDeServicioWeb_Service() {
        super(__getWsdlLocation(), BATCHALTASOLICITUDESDESERVICIOWEB_QNAME);
    }

    public BatchAltaSolicitudesDeServicioWeb_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), BATCHALTASOLICITUDESDESERVICIOWEB_QNAME, features);
    }

    public BatchAltaSolicitudesDeServicioWeb_Service(URL wsdlLocation) {
        super(wsdlLocation, BATCHALTASOLICITUDESDESERVICIOWEB_QNAME);
    }

    public BatchAltaSolicitudesDeServicioWeb_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BATCHALTASOLICITUDESDESERVICIOWEB_QNAME, features);
    }

    public BatchAltaSolicitudesDeServicioWeb_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BatchAltaSolicitudesDeServicioWeb_Service(URL wsdlLocation, QName serviceName,
                                                     WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BatchAltaSolicitudesDeServicioWeb
     */
    @WebEndpoint(name = "BatchAltaSolicitudesDeServicioWeb")
    public BatchAltaSolicitudesDeServicioWeb getBatchAltaSolicitudesDeServicioWeb() {
        return super.getPort(new QName("http://xmlns.oracle.com/BatchAltaSolicitudesDeServicioWeb",
                                       "BatchAltaSolicitudesDeServicioWeb"), BatchAltaSolicitudesDeServicioWeb.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BatchAltaSolicitudesDeServicioWeb
     */
    @WebEndpoint(name = "BatchAltaSolicitudesDeServicioWeb")
    public BatchAltaSolicitudesDeServicioWeb getBatchAltaSolicitudesDeServicioWeb(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/BatchAltaSolicitudesDeServicioWeb",
                                       "BatchAltaSolicitudesDeServicioWeb"), BatchAltaSolicitudesDeServicioWeb.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (BATCHALTASOLICITUDESDESERVICIOWEB_EXCEPTION != null) {
            throw BATCHALTASOLICITUDESDESERVICIOWEB_EXCEPTION;
        }
        return BATCHALTASOLICITUDESDESERVICIOWEB_WSDL_LOCATION;
    }

}
