
package mx.com.sky.sel.proxyclients.selebf.crearregistro;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CrearRegistroSelEBF_ep",
                  targetNamespace = "http://xmlns.sky.com.mx/EnterpriseFlows/Sel/CrearRegistro",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_EBF/CrearRegistroSelEBF/CrearRegistroSelEBF_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FEnterpriseFlows%2FSel%2FCrearRegistro%7DCrearRegistroSelEBF_ep")
public class CrearRegistroSelEBFEp extends Service {

    private final static URL CREARREGISTROSELEBFEP_WSDL_LOCATION;
    private final static WebServiceException CREARREGISTROSELEBFEP_EXCEPTION;
    private final static QName CREARREGISTROSELEBFEP_QNAME =
        new QName("http://xmlns.sky.com.mx/EnterpriseFlows/Sel/CrearRegistro", "CrearRegistroSelEBF_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/SEL_EBF/CrearRegistroSelEBF/CrearRegistroSelEBF_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.sky.com.mx%2FEnterpriseFlows%2FSel%2FCrearRegistro%7DCrearRegistroSelEBF_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREARREGISTROSELEBFEP_WSDL_LOCATION = url;
        CREARREGISTROSELEBFEP_EXCEPTION = e;
    }

    public CrearRegistroSelEBFEp() {
        super(__getWsdlLocation(), CREARREGISTROSELEBFEP_QNAME);
    }

    public CrearRegistroSelEBFEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREARREGISTROSELEBFEP_QNAME, features);
    }

    public CrearRegistroSelEBFEp(URL wsdlLocation) {
        super(wsdlLocation, CREARREGISTROSELEBFEP_QNAME);
    }

    public CrearRegistroSelEBFEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREARREGISTROSELEBFEP_QNAME, features);
    }

    public CrearRegistroSelEBFEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrearRegistroSelEBFEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CrearRegistroSelEBF
     */
    @WebEndpoint(name = "CrearRegistroSelEBF_pt")
    public CrearRegistroSelEBF getCrearRegistroSelEBFPt() {
        return super.getPort(new QName("http://xmlns.sky.com.mx/EnterpriseFlows/Sel/CrearRegistro",
                                       "CrearRegistroSelEBF_pt"), CrearRegistroSelEBF.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrearRegistroSelEBF
     */
    @WebEndpoint(name = "CrearRegistroSelEBF_pt")
    public CrearRegistroSelEBF getCrearRegistroSelEBFPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.sky.com.mx/EnterpriseFlows/Sel/CrearRegistro",
                                       "CrearRegistroSelEBF_pt"), CrearRegistroSelEBF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREARREGISTROSELEBFEP_EXCEPTION != null) {
            throw CREARREGISTROSELEBFEP_EXCEPTION;
        }
        return CREARREGISTROSELEBFEP_WSDL_LOCATION;
    }

}
