
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultapaqueteall;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "consultapaqueteall_client_ep",
                  targetNamespace = "http://xmlns.oracle.com/SKYConsultas/ConsultaPaquete/ConsultaPaqueteAll",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaPaquete/consultapaqueteall_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKYConsultas%2FConsultaPaquete%2FConsultaPaqueteAll%7Dconsultapaqueteall_client_ep")
public class ConsultapaqueteallClientEp extends Service {

    private final static URL CONSULTAPAQUETEALLCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTAPAQUETEALLCLIENTEP_EXCEPTION;
    private final static QName CONSULTAPAQUETEALLCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaPaquete/ConsultaPaqueteAll",
                  "consultapaqueteall_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaPaquete/consultapaqueteall_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKYConsultas%2FConsultaPaquete%2FConsultaPaqueteAll%7Dconsultapaqueteall_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTAPAQUETEALLCLIENTEP_WSDL_LOCATION = url;
        CONSULTAPAQUETEALLCLIENTEP_EXCEPTION = e;
    }

    public ConsultapaqueteallClientEp() {
        super(__getWsdlLocation(), CONSULTAPAQUETEALLCLIENTEP_QNAME);
    }

    public ConsultapaqueteallClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTAPAQUETEALLCLIENTEP_QNAME, features);
    }

    public ConsultapaqueteallClientEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTAPAQUETEALLCLIENTEP_QNAME);
    }

    public ConsultapaqueteallClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTAPAQUETEALLCLIENTEP_QNAME, features);
    }

    public ConsultapaqueteallClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultapaqueteallClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaPaqueteAll
     */
    @WebEndpoint(name = "ConsultaPaqueteAll_pt")
    public ConsultaPaqueteAll getConsultaPaqueteAllPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaPaquete/ConsultaPaqueteAll",
                                       "ConsultaPaqueteAll_pt"), ConsultaPaqueteAll.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaPaqueteAll
     */
    @WebEndpoint(name = "ConsultaPaqueteAll_pt")
    public ConsultaPaqueteAll getConsultaPaqueteAllPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaPaquete/ConsultaPaqueteAll",
                                       "ConsultaPaqueteAll_pt"), ConsultaPaqueteAll.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTAPAQUETEALLCLIENTEP_EXCEPTION != null) {
            throw CONSULTAPAQUETEALLCLIENTEP_EXCEPTION;
        }
        return CONSULTAPAQUETEALLCLIENTEP_WSDL_LOCATION;
    }

}
