package mx.com.sky.sel.proxyclients.pagwebss.consultatablabatch;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class ConsultaTablaBatchSSClient {
    public static void main(String[] args) {
        ConsultaTablaBatchSS_Service consultaTablaBatchSS_Service = new ConsultaTablaBatchSS_Service();
        ConsultaTablaBatchSS consultaTablaBatchSS = consultaTablaBatchSS_Service.getConsultaTablaBatchSS();
        // Add your code to call the desired methods.


    }
}
