
package mx.com.sky.sel.proxyclients.cfdiinterface.consultar.obtenerfactura;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseflowmessage.soasap.obtenerfacturapdf.ObtenerFacturaPDFRequestType;
import mx.com.sky.enterpriseflowmessage.soasap.obtenerfacturapdf.ObtenerFacturaPDFResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-b170214.1743
 * Generated source version: 2.2
 *
 */
@WebService(name = "ObtenerFacturaPDF",
            targetNamespace = "http://xmlns.sky.com.mx/EnterpriseFlows/Sap/ObtenerFacturaPDF")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ mx.com.sky.enterpriseflowmessage.soasap.obtenerfacturapdf.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sap.common.v3.ObjectFactory.class })
public interface ObtenerFacturaPDF {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseflowmessage.soasap.obtenerfacturapdf.ObtenerFacturaPDFResponseType
     */
    @WebMethod(action = "http://xmlns.sky.com.mx/EnterpriseFlows/Sap/ObtenerFacturaPDF/obtenerfacturapdf")
    @WebResult(name = "ObtenerFacturaPDFResponse",
               targetNamespace = "http://www.sky.com.mx/EnterpriseFlowMessage/SoaSap/ObtenerFacturaPDF",
               partName = "payload")
    public ObtenerFacturaPDFResponseType obtenerfacturapdf(@WebParam(name = "ObtenerFacturaPDFRequest",
                                                                     targetNamespace =
                                                                     "http://www.sky.com.mx/EnterpriseFlowMessage/SoaSap/ObtenerFacturaPDF",
                                                                     partName = "payload")
                                                           ObtenerFacturaPDFRequestType payload);

}
