
package mx.com.sky.sel.proxyclients.pagwebconsultas.consultasolicitudservicio;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "consulta_solcitudesservicio_client_ep",
                  targetNamespace =
                  "http://xmlns.oracle.com/SKYConsultas/ConsultaCambioTitular/Consulta_SolcitudesServicio",
                  wsdlLocation =
                  "https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaCambioTitular/consulta_solcitudesservicio_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKYConsultas%2FConsultaCambioTitular%2FConsulta_SolcitudesServicio%7Dconsulta_solcitudesservicio_client_ep")
public class ConsultaSolcitudesservicioClientEp extends Service {

    private final static URL CONSULTASOLCITUDESSERVICIOCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException CONSULTASOLCITUDESSERVICIOCLIENTEP_EXCEPTION;
    private final static QName CONSULTASOLCITUDESSERVICIOCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaCambioTitular/Consulta_SolcitudesServicio",
                  "consulta_solcitudesservicio_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("https://preselsoa.sky.com.mx:443/soa-infra/services/pagwebconsultas/ConsultaCambioTitular/consulta_solcitudesservicio_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2FSKYConsultas%2FConsultaCambioTitular%2FConsulta_SolcitudesServicio%7Dconsulta_solcitudesservicio_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTASOLCITUDESSERVICIOCLIENTEP_WSDL_LOCATION = url;
        CONSULTASOLCITUDESSERVICIOCLIENTEP_EXCEPTION = e;
    }

    public ConsultaSolcitudesservicioClientEp() {
        super(__getWsdlLocation(), CONSULTASOLCITUDESSERVICIOCLIENTEP_QNAME);
    }

    public ConsultaSolcitudesservicioClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTASOLCITUDESSERVICIOCLIENTEP_QNAME, features);
    }

    public ConsultaSolcitudesservicioClientEp(URL wsdlLocation) {
        super(wsdlLocation, CONSULTASOLCITUDESSERVICIOCLIENTEP_QNAME);
    }

    public ConsultaSolcitudesservicioClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTASOLCITUDESSERVICIOCLIENTEP_QNAME, features);
    }

    public ConsultaSolcitudesservicioClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultaSolcitudesservicioClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ConsultaSolcitudesServicio
     */
    @WebEndpoint(name = "Consulta_SolcitudesServicio_pt")
    public ConsultaSolcitudesServicio getConsultaSolcitudesServicioPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaCambioTitular/Consulta_SolcitudesServicio",
                                       "Consulta_SolcitudesServicio_pt"), ConsultaSolcitudesServicio.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultaSolcitudesServicio
     */
    @WebEndpoint(name = "Consulta_SolcitudesServicio_pt")
    public ConsultaSolcitudesServicio getConsultaSolcitudesServicioPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/SKYConsultas/ConsultaCambioTitular/Consulta_SolcitudesServicio",
                                       "Consulta_SolcitudesServicio_pt"), ConsultaSolcitudesServicio.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTASOLCITUDESSERVICIOCLIENTEP_EXCEPTION != null) {
            throw CONSULTASOLCITUDESSERVICIOCLIENTEP_EXCEPTION;
        }
        return CONSULTASOLCITUDESSERVICIOCLIENTEP_WSDL_LOCATION;
    }

}
