
package mx.com.sky.sel.proxyclients.pagweb.validacrecimientostya;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import mx.com.sky.sel.proxyclients.pagweb.validacrecimientostya.types.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "ValidaCrecimientos_TYA",
            targetNamespace = "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA")
@XmlSeeAlso({ ObjectFactory.class })
public interface ValidaCrecimientosTYA {


    /**
     *
     * @param valida
     * @param codigoError
     * @param cuentaSKY
     * @param estatus
     * @param meses
     * @param numEquipos
     * @param descError
     * @param paquete
     * @param hmc
     */
    @WebMethod(action = "validaCrecimientosTYA")
    @RequestWrapper(localName = "validaCrecimientosTYA",
                    targetNamespace =
                    "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA",
                    className = "mx.com.sky.sel.proxyclients.pagweb.validacrecimientostya.types.ValidaCrecimientosTYA")
    @ResponseWrapper(localName = "validaCrecimientosTYAResponse",
                     targetNamespace =
                     "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA",
                     className =
                     "mx.com.sky.sel.proxyclients.pagweb.validacrecimientostya.types.ValidaCrecimientosTYAResponse")
    public void validaCrecimientosTYA(@WebParam(name = "cuentaSKY",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA")
                                      String cuentaSKY,
                                      @WebParam(name = "valida",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA",
                                                mode = WebParam.Mode.OUT) Holder<String> valida,
                                      @WebParam(name = "estatus",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA",
                                                mode = WebParam.Mode.OUT) Holder<String> estatus,
                                      @WebParam(name = "numEquipos",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA",
                                                mode = WebParam.Mode.OUT) Holder<String> numEquipos,
                                      @WebParam(name = "paquete",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA",
                                                mode = WebParam.Mode.OUT) Holder<String> paquete,
                                      @WebParam(name = "meses",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA",
                                                mode = WebParam.Mode.OUT) Holder<String> meses,
                                      @WebParam(name = "hmc",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA",
                                                mode = WebParam.Mode.OUT) Holder<String> hmc,
                                      @WebParam(name = "codigoError",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA",
                                                mode = WebParam.Mode.OUT) Holder<String> codigoError,
                                      @WebParam(name = "descError",
                                                targetNamespace =
                                                "http://xmlns.oracle.com/SKY_CrecimientosEquipos/SKY_Crecimientos/ValidaCrecimientos_TYA",
                                                mode = WebParam.Mode.OUT) Holder<String> descError);

}
