
package mx.com.sky.sel.proxyclients.selebf.gestionapagonuevatdc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;

import mx.com.sky.enterpriseflowmessages.sel.gestionarpagocontdc.GestionarPagoConTDCRequestEBMType;
import mx.com.sky.enterpriseflowmessages.sel.gestionarpagocontdc.GestionarPagoConTDCResponseEBMType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "GestionarPagoConTDCSelEBF",
            targetNamespace =
            "http://xmlns.sky.com.mx/EnterpriseFlows/Sel/GestionarPagoConTDC")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ mx.com.sky.enterpriseflowmessages.sel.gestionarpagocontdc.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.common.v1.ObjectFactory.class,
              mx.com.sky.enterpriseobjects.sel.tarjetapagoebo.ObjectFactory.class
    })
public interface GestionarPagoConTDCSelEBF {


    /**
     *
     * @param payload
     * @return
     *     returns mx.com.sky.enterpriseflowmessages.sel.gestionarpagocontdc.GestionarPagoConTDCResponseEBMType
     */
    @WebMethod(action =
               "http://xmlns.sky.com.mx/EnterpriseFlows/Sel/GestionarPagoConTDC/gestionarPagoConTDC")
    @WebResult(name = "GestionarPagoConTDCResponseEBM",
               targetNamespace =
               "http://www.sky.com.mx/EnterpriseFlowMessages/Sel/GestionarPagoConTDC",
               partName = "payload")
    public GestionarPagoConTDCResponseEBMType gestionarPagoConTDC(@WebParam(name =
                                                                            "GestionarPagoConTDCRequestEBM",
                                                                            targetNamespace =
                                                                            "http://www.sky.com.mx/EnterpriseFlowMessages/Sel/GestionarPagoConTDC",
                                                                            partName =
                                                                            "payload")
                                                                  GestionarPagoConTDCRequestEBMType payload);

}
