package mx.com.sky.sel.proxyclients.pagweb.passwordreset;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.2.1.2.0.1648
public class PasswordResetClient {
    public static void main(String[] args) {
        PasswordReset_Service passwordReset_Service = new PasswordReset_Service();
        PasswordReset passwordReset = passwordReset_Service.getPasswordReset();
        // Add your code to call the desired methods.


    }
}
